/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


public class Advertise extends javax.swing.JPanel {

    /**
     * Creates new form Advertise
     */
    public Advertise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adv_Label_Heading = new javax.swing.JLabel();
        Adv_LPane_SearchAdv = new javax.swing.JLayeredPane();
        CustStage_Search_CmbBox_CustStageName = new javax.swing.JComboBox<>();
        Adv_Search_Label_AdvTypeID = new javax.swing.JLabel();
        Adv_Search_Label_AdvTypeName = new javax.swing.JLabel();
        CustStage_Search_CmbBox_CustStageID = new javax.swing.JComboBox<>();
        CustStage_Scp_1 = new javax.swing.JScrollPane();
        Adv_Search_Table_Adv = new javax.swing.JTable();
        Adv_Search_Label_Date = new javax.swing.JLabel();
        CustStage_Search_CmbBox_CustStageName1 = new javax.swing.JComboBox<>();
        Adv_Search_Btn_Search = new javax.swing.JButton();
        Adv_Search_Btn_ShowAllAdv = new javax.swing.JButton();
        Adv_LPane_AddAdv = new javax.swing.JLayeredPane();
        Adv_AddAdv_Label_AdvTypeID = new javax.swing.JLabel();
        Adv_AddAdv_Label_AdvTypeName = new javax.swing.JLabel();
        CustStage_Scp_2 = new javax.swing.JScrollPane();
        Adv_AddAdv_Table_Adv = new javax.swing.JTable();
        Adv_AddAdv_Label_AdvTotal = new javax.swing.JLabel();
        Adv_AddAdv_TextF_AdvTotal = new javax.swing.JTextField();
        Adv_AddAdv_Btn_AddAdv = new javax.swing.JButton();
        Adv_AddAdv_Btn_RemoveAdded = new javax.swing.JButton();
        Adv_AddAdv_Btn_Update = new javax.swing.JButton();
        Adv_AddAdv_CmbBox_AdvTypeID = new javax.swing.JComboBox<>();
        Adv_AddAdv_CmbBox_AdvTypeName = new javax.swing.JComboBox<>();
        Adv_Btn_Back = new javax.swing.JButton();
        Adv_Btn_Ok = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        Adv_Label_Heading.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Adv_Label_Heading.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Label_Heading.setText("Advertising");

        Adv_LPane_SearchAdv.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Search Advertisings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        Adv_LPane_SearchAdv.setPreferredSize(new java.awt.Dimension(1052, 216));
        Adv_LPane_SearchAdv.setVerifyInputWhenFocusTarget(false);

        CustStage_Search_CmbBox_CustStageName.setEditable(true);
        CustStage_Search_CmbBox_CustStageName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CustStage_Search_CmbBox_CustStageName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustStage_Search_CmbBox_CustStageName.setToolTipText("Advertise Type Name");
        CustStage_Search_CmbBox_CustStageName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustStage_Search_CmbBox_CustStageName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustStage_Search_CmbBox_CustStageNameActionPerformed(evt);
            }
        });

        Adv_Search_Label_AdvTypeID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_Search_Label_AdvTypeID.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Search_Label_AdvTypeID.setText("Advertise Type ID : ");

        Adv_Search_Label_AdvTypeName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_Search_Label_AdvTypeName.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Search_Label_AdvTypeName.setText("Advertise Type Name : ");

        CustStage_Search_CmbBox_CustStageID.setEditable(true);
        CustStage_Search_CmbBox_CustStageID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CustStage_Search_CmbBox_CustStageID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustStage_Search_CmbBox_CustStageID.setToolTipText("Advertise Type ID");
        CustStage_Search_CmbBox_CustStageID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustStage_Search_CmbBox_CustStageID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustStage_Search_CmbBox_CustStageIDActionPerformed(evt);
            }
        });

        Adv_Search_Table_Adv.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Adv_Search_Table_Adv.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Search_Table_Adv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Advertise Type ID", "Advertise Type Name", "Date", "Employee Name", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Adv_Search_Table_Adv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_Search_Table_Adv.setGridColor(new java.awt.Color(102, 102, 102));
        Adv_Search_Table_Adv.setIntercellSpacing(new java.awt.Dimension(1, 0));
        Adv_Search_Table_Adv.setRowHeight(17);
        Adv_Search_Table_Adv.setSelectionBackground(new java.awt.Color(46, 141, 216));
        Adv_Search_Table_Adv.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_1.setViewportView(Adv_Search_Table_Adv);

        Adv_Search_Label_Date.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_Search_Label_Date.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Search_Label_Date.setText("Date : ");

        CustStage_Search_CmbBox_CustStageName1.setEditable(true);
        CustStage_Search_CmbBox_CustStageName1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CustStage_Search_CmbBox_CustStageName1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustStage_Search_CmbBox_CustStageName1.setToolTipText("Date");
        CustStage_Search_CmbBox_CustStageName1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustStage_Search_CmbBox_CustStageName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustStage_Search_CmbBox_CustStageName1ActionPerformed(evt);
            }
        });

        Adv_Search_Btn_Search.setBackground(new java.awt.Color(204, 204, 204));
        Adv_Search_Btn_Search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Adv_Search_Btn_Search.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Search_Btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/search (2).png"))); // NOI18N
        Adv_Search_Btn_Search.setText("Search");
        Adv_Search_Btn_Search.setToolTipText("Search");
        Adv_Search_Btn_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_Search_Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_Search_Btn_SearchActionPerformed(evt);
            }
        });

        Adv_Search_Btn_ShowAllAdv.setBackground(new java.awt.Color(204, 204, 204));
        Adv_Search_Btn_ShowAllAdv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Adv_Search_Btn_ShowAllAdv.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Search_Btn_ShowAllAdv.setText("Show All Advertisings");
        Adv_Search_Btn_ShowAllAdv.setToolTipText("Show All Advertisings");
        Adv_Search_Btn_ShowAllAdv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_Search_Btn_ShowAllAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_Search_Btn_ShowAllAdvActionPerformed(evt);
            }
        });

        Adv_LPane_SearchAdv.setLayer(CustStage_Search_CmbBox_CustStageName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(Adv_Search_Label_AdvTypeID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(Adv_Search_Label_AdvTypeName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(CustStage_Search_CmbBox_CustStageID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(CustStage_Scp_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(Adv_Search_Label_Date, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(CustStage_Search_CmbBox_CustStageName1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(Adv_Search_Btn_Search, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_SearchAdv.setLayer(Adv_Search_Btn_ShowAllAdv, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Adv_LPane_SearchAdvLayout = new javax.swing.GroupLayout(Adv_LPane_SearchAdv);
        Adv_LPane_SearchAdv.setLayout(Adv_LPane_SearchAdvLayout);
        Adv_LPane_SearchAdvLayout.setHorizontalGroup(
            Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Adv_LPane_SearchAdvLayout.createSequentialGroup()
                .addGroup(Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Adv_LPane_SearchAdvLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Adv_Search_Label_AdvTypeName)
                            .addComponent(Adv_Search_Label_AdvTypeID)
                            .addComponent(Adv_Search_Label_Date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustStage_Search_CmbBox_CustStageID, 0, 157, Short.MAX_VALUE)
                            .addComponent(CustStage_Search_CmbBox_CustStageName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustStage_Search_CmbBox_CustStageName1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Adv_LPane_SearchAdvLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Adv_Search_Btn_Search))
                    .addGroup(Adv_LPane_SearchAdvLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Adv_Search_Btn_ShowAllAdv)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        Adv_LPane_SearchAdvLayout.setVerticalGroup(
            Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Adv_LPane_SearchAdvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adv_Search_Label_AdvTypeID)
                    .addComponent(CustStage_Search_CmbBox_CustStageID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adv_Search_Label_AdvTypeName)
                    .addComponent(CustStage_Search_CmbBox_CustStageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Adv_LPane_SearchAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adv_Search_Label_Date)
                    .addComponent(CustStage_Search_CmbBox_CustStageName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Adv_Search_Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adv_Search_Btn_ShowAllAdv)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(Adv_LPane_SearchAdvLayout.createSequentialGroup()
                .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        Adv_LPane_AddAdv.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add Advertisings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        Adv_LPane_AddAdv.setPreferredSize(new java.awt.Dimension(1052, 216));
        Adv_LPane_AddAdv.setVerifyInputWhenFocusTarget(false);

        Adv_AddAdv_Label_AdvTypeID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_AddAdv_Label_AdvTypeID.setForeground(new java.awt.Color(51, 51, 51));
        Adv_AddAdv_Label_AdvTypeID.setText("Advertise Type ID : ");

        Adv_AddAdv_Label_AdvTypeName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_AddAdv_Label_AdvTypeName.setForeground(new java.awt.Color(51, 51, 51));
        Adv_AddAdv_Label_AdvTypeName.setText("Advertise Type Name : ");

        Adv_AddAdv_Table_Adv.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Adv_AddAdv_Table_Adv.setForeground(new java.awt.Color(51, 51, 51));
        Adv_AddAdv_Table_Adv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Advertise Type ID", "Advertise Type Name", "Date", "Employee Name", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Adv_AddAdv_Table_Adv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_AddAdv_Table_Adv.setGridColor(new java.awt.Color(102, 102, 102));
        Adv_AddAdv_Table_Adv.setIntercellSpacing(new java.awt.Dimension(1, 0));
        Adv_AddAdv_Table_Adv.setRowHeight(17);
        Adv_AddAdv_Table_Adv.setSelectionBackground(new java.awt.Color(46, 141, 216));
        Adv_AddAdv_Table_Adv.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_2.setViewportView(Adv_AddAdv_Table_Adv);

        Adv_AddAdv_Label_AdvTotal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_AddAdv_Label_AdvTotal.setForeground(new java.awt.Color(51, 51, 51));
        Adv_AddAdv_Label_AdvTotal.setText(" Total : ");

        Adv_AddAdv_TextF_AdvTotal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Adv_AddAdv_TextF_AdvTotal.setToolTipText("Total From Advertising");
        Adv_AddAdv_TextF_AdvTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_AddAdv_TextF_AdvTotalActionPerformed(evt);
            }
        });

        Adv_AddAdv_Btn_AddAdv.setBackground(new java.awt.Color(204, 204, 204));
        Adv_AddAdv_Btn_AddAdv.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_AddAdv_Btn_AddAdv.setForeground(new java.awt.Color(51, 51, 51));
        Adv_AddAdv_Btn_AddAdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Add_plus.png"))); // NOI18N
        Adv_AddAdv_Btn_AddAdv.setText("Add");
        Adv_AddAdv_Btn_AddAdv.setToolTipText("Add Customer Stage");
        Adv_AddAdv_Btn_AddAdv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Adv_AddAdv_Btn_RemoveAdded.setBackground(new java.awt.Color(204, 204, 204));
        Adv_AddAdv_Btn_RemoveAdded.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_AddAdv_Btn_RemoveAdded.setForeground(new java.awt.Color(51, 51, 51));
        Adv_AddAdv_Btn_RemoveAdded.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/trash_bin.png"))); // NOI18N
        Adv_AddAdv_Btn_RemoveAdded.setText("Remove");
        Adv_AddAdv_Btn_RemoveAdded.setToolTipText("Remove Added");
        Adv_AddAdv_Btn_RemoveAdded.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_AddAdv_Btn_RemoveAdded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_AddAdv_Btn_RemoveAddedActionPerformed(evt);
            }
        });

        Adv_AddAdv_Btn_Update.setBackground(new java.awt.Color(204, 204, 204));
        Adv_AddAdv_Btn_Update.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Adv_AddAdv_Btn_Update.setForeground(new java.awt.Color(51, 51, 51));
        Adv_AddAdv_Btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/check.png"))); // NOI18N
        Adv_AddAdv_Btn_Update.setText("Update");
        Adv_AddAdv_Btn_Update.setToolTipText("Update");
        Adv_AddAdv_Btn_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_AddAdv_Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_AddAdv_Btn_UpdateActionPerformed(evt);
            }
        });

        Adv_AddAdv_CmbBox_AdvTypeID.setEditable(true);
        Adv_AddAdv_CmbBox_AdvTypeID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Adv_AddAdv_CmbBox_AdvTypeID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        Adv_AddAdv_CmbBox_AdvTypeID.setToolTipText("Advertise Type ID");
        Adv_AddAdv_CmbBox_AdvTypeID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_AddAdv_CmbBox_AdvTypeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_AddAdv_CmbBox_AdvTypeIDActionPerformed(evt);
            }
        });

        Adv_AddAdv_CmbBox_AdvTypeName.setEditable(true);
        Adv_AddAdv_CmbBox_AdvTypeName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Adv_AddAdv_CmbBox_AdvTypeName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        Adv_AddAdv_CmbBox_AdvTypeName.setToolTipText("Advertise Type Name");
        Adv_AddAdv_CmbBox_AdvTypeName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_AddAdv_CmbBox_AdvTypeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_AddAdv_CmbBox_AdvTypeNameActionPerformed(evt);
            }
        });

        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_Label_AdvTypeID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_Label_AdvTypeName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(CustStage_Scp_2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_Label_AdvTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_TextF_AdvTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_Btn_AddAdv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_Btn_RemoveAdded, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_Btn_Update, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_CmbBox_AdvTypeID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Adv_LPane_AddAdv.setLayer(Adv_AddAdv_CmbBox_AdvTypeName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Adv_LPane_AddAdvLayout = new javax.swing.GroupLayout(Adv_LPane_AddAdv);
        Adv_LPane_AddAdv.setLayout(Adv_LPane_AddAdvLayout);
        Adv_LPane_AddAdvLayout.setHorizontalGroup(
            Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                        .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Adv_AddAdv_Label_AdvTypeName)
                            .addComponent(Adv_AddAdv_Label_AdvTypeID)
                            .addComponent(Adv_AddAdv_Label_AdvTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Adv_AddAdv_TextF_AdvTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Adv_AddAdv_CmbBox_AdvTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Adv_AddAdv_CmbBox_AdvTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(Adv_AddAdv_Btn_AddAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustStage_Scp_2, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                        .addComponent(Adv_AddAdv_Btn_RemoveAdded)
                        .addGap(14, 14, 14))
                    .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                        .addComponent(Adv_AddAdv_Btn_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        Adv_LPane_AddAdvLayout.setVerticalGroup(
            Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustStage_Scp_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                                .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Adv_AddAdv_Label_AdvTypeID)
                                    .addComponent(Adv_AddAdv_CmbBox_AdvTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Adv_AddAdv_Label_AdvTypeName)
                                    .addComponent(Adv_AddAdv_CmbBox_AdvTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Adv_LPane_AddAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Adv_AddAdv_Label_AdvTotal)
                                    .addComponent(Adv_AddAdv_TextF_AdvTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(Adv_AddAdv_Btn_AddAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 41, Short.MAX_VALUE))
                            .addGroup(Adv_LPane_AddAdvLayout.createSequentialGroup()
                                .addComponent(Adv_AddAdv_Btn_RemoveAdded)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Adv_AddAdv_Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );

        Adv_Btn_Back.setBackground(new java.awt.Color(204, 204, 204));
        Adv_Btn_Back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Adv_Btn_Back.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Btn_Back.setText("Back");
        Adv_Btn_Back.setToolTipText("Back");
        Adv_Btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_Btn_BackActionPerformed(evt);
            }
        });

        Adv_Btn_Ok.setBackground(new java.awt.Color(204, 204, 204));
        Adv_Btn_Ok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Adv_Btn_Ok.setForeground(new java.awt.Color(51, 51, 51));
        Adv_Btn_Ok.setText("Ok");
        Adv_Btn_Ok.setToolTipText("Ok");
        Adv_Btn_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adv_Btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adv_Btn_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Adv_Label_Heading)
                                .addGap(474, 474, 474))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Adv_Btn_Back)
                                .addGap(6, 6, 6)
                                .addComponent(Adv_Btn_Ok)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Adv_LPane_AddAdv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                            .addComponent(Adv_LPane_SearchAdv, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Adv_Label_Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adv_LPane_SearchAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adv_LPane_AddAdv, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Adv_Btn_Back)
                    .addComponent(Adv_Btn_Ok))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CustStage_Search_CmbBox_CustStageNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustStage_Search_CmbBox_CustStageNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustStage_Search_CmbBox_CustStageNameActionPerformed

    private void Adv_Search_Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_Search_Btn_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_Search_Btn_SearchActionPerformed

    private void Adv_Search_Btn_ShowAllAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_Search_Btn_ShowAllAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_Search_Btn_ShowAllAdvActionPerformed

    private void CustStage_Search_CmbBox_CustStageIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustStage_Search_CmbBox_CustStageIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustStage_Search_CmbBox_CustStageIDActionPerformed

    private void CustStage_Search_CmbBox_CustStageName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustStage_Search_CmbBox_CustStageName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustStage_Search_CmbBox_CustStageName1ActionPerformed

    private void Adv_AddAdv_TextF_AdvTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_AddAdv_TextF_AdvTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_AddAdv_TextF_AdvTotalActionPerformed

    private void Adv_AddAdv_Btn_RemoveAddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_AddAdv_Btn_RemoveAddedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_AddAdv_Btn_RemoveAddedActionPerformed

    private void Adv_Btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_Btn_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_Btn_OkActionPerformed

    private void Adv_Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_Btn_BackActionPerformed
        // TODSup_Label_Headingcode here:
    }//GEN-LAST:event_Adv_Btn_BackActionPerformed

    private void Adv_AddAdv_Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_AddAdv_Btn_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_AddAdv_Btn_UpdateActionPerformed

    private void Adv_AddAdv_CmbBox_AdvTypeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_AddAdv_CmbBox_AdvTypeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_AddAdv_CmbBox_AdvTypeIDActionPerformed

    private void Adv_AddAdv_CmbBox_AdvTypeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adv_AddAdv_CmbBox_AdvTypeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adv_AddAdv_CmbBox_AdvTypeNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adv_AddAdv_Btn_AddAdv;
    private javax.swing.JButton Adv_AddAdv_Btn_RemoveAdded;
    private javax.swing.JButton Adv_AddAdv_Btn_Update;
    private javax.swing.JComboBox<String> Adv_AddAdv_CmbBox_AdvTypeID;
    private javax.swing.JComboBox<String> Adv_AddAdv_CmbBox_AdvTypeName;
    private javax.swing.JLabel Adv_AddAdv_Label_AdvTotal;
    private javax.swing.JLabel Adv_AddAdv_Label_AdvTypeID;
    private javax.swing.JLabel Adv_AddAdv_Label_AdvTypeName;
    private javax.swing.JTable Adv_AddAdv_Table_Adv;
    private javax.swing.JTextField Adv_AddAdv_TextF_AdvTotal;
    private javax.swing.JButton Adv_Btn_Back;
    private javax.swing.JButton Adv_Btn_Ok;
    private javax.swing.JLayeredPane Adv_LPane_AddAdv;
    private javax.swing.JLayeredPane Adv_LPane_SearchAdv;
    private javax.swing.JLabel Adv_Label_Heading;
    private javax.swing.JButton Adv_Search_Btn_Search;
    private javax.swing.JButton Adv_Search_Btn_ShowAllAdv;
    private javax.swing.JLabel Adv_Search_Label_AdvTypeID;
    private javax.swing.JLabel Adv_Search_Label_AdvTypeName;
    private javax.swing.JLabel Adv_Search_Label_Date;
    private javax.swing.JTable Adv_Search_Table_Adv;
    private javax.swing.JScrollPane CustStage_Scp_1;
    private javax.swing.JScrollPane CustStage_Scp_2;
    private javax.swing.JComboBox<String> CustStage_Search_CmbBox_CustStageID;
    private javax.swing.JComboBox<String> CustStage_Search_CmbBox_CustStageName;
    private javax.swing.JComboBox<String> CustStage_Search_CmbBox_CustStageName1;
    // End of variables declaration//GEN-END:variables
}
