/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


public class ContPers extends javax.swing.JPanel {

    /**
     * Creates new form ContPers
     */
    public ContPers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContPers_Label_Heading = new javax.swing.JLabel();
        Sup_LPane_SearchSup = new javax.swing.JLayeredPane();
        ContPers_Search_Label_SupID = new javax.swing.JLabel();
        ContPers_Search_CmbBox_SupID = new javax.swing.JComboBox<>();
        ContPers_Search_Label_SupName = new javax.swing.JLabel();
        ContPers_Search_CmbBox_SupName = new javax.swing.JComboBox<>();
        EditSup_Scp_1 = new javax.swing.JScrollPane();
        ContPers_Search_Table_Sup = new javax.swing.JTable();
        ContPers_ScP_1 = new javax.swing.JScrollPane();
        ContPers_Search_Table_ContPers = new javax.swing.JTable();
        ContPers_Search_CmbBox_ContPersID = new javax.swing.JComboBox<>();
        ContPers_Search_CmbBox_ContPersName = new javax.swing.JComboBox<>();
        ContPers_Search_Label_ContPersID = new javax.swing.JLabel();
        ContPers_Search_Label_ContPersName = new javax.swing.JLabel();
        ContPers_Search_Btn_Search = new javax.swing.JButton();
        ContPers_Search_Btn_ShowAllSup = new javax.swing.JButton();
        ContPers_Search_Btn_ShowAllContPers = new javax.swing.JButton();
        ContPers_LPane_AdEdReContPers = new javax.swing.JLayeredPane();
        ContPers_AdEdRe_Label_ContPersID = new javax.swing.JLabel();
        ContPers_AdEdRe_Label_ContPersFName = new javax.swing.JLabel();
        ContPers_AdEdRe_Label_ContPersLName = new javax.swing.JLabel();
        ContPers_AdEdRe_Label_ContPersContNo = new javax.swing.JLabel();
        ContPers_AdEdRe_Label_ContPersEmail = new javax.swing.JLabel();
        ContPers_AdEdRe_TextF_ContPersID = new javax.swing.JTextField();
        ContPers_AdEdRe_TextF_ContPersFName = new javax.swing.JTextField();
        ContPers_AdEdRe_TextF_ContPersLName = new javax.swing.JTextField();
        ContPers_AdEdRe_TextF_ContPersEmail = new javax.swing.JTextField();
        ContPers_AdEdRe_TextF_ContPersContNo = new javax.swing.JTextField();
        AddSup_Scp_1 = new javax.swing.JScrollPane();
        ContPers_AdEdRe_Table_ContPers = new javax.swing.JTable();
        ContPers_AdEdRe_Btn_AddContPers = new javax.swing.JButton();
        ContPers_AdEdRe_Btn_EditContPers = new javax.swing.JButton();
        ContPers_AdEdRe_Btn_Update = new javax.swing.JButton();
        ContPers_AdEdRe_Btn_RemoveUpdate = new javax.swing.JButton();
        ContPers_AdEdRe_Label_SupID = new javax.swing.JLabel();
        ContPers_AdEdRe_TextF_SupID = new javax.swing.JTextField();
        ContPers_AdEdRe_Btn_RemoveContPers = new javax.swing.JButton();
        ContPers_Btn_Back = new javax.swing.JButton();
        ContPers_Btn_Ok = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        ContPers_Label_Heading.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ContPers_Label_Heading.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Label_Heading.setText("Contact Person");

        Sup_LPane_SearchSup.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Search Contact Persons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        Sup_LPane_SearchSup.setPreferredSize(new java.awt.Dimension(1052, 216));
        Sup_LPane_SearchSup.setVerifyInputWhenFocusTarget(false);

        ContPers_Search_Label_SupID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_Search_Label_SupID.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Label_SupID.setText("Suplier ID : ");

        ContPers_Search_CmbBox_SupID.setEditable(true);
        ContPers_Search_CmbBox_SupID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_Search_CmbBox_SupID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        ContPers_Search_CmbBox_SupID.setToolTipText("Suplier ID");
        ContPers_Search_CmbBox_SupID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_CmbBox_SupID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Search_CmbBox_SupIDActionPerformed(evt);
            }
        });

        ContPers_Search_Label_SupName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_Search_Label_SupName.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Label_SupName.setText("Suplier Name : ");

        ContPers_Search_CmbBox_SupName.setEditable(true);
        ContPers_Search_CmbBox_SupName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_Search_CmbBox_SupName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        ContPers_Search_CmbBox_SupName.setToolTipText("Suplier Name");
        ContPers_Search_CmbBox_SupName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_CmbBox_SupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Search_CmbBox_SupNameActionPerformed(evt);
            }
        });

        ContPers_Search_Table_Sup.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_Search_Table_Sup.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Table_Sup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suplier ID", "Suplier Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ContPers_Search_Table_Sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_Table_Sup.setIntercellSpacing(new java.awt.Dimension(1, 0));
        ContPers_Search_Table_Sup.setRowHeight(17);
        ContPers_Search_Table_Sup.setSelectionBackground(new java.awt.Color(46, 141, 216));
        ContPers_Search_Table_Sup.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        EditSup_Scp_1.setViewportView(ContPers_Search_Table_Sup);

        ContPers_Search_Table_ContPers.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_Search_Table_ContPers.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Table_ContPers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contact Person ID", "Contact Person Name", "Contact No", "E-Mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ContPers_Search_Table_ContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_Table_ContPers.setIntercellSpacing(new java.awt.Dimension(1, 0));
        ContPers_Search_Table_ContPers.setRowHeight(17);
        ContPers_Search_Table_ContPers.setSelectionBackground(new java.awt.Color(46, 141, 216));
        ContPers_Search_Table_ContPers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ContPers_ScP_1.setViewportView(ContPers_Search_Table_ContPers);

        ContPers_Search_CmbBox_ContPersID.setEditable(true);
        ContPers_Search_CmbBox_ContPersID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_Search_CmbBox_ContPersID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        ContPers_Search_CmbBox_ContPersID.setToolTipText("Contact Person ID");
        ContPers_Search_CmbBox_ContPersID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_CmbBox_ContPersID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Search_CmbBox_ContPersIDActionPerformed(evt);
            }
        });

        ContPers_Search_CmbBox_ContPersName.setEditable(true);
        ContPers_Search_CmbBox_ContPersName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_Search_CmbBox_ContPersName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        ContPers_Search_CmbBox_ContPersName.setToolTipText("Contact Person Name");
        ContPers_Search_CmbBox_ContPersName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_CmbBox_ContPersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Search_CmbBox_ContPersNameActionPerformed(evt);
            }
        });

        ContPers_Search_Label_ContPersID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_Search_Label_ContPersID.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Label_ContPersID.setText("Cont. Person ID : ");

        ContPers_Search_Label_ContPersName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_Search_Label_ContPersName.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Label_ContPersName.setText("Cont. Person Name : ");

        ContPers_Search_Btn_Search.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_Search_Btn_Search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ContPers_Search_Btn_Search.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/search (2).png"))); // NOI18N
        ContPers_Search_Btn_Search.setText("Search");
        ContPers_Search_Btn_Search.setToolTipText("Search");
        ContPers_Search_Btn_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Search_Btn_SearchActionPerformed(evt);
            }
        });

        ContPers_Search_Btn_ShowAllSup.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_Search_Btn_ShowAllSup.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        ContPers_Search_Btn_ShowAllSup.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Btn_ShowAllSup.setText("Show All Supliers");
        ContPers_Search_Btn_ShowAllSup.setToolTipText("Show All Supliers");
        ContPers_Search_Btn_ShowAllSup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_Btn_ShowAllSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Search_Btn_ShowAllSupActionPerformed(evt);
            }
        });

        ContPers_Search_Btn_ShowAllContPers.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_Search_Btn_ShowAllContPers.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        ContPers_Search_Btn_ShowAllContPers.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Search_Btn_ShowAllContPers.setText("Show All Cont. Persons");
        ContPers_Search_Btn_ShowAllContPers.setToolTipText("Show All Cont. Persons");
        ContPers_Search_Btn_ShowAllContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Search_Btn_ShowAllContPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Search_Btn_ShowAllContPersActionPerformed(evt);
            }
        });

        Sup_LPane_SearchSup.setLayer(ContPers_Search_Label_SupID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_CmbBox_SupID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_Label_SupName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_CmbBox_SupName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(EditSup_Scp_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_ScP_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_CmbBox_ContPersID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_CmbBox_ContPersName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_Label_ContPersID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_Label_ContPersName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_Btn_Search, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_Btn_ShowAllSup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sup_LPane_SearchSup.setLayer(ContPers_Search_Btn_ShowAllContPers, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Sup_LPane_SearchSupLayout = new javax.swing.GroupLayout(Sup_LPane_SearchSup);
        Sup_LPane_SearchSup.setLayout(Sup_LPane_SearchSupLayout);
        Sup_LPane_SearchSupLayout.setHorizontalGroup(
            Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sup_LPane_SearchSupLayout.createSequentialGroup()
                .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Sup_LPane_SearchSupLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(ContPers_Search_Btn_Search)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ContPers_Search_Btn_ShowAllSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContPers_Search_Btn_ShowAllContPers, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                        .addGroup(Sup_LPane_SearchSupLayout.createSequentialGroup()
                            .addComponent(ContPers_Search_Label_ContPersName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ContPers_Search_CmbBox_ContPersName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Sup_LPane_SearchSupLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sup_LPane_SearchSupLayout.createSequentialGroup()
                                .addComponent(ContPers_Search_Label_SupName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContPers_Search_CmbBox_SupName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sup_LPane_SearchSupLayout.createSequentialGroup()
                                .addComponent(ContPers_Search_Label_SupID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContPers_Search_CmbBox_SupID, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sup_LPane_SearchSupLayout.createSequentialGroup()
                                .addComponent(ContPers_Search_Label_ContPersID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContPers_Search_CmbBox_ContPersID, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(ContPers_ScP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditSup_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Sup_LPane_SearchSupLayout.setVerticalGroup(
            Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sup_LPane_SearchSupLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContPers_Search_CmbBox_SupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContPers_Search_Label_SupID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContPers_Search_CmbBox_SupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContPers_Search_Label_SupName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContPers_Search_CmbBox_ContPersID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContPers_Search_Label_ContPersID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContPers_Search_CmbBox_ContPersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContPers_Search_Label_ContPersName))
                .addGap(6, 6, 6)
                .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContPers_Search_Btn_ShowAllSup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ContPers_Search_Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ContPers_Search_Btn_ShowAllContPers, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(Sup_LPane_SearchSupLayout.createSequentialGroup()
                .addGroup(Sup_LPane_SearchSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(EditSup_Scp_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(ContPers_ScP_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContPers_LPane_AdEdReContPers.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add / Edit / Remove Contact Person", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        ContPers_LPane_AdEdReContPers.setPreferredSize(new java.awt.Dimension(1052, 216));
        ContPers_LPane_AdEdReContPers.setVerifyInputWhenFocusTarget(false);

        ContPers_AdEdRe_Label_ContPersID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Label_ContPersID.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Label_ContPersID.setText("Cont. Person ID : ");

        ContPers_AdEdRe_Label_ContPersFName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Label_ContPersFName.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Label_ContPersFName.setText("Cont. Person First Name : ");

        ContPers_AdEdRe_Label_ContPersLName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Label_ContPersLName.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Label_ContPersLName.setText("Cont. Person Last Name : ");

        ContPers_AdEdRe_Label_ContPersContNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Label_ContPersContNo.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Label_ContPersContNo.setText("Contact No : ");

        ContPers_AdEdRe_Label_ContPersEmail.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Label_ContPersEmail.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Label_ContPersEmail.setText("E - mail : ");

        ContPers_AdEdRe_TextF_ContPersID.setEditable(false);
        ContPers_AdEdRe_TextF_ContPersID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_AdEdRe_TextF_ContPersID.setToolTipText("Contact Person ID");
        ContPers_AdEdRe_TextF_ContPersID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_TextF_ContPersIDActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_TextF_ContPersFName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_AdEdRe_TextF_ContPersFName.setToolTipText("Contact Person First Name");
        ContPers_AdEdRe_TextF_ContPersFName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ContPers_AdEdRe_TextF_ContPersFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_TextF_ContPersFNameActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_TextF_ContPersLName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_AdEdRe_TextF_ContPersLName.setToolTipText("Contact Person Last Name");
        ContPers_AdEdRe_TextF_ContPersLName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ContPers_AdEdRe_TextF_ContPersLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_TextF_ContPersLNameActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_TextF_ContPersEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_AdEdRe_TextF_ContPersEmail.setToolTipText("Contact Person E-mail Address");
        ContPers_AdEdRe_TextF_ContPersEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ContPers_AdEdRe_TextF_ContPersEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_TextF_ContPersEmailActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_TextF_ContPersContNo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_AdEdRe_TextF_ContPersContNo.setToolTipText("Contact Person Contact Number");
        ContPers_AdEdRe_TextF_ContPersContNo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ContPers_AdEdRe_TextF_ContPersContNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_TextF_ContPersContNoActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_Table_ContPers.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_AdEdRe_Table_ContPers.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Table_ContPers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suplier ID", "Contact Person ID", "Contact Person Name", "Contact No", "E-Mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ContPers_AdEdRe_Table_ContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_AdEdRe_Table_ContPers.setIntercellSpacing(new java.awt.Dimension(1, 0));
        ContPers_AdEdRe_Table_ContPers.setRowHeight(17);
        ContPers_AdEdRe_Table_ContPers.setSelectionBackground(new java.awt.Color(46, 141, 216));
        ContPers_AdEdRe_Table_ContPers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        AddSup_Scp_1.setViewportView(ContPers_AdEdRe_Table_ContPers);

        ContPers_AdEdRe_Btn_AddContPers.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_AdEdRe_Btn_AddContPers.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ContPers_AdEdRe_Btn_AddContPers.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Btn_AddContPers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Add_plus.png"))); // NOI18N
        ContPers_AdEdRe_Btn_AddContPers.setText("Add");
        ContPers_AdEdRe_Btn_AddContPers.setToolTipText("Add Contact Person");
        ContPers_AdEdRe_Btn_AddContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ContPers_AdEdRe_Btn_EditContPers.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_AdEdRe_Btn_EditContPers.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ContPers_AdEdRe_Btn_EditContPers.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Btn_EditContPers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Edit_pencil.png"))); // NOI18N
        ContPers_AdEdRe_Btn_EditContPers.setText("Edit");
        ContPers_AdEdRe_Btn_EditContPers.setToolTipText("Edit Contact Person");
        ContPers_AdEdRe_Btn_EditContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_AdEdRe_Btn_EditContPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_Btn_EditContPersActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_Btn_Update.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_AdEdRe_Btn_Update.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Btn_Update.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/check.png"))); // NOI18N
        ContPers_AdEdRe_Btn_Update.setText("Update");
        ContPers_AdEdRe_Btn_Update.setToolTipText("Update");
        ContPers_AdEdRe_Btn_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_AdEdRe_Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_Btn_UpdateActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_Btn_RemoveUpdate.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_AdEdRe_Btn_RemoveUpdate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Btn_RemoveUpdate.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Btn_RemoveUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/trash_bin.png"))); // NOI18N
        ContPers_AdEdRe_Btn_RemoveUpdate.setText("Remove");
        ContPers_AdEdRe_Btn_RemoveUpdate.setToolTipText("Remove Edit");
        ContPers_AdEdRe_Btn_RemoveUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_AdEdRe_Btn_RemoveUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_Btn_RemoveUpdateActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_Label_SupID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ContPers_AdEdRe_Label_SupID.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Label_SupID.setText("Suplier ID : ");

        ContPers_AdEdRe_TextF_SupID.setEditable(false);
        ContPers_AdEdRe_TextF_SupID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ContPers_AdEdRe_TextF_SupID.setToolTipText("Suplier ID");
        ContPers_AdEdRe_TextF_SupID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_TextF_SupIDActionPerformed(evt);
            }
        });

        ContPers_AdEdRe_Btn_RemoveContPers.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_AdEdRe_Btn_RemoveContPers.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ContPers_AdEdRe_Btn_RemoveContPers.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_AdEdRe_Btn_RemoveContPers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/trash_bin.png"))); // NOI18N
        ContPers_AdEdRe_Btn_RemoveContPers.setText("Remove");
        ContPers_AdEdRe_Btn_RemoveContPers.setToolTipText("Remove Contact Person");
        ContPers_AdEdRe_Btn_RemoveContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_AdEdRe_Btn_RemoveContPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_AdEdRe_Btn_RemoveContPersActionPerformed(evt);
            }
        });

        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Label_ContPersID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Label_ContPersFName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Label_ContPersLName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Label_ContPersContNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Label_ContPersEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_TextF_ContPersID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_TextF_ContPersFName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_TextF_ContPersLName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_TextF_ContPersEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_TextF_ContPersContNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(AddSup_Scp_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Btn_AddContPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Btn_EditContPers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Btn_Update, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Btn_RemoveUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Label_SupID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_TextF_SupID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContPers_LPane_AdEdReContPers.setLayer(ContPers_AdEdRe_Btn_RemoveContPers, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ContPers_LPane_AdEdReContPersLayout = new javax.swing.GroupLayout(ContPers_LPane_AdEdReContPers);
        ContPers_LPane_AdEdReContPers.setLayout(ContPers_LPane_AdEdReContPersLayout);
        ContPers_LPane_AdEdReContPersLayout.setHorizontalGroup(
            ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(ContPers_AdEdRe_Label_ContPersID))
                                .addComponent(ContPers_AdEdRe_Label_ContPersFName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ContPers_AdEdRe_Label_ContPersLName, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(ContPers_AdEdRe_Label_SupID)
                            .addComponent(ContPers_AdEdRe_Label_ContPersContNo)
                            .addComponent(ContPers_AdEdRe_Label_ContPersEmail))
                        .addGap(4, 4, 4)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContPers_AdEdRe_TextF_SupID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersFName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersLName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersContNo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContPers_AdEdRe_Btn_AddContPers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ContPers_AdEdRe_Btn_EditContPers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ContPers_AdEdRe_Btn_RemoveContPers)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddSup_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContPers_AdEdRe_Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                        .addComponent(ContPers_AdEdRe_Btn_RemoveUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ContPers_LPane_AdEdReContPersLayout.setVerticalGroup(
            ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContPers_AdEdRe_TextF_SupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Label_SupID))
                        .addGap(6, 6, 6)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Label_ContPersID))
                        .addGap(6, 6, 6)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Label_ContPersFName))
                        .addGap(6, 6, 6)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Label_ContPersLName))
                        .addGap(6, 6, 6)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersContNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Label_ContPersContNo))
                        .addGap(6, 6, 6)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContPers_AdEdRe_TextF_ContPersEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Label_ContPersEmail))
                        .addGap(18, 18, 18)
                        .addGroup(ContPers_LPane_AdEdReContPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContPers_AdEdRe_Btn_AddContPers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Btn_EditContPers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContPers_AdEdRe_Btn_RemoveContPers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AddSup_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContPers_LPane_AdEdReContPersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ContPers_AdEdRe_Btn_RemoveUpdate)
                .addGap(74, 74, 74)
                .addComponent(ContPers_AdEdRe_Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        ContPers_Btn_Back.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_Btn_Back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ContPers_Btn_Back.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Btn_Back.setText("Back");
        ContPers_Btn_Back.setToolTipText("Back");
        ContPers_Btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Btn_BackActionPerformed(evt);
            }
        });

        ContPers_Btn_Ok.setBackground(new java.awt.Color(204, 204, 204));
        ContPers_Btn_Ok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ContPers_Btn_Ok.setForeground(new java.awt.Color(51, 51, 51));
        ContPers_Btn_Ok.setText("Ok");
        ContPers_Btn_Ok.setToolTipText("Ok");
        ContPers_Btn_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContPers_Btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContPers_Btn_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sup_LPane_SearchSup, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ContPers_Label_Heading)
                                .addGap(452, 452, 452))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ContPers_LPane_AdEdReContPers, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ContPers_Btn_Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContPers_Btn_Ok)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContPers_Label_Heading)
                .addGap(0, 0, 0)
                .addComponent(Sup_LPane_SearchSup, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContPers_LPane_AdEdReContPers, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContPers_Btn_Back)
                    .addComponent(ContPers_Btn_Ok, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ContPers_Search_CmbBox_SupIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Search_CmbBox_SupIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Search_CmbBox_SupIDActionPerformed

    private void ContPers_Search_CmbBox_SupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Search_CmbBox_SupNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Search_CmbBox_SupNameActionPerformed

    private void ContPers_Search_Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Search_Btn_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Search_Btn_SearchActionPerformed

    private void ContPers_Search_Btn_ShowAllSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Search_Btn_ShowAllSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Search_Btn_ShowAllSupActionPerformed

    private void ContPers_Search_CmbBox_ContPersIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Search_CmbBox_ContPersIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Search_CmbBox_ContPersIDActionPerformed

    private void ContPers_Search_CmbBox_ContPersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Search_CmbBox_ContPersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Search_CmbBox_ContPersNameActionPerformed

    private void ContPers_Search_Btn_ShowAllContPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Search_Btn_ShowAllContPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Search_Btn_ShowAllContPersActionPerformed

    private void ContPers_AdEdRe_TextF_ContPersIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_TextF_ContPersIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_TextF_ContPersIDActionPerformed

    private void ContPers_AdEdRe_TextF_ContPersFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_TextF_ContPersFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_TextF_ContPersFNameActionPerformed

    private void ContPers_AdEdRe_TextF_ContPersLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_TextF_ContPersLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_TextF_ContPersLNameActionPerformed

    private void ContPers_AdEdRe_TextF_ContPersEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_TextF_ContPersEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_TextF_ContPersEmailActionPerformed

    private void ContPers_AdEdRe_TextF_ContPersContNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_TextF_ContPersContNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_TextF_ContPersContNoActionPerformed

    private void ContPers_AdEdRe_Btn_EditContPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_Btn_EditContPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_Btn_EditContPersActionPerformed

    private void ContPers_AdEdRe_Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_Btn_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_Btn_UpdateActionPerformed

    private void ContPers_AdEdRe_Btn_RemoveUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_Btn_RemoveUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_Btn_RemoveUpdateActionPerformed

    private void ContPers_AdEdRe_TextF_SupIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_TextF_SupIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_TextF_SupIDActionPerformed

    private void ContPers_AdEdRe_Btn_RemoveContPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_AdEdRe_Btn_RemoveContPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_AdEdRe_Btn_RemoveContPersActionPerformed

    private void ContPers_Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Btn_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Btn_BackActionPerformed

    private void ContPers_Btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContPers_Btn_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContPers_Btn_OkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AddSup_Scp_1;
    private javax.swing.JButton ContPers_AdEdRe_Btn_AddContPers;
    private javax.swing.JButton ContPers_AdEdRe_Btn_EditContPers;
    private javax.swing.JButton ContPers_AdEdRe_Btn_RemoveContPers;
    private javax.swing.JButton ContPers_AdEdRe_Btn_RemoveUpdate;
    private javax.swing.JButton ContPers_AdEdRe_Btn_Update;
    private javax.swing.JLabel ContPers_AdEdRe_Label_ContPersContNo;
    private javax.swing.JLabel ContPers_AdEdRe_Label_ContPersEmail;
    private javax.swing.JLabel ContPers_AdEdRe_Label_ContPersFName;
    private javax.swing.JLabel ContPers_AdEdRe_Label_ContPersID;
    private javax.swing.JLabel ContPers_AdEdRe_Label_ContPersLName;
    private javax.swing.JLabel ContPers_AdEdRe_Label_SupID;
    private javax.swing.JTable ContPers_AdEdRe_Table_ContPers;
    private javax.swing.JTextField ContPers_AdEdRe_TextF_ContPersContNo;
    private javax.swing.JTextField ContPers_AdEdRe_TextF_ContPersEmail;
    private javax.swing.JTextField ContPers_AdEdRe_TextF_ContPersFName;
    private javax.swing.JTextField ContPers_AdEdRe_TextF_ContPersID;
    private javax.swing.JTextField ContPers_AdEdRe_TextF_ContPersLName;
    private javax.swing.JTextField ContPers_AdEdRe_TextF_SupID;
    public javax.swing.JButton ContPers_Btn_Back;
    public javax.swing.JButton ContPers_Btn_Ok;
    private javax.swing.JLayeredPane ContPers_LPane_AdEdReContPers;
    private javax.swing.JLabel ContPers_Label_Heading;
    private javax.swing.JScrollPane ContPers_ScP_1;
    private javax.swing.JButton ContPers_Search_Btn_Search;
    private javax.swing.JButton ContPers_Search_Btn_ShowAllContPers;
    private javax.swing.JButton ContPers_Search_Btn_ShowAllSup;
    private javax.swing.JComboBox<String> ContPers_Search_CmbBox_ContPersID;
    private javax.swing.JComboBox<String> ContPers_Search_CmbBox_ContPersName;
    private javax.swing.JComboBox<String> ContPers_Search_CmbBox_SupID;
    private javax.swing.JComboBox<String> ContPers_Search_CmbBox_SupName;
    private javax.swing.JLabel ContPers_Search_Label_ContPersID;
    private javax.swing.JLabel ContPers_Search_Label_ContPersName;
    private javax.swing.JLabel ContPers_Search_Label_SupID;
    private javax.swing.JLabel ContPers_Search_Label_SupName;
    private javax.swing.JTable ContPers_Search_Table_ContPers;
    private javax.swing.JTable ContPers_Search_Table_Sup;
    private javax.swing.JScrollPane EditSup_Scp_1;
    private javax.swing.JLayeredPane Sup_LPane_SearchSup;
    // End of variables declaration//GEN-END:variables
}
