/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


public class Donate extends javax.swing.JPanel {

    /**
     * Creates new form Donate
     */
    public Donate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Donate_Label_Heading = new javax.swing.JLabel();
        Donate_LPane_SearchDonate = new javax.swing.JLayeredPane();
        Donate_Search_Label_DonateID = new javax.swing.JLabel();
        CustStage_Search_CmbBox_CustStageID = new javax.swing.JComboBox<>();
        CustStage_Scp_1 = new javax.swing.JScrollPane();
        Donate_Search_Table_Doante = new javax.swing.JTable();
        Donate_Search_Label_Date = new javax.swing.JLabel();
        CustStage_Search_CmbBox_CustStageName1 = new javax.swing.JComboBox<>();
        Donate_Search_Btn_Search = new javax.swing.JButton();
        Donate_Search_Btn_ShowAllDonate = new javax.swing.JButton();
        DispItem_AddDisp_Label_Reson3 = new javax.swing.JLabel();
        Donate_Search_Label_Discription = new javax.swing.JLabel();
        AddCustStage_Scp_3 = new javax.swing.JScrollPane();
        Donate_Search_TextA_Discription = new javax.swing.JTextArea();
        Donate_Search_LPane_AddDonate = new javax.swing.JLayeredPane();
        Donate_Add_Label_DonateID = new javax.swing.JLabel();
        Donate_Add_TextF_ApprovedBy = new javax.swing.JTextField();
        Donate_Add_TextF_Amount = new javax.swing.JTextField();
        Donate_Add_TextF_DonateID = new javax.swing.JTextField();
        Donate_Add_Label_Discription = new javax.swing.JLabel();
        AddCustStage_Scp_2 = new javax.swing.JScrollPane();
        Donate_Add_TextA_Dicription = new javax.swing.JTextArea();
        Donate_Add_Label_Amount = new javax.swing.JLabel();
        Donate_Add_Label_ApprovedBy = new javax.swing.JLabel();
        Donate_Add_Btn_AddDonate = new javax.swing.JButton();
        Donate_Add_Btn_RemoveAdded = new javax.swing.JButton();
        AEmpPos_AdEdRe_Btn_Done = new javax.swing.JButton();
        CustStage_Scp_3 = new javax.swing.JScrollPane();
        Donate_Add_Table_Donate = new javax.swing.JTable();
        Donate_Btn_Back = new javax.swing.JButton();
        Donate_Add_Btn_Ok = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        Donate_Label_Heading.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Donate_Label_Heading.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Label_Heading.setText("Donations");

        Donate_LPane_SearchDonate.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Search Donations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        Donate_LPane_SearchDonate.setPreferredSize(new java.awt.Dimension(1052, 216));
        Donate_LPane_SearchDonate.setVerifyInputWhenFocusTarget(false);

        Donate_Search_Label_DonateID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Search_Label_DonateID.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Search_Label_DonateID.setText("Donation ID : ");

        CustStage_Search_CmbBox_CustStageID.setEditable(true);
        CustStage_Search_CmbBox_CustStageID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CustStage_Search_CmbBox_CustStageID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustStage_Search_CmbBox_CustStageID.setToolTipText("Donation ID");
        CustStage_Search_CmbBox_CustStageID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustStage_Search_CmbBox_CustStageID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustStage_Search_CmbBox_CustStageIDActionPerformed(evt);
            }
        });

        Donate_Search_Table_Doante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Donate_Search_Table_Doante.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Search_Table_Doante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donation ID", "Date", "Approved By", "Employee Name", "For What (Discription)", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Donate_Search_Table_Doante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donate_Search_Table_Doante.setGridColor(new java.awt.Color(102, 102, 102));
        Donate_Search_Table_Doante.setIntercellSpacing(new java.awt.Dimension(1, 0));
        Donate_Search_Table_Doante.setRowHeight(17);
        Donate_Search_Table_Doante.setSelectionBackground(new java.awt.Color(46, 141, 216));
        Donate_Search_Table_Doante.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_1.setViewportView(Donate_Search_Table_Doante);

        Donate_Search_Label_Date.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Search_Label_Date.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Search_Label_Date.setText("Date : ");

        CustStage_Search_CmbBox_CustStageName1.setEditable(true);
        CustStage_Search_CmbBox_CustStageName1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CustStage_Search_CmbBox_CustStageName1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustStage_Search_CmbBox_CustStageName1.setToolTipText("Date");
        CustStage_Search_CmbBox_CustStageName1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustStage_Search_CmbBox_CustStageName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustStage_Search_CmbBox_CustStageName1ActionPerformed(evt);
            }
        });

        Donate_Search_Btn_Search.setBackground(new java.awt.Color(204, 204, 204));
        Donate_Search_Btn_Search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Donate_Search_Btn_Search.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Search_Btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/search (2).png"))); // NOI18N
        Donate_Search_Btn_Search.setText("Search");
        Donate_Search_Btn_Search.setToolTipText("Search");
        Donate_Search_Btn_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donate_Search_Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Search_Btn_SearchActionPerformed(evt);
            }
        });

        Donate_Search_Btn_ShowAllDonate.setBackground(new java.awt.Color(204, 204, 204));
        Donate_Search_Btn_ShowAllDonate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Donate_Search_Btn_ShowAllDonate.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Search_Btn_ShowAllDonate.setText("Show All Donations");
        Donate_Search_Btn_ShowAllDonate.setToolTipText("Show All Donations");
        Donate_Search_Btn_ShowAllDonate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donate_Search_Btn_ShowAllDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Search_Btn_ShowAllDonateActionPerformed(evt);
            }
        });

        DispItem_AddDisp_Label_Reson3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        DispItem_AddDisp_Label_Reson3.setForeground(new java.awt.Color(51, 51, 51));
        DispItem_AddDisp_Label_Reson3.setText("Discription : ");

        Donate_Search_Label_Discription.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Search_Label_Discription.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Search_Label_Discription.setText("Discription : ");

        AddCustStage_Scp_3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AddCustStage_Scp_3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Donate_Search_TextA_Discription.setEditable(false);
        Donate_Search_TextA_Discription.setColumns(20);
        Donate_Search_TextA_Discription.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Donate_Search_TextA_Discription.setLineWrap(true);
        Donate_Search_TextA_Discription.setRows(5);
        Donate_Search_TextA_Discription.setToolTipText("For What (Discroption)");
        Donate_Search_TextA_Discription.setWrapStyleWord(true);
        AddCustStage_Scp_3.setViewportView(Donate_Search_TextA_Discription);

        Donate_LPane_SearchDonate.setLayer(Donate_Search_Label_DonateID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(CustStage_Search_CmbBox_CustStageID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(CustStage_Scp_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(Donate_Search_Label_Date, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(CustStage_Search_CmbBox_CustStageName1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(Donate_Search_Btn_Search, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(Donate_Search_Btn_ShowAllDonate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(DispItem_AddDisp_Label_Reson3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(Donate_Search_Label_Discription, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_LPane_SearchDonate.setLayer(AddCustStage_Scp_3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Donate_LPane_SearchDonateLayout = new javax.swing.GroupLayout(Donate_LPane_SearchDonate);
        Donate_LPane_SearchDonate.setLayout(Donate_LPane_SearchDonateLayout);
        Donate_LPane_SearchDonateLayout.setHorizontalGroup(
            Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                        .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Donate_LPane_SearchDonateLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(Donate_Search_Label_Discription))
                            .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Donate_Search_Label_DonateID)
                                    .addComponent(Donate_Search_Label_Date))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Donate_Search_Btn_Search))
                                    .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CustStage_Search_CmbBox_CustStageName1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CustStage_Search_CmbBox_CustStageID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Donate_LPane_SearchDonateLayout.createSequentialGroup()
                        .addComponent(Donate_Search_Btn_ShowAllDonate)
                        .addGap(27, 27, 27)))
                .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustStage_Scp_1)
                    .addComponent(AddCustStage_Scp_3))
                .addContainerGap())
            .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                    .addGap(498, 498, 498)
                    .addComponent(DispItem_AddDisp_Label_Reson3)
                    .addContainerGap(484, Short.MAX_VALUE)))
        );
        Donate_LPane_SearchDonateLayout.setVerticalGroup(
            Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Donate_LPane_SearchDonateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Donate_Search_Label_DonateID)
                            .addComponent(CustStage_Search_CmbBox_CustStageID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Donate_Search_Label_Date)
                            .addComponent(CustStage_Search_CmbBox_CustStageName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Donate_Search_Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Donate_Search_Btn_ShowAllDonate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                        .addComponent(Donate_Search_Label_Discription)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(AddCustStage_Scp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(Donate_LPane_SearchDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Donate_LPane_SearchDonateLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(DispItem_AddDisp_Label_Reson3)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        Donate_Search_LPane_AddDonate.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add Donations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        Donate_Search_LPane_AddDonate.setPreferredSize(new java.awt.Dimension(1052, 216));
        Donate_Search_LPane_AddDonate.setVerifyInputWhenFocusTarget(false);

        Donate_Add_Label_DonateID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Add_Label_DonateID.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Label_DonateID.setText("Donation ID : ");

        Donate_Add_TextF_ApprovedBy.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Donate_Add_TextF_ApprovedBy.setToolTipText("Approved By");
        Donate_Add_TextF_ApprovedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Add_TextF_ApprovedByActionPerformed(evt);
            }
        });

        Donate_Add_TextF_Amount.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Donate_Add_TextF_Amount.setToolTipText("Donation Amount");
        Donate_Add_TextF_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Add_TextF_AmountActionPerformed(evt);
            }
        });

        Donate_Add_TextF_DonateID.setEditable(false);
        Donate_Add_TextF_DonateID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Donate_Add_TextF_DonateID.setToolTipText("Donation ID");
        Donate_Add_TextF_DonateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Add_TextF_DonateIDActionPerformed(evt);
            }
        });

        Donate_Add_Label_Discription.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Add_Label_Discription.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Label_Discription.setText("Discription : ");

        AddCustStage_Scp_2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AddCustStage_Scp_2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Donate_Add_TextA_Dicription.setColumns(20);
        Donate_Add_TextA_Dicription.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Donate_Add_TextA_Dicription.setLineWrap(true);
        Donate_Add_TextA_Dicription.setRows(5);
        Donate_Add_TextA_Dicription.setToolTipText("For What (Discroption)");
        Donate_Add_TextA_Dicription.setWrapStyleWord(true);
        AddCustStage_Scp_2.setViewportView(Donate_Add_TextA_Dicription);

        Donate_Add_Label_Amount.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Add_Label_Amount.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Label_Amount.setText("Amount : ");

        Donate_Add_Label_ApprovedBy.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Add_Label_ApprovedBy.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Label_ApprovedBy.setText("Approved By : ");

        Donate_Add_Btn_AddDonate.setBackground(new java.awt.Color(204, 204, 204));
        Donate_Add_Btn_AddDonate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Add_Btn_AddDonate.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Btn_AddDonate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Add_plus.png"))); // NOI18N
        Donate_Add_Btn_AddDonate.setText("Add");
        Donate_Add_Btn_AddDonate.setToolTipText("Add Donation");
        Donate_Add_Btn_AddDonate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Donate_Add_Btn_RemoveAdded.setBackground(new java.awt.Color(204, 204, 204));
        Donate_Add_Btn_RemoveAdded.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Donate_Add_Btn_RemoveAdded.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Btn_RemoveAdded.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/trash_bin.png"))); // NOI18N
        Donate_Add_Btn_RemoveAdded.setText("Remove");
        Donate_Add_Btn_RemoveAdded.setToolTipText("Remove Added");
        Donate_Add_Btn_RemoveAdded.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donate_Add_Btn_RemoveAdded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Add_Btn_RemoveAddedActionPerformed(evt);
            }
        });

        AEmpPos_AdEdRe_Btn_Done.setBackground(new java.awt.Color(204, 204, 204));
        AEmpPos_AdEdRe_Btn_Done.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AEmpPos_AdEdRe_Btn_Done.setForeground(new java.awt.Color(51, 51, 51));
        AEmpPos_AdEdRe_Btn_Done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/check.png"))); // NOI18N
        AEmpPos_AdEdRe_Btn_Done.setText("Done");
        AEmpPos_AdEdRe_Btn_Done.setToolTipText("Done");
        AEmpPos_AdEdRe_Btn_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AEmpPos_AdEdRe_Btn_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEmpPos_AdEdRe_Btn_DoneActionPerformed(evt);
            }
        });

        Donate_Add_Table_Donate.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Donate_Add_Table_Donate.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Table_Donate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donation ID", "Date", "Approved By", "Employee Name", "For What (Discription)", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Donate_Add_Table_Donate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donate_Add_Table_Donate.setGridColor(new java.awt.Color(102, 102, 102));
        Donate_Add_Table_Donate.setIntercellSpacing(new java.awt.Dimension(1, 0));
        Donate_Add_Table_Donate.setRowHeight(17);
        Donate_Add_Table_Donate.setSelectionBackground(new java.awt.Color(46, 141, 216));
        Donate_Add_Table_Donate.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_3.setViewportView(Donate_Add_Table_Donate);

        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_Label_DonateID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_TextF_ApprovedBy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_TextF_Amount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_TextF_DonateID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_Label_Discription, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(AddCustStage_Scp_2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_Label_Amount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_Label_ApprovedBy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_Btn_AddDonate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(Donate_Add_Btn_RemoveAdded, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(AEmpPos_AdEdRe_Btn_Done, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Donate_Search_LPane_AddDonate.setLayer(CustStage_Scp_3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Donate_Search_LPane_AddDonateLayout = new javax.swing.GroupLayout(Donate_Search_LPane_AddDonate);
        Donate_Search_LPane_AddDonate.setLayout(Donate_Search_LPane_AddDonateLayout);
        Donate_Search_LPane_AddDonateLayout.setHorizontalGroup(
            Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Donate_Add_Label_Discription)
                            .addComponent(Donate_Add_Label_Amount)
                            .addComponent(Donate_Add_Label_DonateID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Donate_Add_Label_ApprovedBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Donate_Add_TextF_DonateID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                        .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Donate_Add_TextF_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Donate_Add_TextF_ApprovedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Donate_Add_Btn_AddDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddCustStage_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustStage_Scp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Donate_Add_Btn_RemoveAdded)
                    .addComponent(AEmpPos_AdEdRe_Btn_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Donate_Search_LPane_AddDonateLayout.setVerticalGroup(
            Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                        .addComponent(Donate_Add_Btn_RemoveAdded)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AEmpPos_AdEdRe_Btn_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Donate_Add_Label_DonateID)
                            .addComponent(Donate_Add_TextF_DonateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Donate_Add_Label_Discription)
                            .addComponent(AddCustStage_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Donate_Add_TextF_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Donate_Add_Label_Amount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Donate_Search_LPane_AddDonateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Donate_Add_TextF_ApprovedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Donate_Add_Label_ApprovedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Donate_Add_Btn_AddDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
            .addGroup(Donate_Search_LPane_AddDonateLayout.createSequentialGroup()
                .addComponent(CustStage_Scp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        Donate_Btn_Back.setBackground(new java.awt.Color(204, 204, 204));
        Donate_Btn_Back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Donate_Btn_Back.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Btn_Back.setText("Back");
        Donate_Btn_Back.setToolTipText("Back");
        Donate_Btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donate_Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Btn_BackActionPerformed(evt);
            }
        });

        Donate_Add_Btn_Ok.setBackground(new java.awt.Color(204, 204, 204));
        Donate_Add_Btn_Ok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Donate_Add_Btn_Ok.setForeground(new java.awt.Color(51, 51, 51));
        Donate_Add_Btn_Ok.setText("Ok");
        Donate_Add_Btn_Ok.setToolTipText("Ok");
        Donate_Add_Btn_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donate_Add_Btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_Add_Btn_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(948, 948, 948)
                .addComponent(Donate_Btn_Back)
                .addGap(6, 6, 6)
                .addComponent(Donate_Add_Btn_Ok)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Donate_LPane_SearchDonate, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                    .addComponent(Donate_Search_LPane_AddDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Donate_Label_Heading)
                .addGap(482, 482, 482))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Donate_Label_Heading)
                .addGap(11, 11, 11)
                .addComponent(Donate_LPane_SearchDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(Donate_Search_LPane_AddDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Donate_Btn_Back)
                    .addComponent(Donate_Add_Btn_Ok)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CustStage_Search_CmbBox_CustStageIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustStage_Search_CmbBox_CustStageIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustStage_Search_CmbBox_CustStageIDActionPerformed

    private void CustStage_Search_CmbBox_CustStageName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustStage_Search_CmbBox_CustStageName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustStage_Search_CmbBox_CustStageName1ActionPerformed

    private void Donate_Search_Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Search_Btn_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Donate_Search_Btn_SearchActionPerformed

    private void Donate_Search_Btn_ShowAllDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Search_Btn_ShowAllDonateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Donate_Search_Btn_ShowAllDonateActionPerformed

    private void Donate_Add_TextF_ApprovedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Add_TextF_ApprovedByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Donate_Add_TextF_ApprovedByActionPerformed

    private void Donate_Add_TextF_AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Add_TextF_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Donate_Add_TextF_AmountActionPerformed

    private void Donate_Add_TextF_DonateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Add_TextF_DonateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Donate_Add_TextF_DonateIDActionPerformed

    private void Donate_Add_Btn_RemoveAddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Add_Btn_RemoveAddedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Donate_Add_Btn_RemoveAddedActionPerformed

    private void AEmpPos_AdEdRe_Btn_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEmpPos_AdEdRe_Btn_DoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AEmpPos_AdEdRe_Btn_DoneActionPerformed

    private void Donate_Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Btn_BackActionPerformed
        // TODSup_Label_Headingcode here:
    }//GEN-LAST:event_Donate_Btn_BackActionPerformed

    private void Donate_Add_Btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_Add_Btn_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Donate_Add_Btn_OkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AEmpPos_AdEdRe_Btn_Done;
    private javax.swing.JScrollPane AddCustStage_Scp_2;
    private javax.swing.JScrollPane AddCustStage_Scp_3;
    private javax.swing.JScrollPane CustStage_Scp_1;
    private javax.swing.JScrollPane CustStage_Scp_3;
    private javax.swing.JComboBox<String> CustStage_Search_CmbBox_CustStageID;
    private javax.swing.JComboBox<String> CustStage_Search_CmbBox_CustStageName1;
    private javax.swing.JLabel DispItem_AddDisp_Label_Reson3;
    private javax.swing.JButton Donate_Add_Btn_AddDonate;
    private javax.swing.JButton Donate_Add_Btn_Ok;
    private javax.swing.JButton Donate_Add_Btn_RemoveAdded;
    private javax.swing.JLabel Donate_Add_Label_Amount;
    private javax.swing.JLabel Donate_Add_Label_ApprovedBy;
    private javax.swing.JLabel Donate_Add_Label_Discription;
    private javax.swing.JLabel Donate_Add_Label_DonateID;
    private javax.swing.JTable Donate_Add_Table_Donate;
    private javax.swing.JTextArea Donate_Add_TextA_Dicription;
    private javax.swing.JTextField Donate_Add_TextF_Amount;
    private javax.swing.JTextField Donate_Add_TextF_ApprovedBy;
    private javax.swing.JTextField Donate_Add_TextF_DonateID;
    private javax.swing.JButton Donate_Btn_Back;
    private javax.swing.JLayeredPane Donate_LPane_SearchDonate;
    private javax.swing.JLabel Donate_Label_Heading;
    private javax.swing.JButton Donate_Search_Btn_Search;
    private javax.swing.JButton Donate_Search_Btn_ShowAllDonate;
    private javax.swing.JLayeredPane Donate_Search_LPane_AddDonate;
    private javax.swing.JLabel Donate_Search_Label_Date;
    private javax.swing.JLabel Donate_Search_Label_Discription;
    private javax.swing.JLabel Donate_Search_Label_DonateID;
    private javax.swing.JTable Donate_Search_Table_Doante;
    private javax.swing.JTextArea Donate_Search_TextA_Discription;
    // End of variables declaration//GEN-END:variables
}
