/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


public class EmpAttend extends javax.swing.JPanel {

    /**
     * Creates new form EmpAttend
     */
    public EmpAttend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmpAttend_Label_Heading = new javax.swing.JLabel();
        EmpAttend_Label_Date = new javax.swing.JLabel();
        EmpAttend_Label_EmpID = new javax.swing.JLabel();
        EmpAttend_CmbBox_EmpID = new javax.swing.JComboBox<>();
        EmpAttend_CmbBox_Date = new javax.swing.JComboBox<>();
        EmpAttend_Btn_Search = new javax.swing.JButton();
        EmpAttend_Btn_ShowAllEmp = new javax.swing.JButton();
        Emp_Scp_2 = new javax.swing.JScrollPane();
        EmpAttend_Table_Emp = new javax.swing.JTable();
        EmpAttend_Btn_Back = new javax.swing.JButton();
        EmpAttend_Btn_Ok = new javax.swing.JButton();
        Emp_Scp_3 = new javax.swing.JScrollPane();
        EmpAttend_Table_EmpAttend = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        EmpAttend_Label_Heading.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        EmpAttend_Label_Heading.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Label_Heading.setText("Employee Atendents");

        EmpAttend_Label_Date.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        EmpAttend_Label_Date.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Label_Date.setText("Date : ");

        EmpAttend_Label_EmpID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        EmpAttend_Label_EmpID.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Label_EmpID.setText("Employee ID : ");

        EmpAttend_CmbBox_EmpID.setEditable(true);
        EmpAttend_CmbBox_EmpID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        EmpAttend_CmbBox_EmpID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        EmpAttend_CmbBox_EmpID.setToolTipText("Employee ID");
        EmpAttend_CmbBox_EmpID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_CmbBox_EmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAttend_CmbBox_EmpIDActionPerformed(evt);
            }
        });

        EmpAttend_CmbBox_Date.setEditable(true);
        EmpAttend_CmbBox_Date.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        EmpAttend_CmbBox_Date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        EmpAttend_CmbBox_Date.setToolTipText("Date");
        EmpAttend_CmbBox_Date.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_CmbBox_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAttend_CmbBox_DateActionPerformed(evt);
            }
        });

        EmpAttend_Btn_Search.setBackground(new java.awt.Color(204, 204, 204));
        EmpAttend_Btn_Search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EmpAttend_Btn_Search.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/search (2).png"))); // NOI18N
        EmpAttend_Btn_Search.setText("Search");
        EmpAttend_Btn_Search.setToolTipText("Search");
        EmpAttend_Btn_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAttend_Btn_SearchActionPerformed(evt);
            }
        });

        EmpAttend_Btn_ShowAllEmp.setBackground(new java.awt.Color(204, 204, 204));
        EmpAttend_Btn_ShowAllEmp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EmpAttend_Btn_ShowAllEmp.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Btn_ShowAllEmp.setText("Show All Employees");
        EmpAttend_Btn_ShowAllEmp.setToolTipText("Show All Employees");
        EmpAttend_Btn_ShowAllEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_Btn_ShowAllEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAttend_Btn_ShowAllEmpActionPerformed(evt);
            }
        });

        EmpAttend_Table_Emp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        EmpAttend_Table_Emp.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Table_Emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmpAttend_Table_Emp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_Table_Emp.setGridColor(new java.awt.Color(102, 102, 102));
        EmpAttend_Table_Emp.setIntercellSpacing(new java.awt.Dimension(1, 0));
        EmpAttend_Table_Emp.setRowHeight(17);
        EmpAttend_Table_Emp.setSelectionBackground(new java.awt.Color(46, 141, 216));
        EmpAttend_Table_Emp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Emp_Scp_2.setViewportView(EmpAttend_Table_Emp);

        EmpAttend_Btn_Back.setBackground(new java.awt.Color(204, 204, 204));
        EmpAttend_Btn_Back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EmpAttend_Btn_Back.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Btn_Back.setText("Back");
        EmpAttend_Btn_Back.setToolTipText("Back");
        EmpAttend_Btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAttend_Btn_BackActionPerformed(evt);
            }
        });

        EmpAttend_Btn_Ok.setBackground(new java.awt.Color(204, 204, 204));
        EmpAttend_Btn_Ok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EmpAttend_Btn_Ok.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Btn_Ok.setText("Ok");
        EmpAttend_Btn_Ok.setToolTipText("Ok");
        EmpAttend_Btn_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_Btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAttend_Btn_OkActionPerformed(evt);
            }
        });

        EmpAttend_Table_EmpAttend.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        EmpAttend_Table_EmpAttend.setForeground(new java.awt.Color(51, 51, 51));
        EmpAttend_Table_EmpAttend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Start Time", "End Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmpAttend_Table_EmpAttend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpAttend_Table_EmpAttend.setGridColor(new java.awt.Color(102, 102, 102));
        EmpAttend_Table_EmpAttend.setIntercellSpacing(new java.awt.Dimension(1, 0));
        EmpAttend_Table_EmpAttend.setRowHeight(17);
        EmpAttend_Table_EmpAttend.setSelectionBackground(new java.awt.Color(46, 141, 216));
        EmpAttend_Table_EmpAttend.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Emp_Scp_3.setViewportView(EmpAttend_Table_EmpAttend);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(EmpAttend_Label_EmpID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpAttend_CmbBox_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmpAttend_Label_Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpAttend_CmbBox_Date, 0, 102, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(EmpAttend_Btn_Search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpAttend_Btn_ShowAllEmp)
                .addGap(347, 347, 347))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EmpAttend_Label_Heading)
                        .addGap(422, 422, 422))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EmpAttend_Btn_Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmpAttend_Btn_Ok)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Emp_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Emp_Scp_3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(EmpAttend_Label_Heading)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpAttend_Label_EmpID)
                    .addComponent(EmpAttend_CmbBox_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpAttend_Label_Date)
                    .addComponent(EmpAttend_CmbBox_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpAttend_Btn_Search)
                    .addComponent(EmpAttend_Btn_ShowAllEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Emp_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emp_Scp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpAttend_Btn_Back)
                    .addComponent(EmpAttend_Btn_Ok))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmpAttend_CmbBox_EmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAttend_CmbBox_EmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpAttend_CmbBox_EmpIDActionPerformed

    private void EmpAttend_CmbBox_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAttend_CmbBox_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpAttend_CmbBox_DateActionPerformed

    private void EmpAttend_Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAttend_Btn_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpAttend_Btn_SearchActionPerformed

    private void EmpAttend_Btn_ShowAllEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAttend_Btn_ShowAllEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpAttend_Btn_ShowAllEmpActionPerformed

    private void EmpAttend_Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAttend_Btn_BackActionPerformed
        // TODSup_Label_Headingcode here:
    }//GEN-LAST:event_EmpAttend_Btn_BackActionPerformed

    private void EmpAttend_Btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAttend_Btn_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpAttend_Btn_OkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmpAttend_Btn_Back;
    private javax.swing.JButton EmpAttend_Btn_Ok;
    private javax.swing.JButton EmpAttend_Btn_Search;
    private javax.swing.JButton EmpAttend_Btn_ShowAllEmp;
    private javax.swing.JComboBox<String> EmpAttend_CmbBox_Date;
    private javax.swing.JComboBox<String> EmpAttend_CmbBox_EmpID;
    private javax.swing.JLabel EmpAttend_Label_Date;
    private javax.swing.JLabel EmpAttend_Label_EmpID;
    private javax.swing.JLabel EmpAttend_Label_Heading;
    private javax.swing.JTable EmpAttend_Table_Emp;
    private javax.swing.JTable EmpAttend_Table_EmpAttend;
    private javax.swing.JScrollPane Emp_Scp_2;
    private javax.swing.JScrollPane Emp_Scp_3;
    // End of variables declaration//GEN-END:variables
}
