/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


public class GRNR extends javax.swing.JPanel {

    /**
     * Creates new form GRNR
     */
    public GRNR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRNR_Label_Heading = new javax.swing.JLabel();
        GRNR_Label_PostMNo = new javax.swing.JLabel();
        GRNR_TextF_GRNNo = new javax.swing.JTextField();
        GRNR_CmbBox_ItemID = new javax.swing.JComboBox<>();
        GRNR_TextF_Date = new javax.swing.JTextField();
        GRNR_Label_ItemName = new javax.swing.JLabel();
        GRNR_Label_GRNRDate = new javax.swing.JLabel();
        GRNR_CmbBox_ItemName = new javax.swing.JComboBox<>();
        GRNR_Label_Time = new javax.swing.JLabel();
        GRNR_Label_Quant = new javax.swing.JLabel();
        GRNR_TextF_Quant = new javax.swing.JTextField();
        GRNR_Btn_AddItem = new javax.swing.JButton();
        GRNR_TextF_PostMNo = new javax.swing.JTextField();
        GRNR_Label_ItemID = new javax.swing.JLabel();
        GRNR_CmbBox_SupID = new javax.swing.JComboBox<>();
        GRNR_Label_GRNNo = new javax.swing.JLabel();
        GRN_Sep = new javax.swing.JSeparator();
        GRNR_Btn_RemoveItem = new javax.swing.JButton();
        GRNR_Label_SupID = new javax.swing.JLabel();
        GRNR_Label_OldGRNNo = new javax.swing.JLabel();
        GRNR_TextF_Time = new javax.swing.JTextField();
        GRNR_TextF_OldGRNNo = new javax.swing.JTextField();
        GRNR_Label_EmpID = new javax.swing.JLabel();
        GRNR_TextF_EmpID = new javax.swing.JTextField();
        GRNR_Label_Reson = new javax.swing.JLabel();
        AddCustStage_Scp_2 = new javax.swing.JScrollPane();
        GRNR_TextA_Reson = new javax.swing.JTextArea();
        CustStage_Scp_1 = new javax.swing.JScrollPane();
        GRNR_Table_Item = new javax.swing.JTable();
        GRNR_Label_Total = new javax.swing.JLabel();
        GRNR_TextF_Total = new javax.swing.JTextField();
        GRNR_Btn_Done = new javax.swing.JButton();
        GRNR_Btn_Back = new javax.swing.JButton();
        GRNR_Btn_Ok = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        GRNR_Label_Heading.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        GRNR_Label_Heading.setForeground(new java.awt.Color(179, 14, 34));
        GRNR_Label_Heading.setText("GRN Return");

        GRNR_Label_PostMNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_PostMNo.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_PostMNo.setText("Post Machine No : ");

        GRNR_TextF_GRNNo.setEditable(false);
        GRNR_TextF_GRNNo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextF_GRNNo.setToolTipText("GRNR Number");
        GRNR_TextF_GRNNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_GRNNoActionPerformed(evt);
            }
        });

        GRNR_CmbBox_ItemID.setEditable(true);
        GRNR_CmbBox_ItemID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_CmbBox_ItemID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        GRNR_CmbBox_ItemID.setToolTipText("Item ID");
        GRNR_CmbBox_ItemID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRNR_CmbBox_ItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_CmbBox_ItemIDActionPerformed(evt);
            }
        });

        GRNR_TextF_Date.setEditable(false);
        GRNR_TextF_Date.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextF_Date.setToolTipText("GRNR Date");
        GRNR_TextF_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_DateActionPerformed(evt);
            }
        });

        GRNR_Label_ItemName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_ItemName.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_ItemName.setText("Item Name : ");

        GRNR_Label_GRNRDate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_GRNRDate.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_GRNRDate.setText("Date : ");

        GRNR_CmbBox_ItemName.setEditable(true);
        GRNR_CmbBox_ItemName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_CmbBox_ItemName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        GRNR_CmbBox_ItemName.setToolTipText("Item Name");
        GRNR_CmbBox_ItemName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRNR_CmbBox_ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_CmbBox_ItemNameActionPerformed(evt);
            }
        });

        GRNR_Label_Time.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_Time.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_Time.setText("Time : ");

        GRNR_Label_Quant.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_Quant.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_Quant.setText("Quantity : ");

        GRNR_TextF_Quant.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextF_Quant.setToolTipText("Quantity");
        GRNR_TextF_Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_QuantActionPerformed(evt);
            }
        });

        GRNR_Btn_AddItem.setBackground(new java.awt.Color(204, 204, 204));
        GRNR_Btn_AddItem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Btn_AddItem.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Btn_AddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Add_plus.png"))); // NOI18N
        GRNR_Btn_AddItem.setText("Add");
        GRNR_Btn_AddItem.setToolTipText("Add Item");
        GRNR_Btn_AddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRNR_Btn_AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_Btn_AddItemActionPerformed(evt);
            }
        });

        GRNR_TextF_PostMNo.setEditable(false);
        GRNR_TextF_PostMNo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextF_PostMNo.setToolTipText("Post Machine No");
        GRNR_TextF_PostMNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_PostMNoActionPerformed(evt);
            }
        });

        GRNR_Label_ItemID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_ItemID.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_ItemID.setText("Item ID : ");

        GRNR_CmbBox_SupID.setEditable(true);
        GRNR_CmbBox_SupID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_CmbBox_SupID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        GRNR_CmbBox_SupID.setToolTipText("Suplier ID");
        GRNR_CmbBox_SupID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        GRNR_Label_GRNNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_GRNNo.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_GRNNo.setText("GRNR No : ");

        GRN_Sep.setBackground(new java.awt.Color(204, 204, 204));
        GRN_Sep.setForeground(new java.awt.Color(153, 153, 153));

        GRNR_Btn_RemoveItem.setBackground(new java.awt.Color(204, 204, 204));
        GRNR_Btn_RemoveItem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Btn_RemoveItem.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Btn_RemoveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/trash_bin.png"))); // NOI18N
        GRNR_Btn_RemoveItem.setText("Remove");
        GRNR_Btn_RemoveItem.setToolTipText("Remove Added Item");
        GRNR_Btn_RemoveItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRNR_Btn_RemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_Btn_RemoveItemActionPerformed(evt);
            }
        });

        GRNR_Label_SupID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_SupID.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_SupID.setText("Suplier ID : ");

        GRNR_Label_OldGRNNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_OldGRNNo.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_OldGRNNo.setText("Old GRN No : ");

        GRNR_TextF_Time.setEditable(false);
        GRNR_TextF_Time.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextF_Time.setToolTipText("GRNR Time");
        GRNR_TextF_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_TimeActionPerformed(evt);
            }
        });

        GRNR_TextF_OldGRNNo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextF_OldGRNNo.setToolTipText("Old GRN No");
        GRNR_TextF_OldGRNNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_OldGRNNoActionPerformed(evt);
            }
        });

        GRNR_Label_EmpID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_EmpID.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_EmpID.setText("Employee ID : ");

        GRNR_TextF_EmpID.setEditable(false);
        GRNR_TextF_EmpID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextF_EmpID.setToolTipText("Employee ID");
        GRNR_TextF_EmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_EmpIDActionPerformed(evt);
            }
        });

        GRNR_Label_Reson.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Label_Reson.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Label_Reson.setText("Reson : ");

        AddCustStage_Scp_2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AddCustStage_Scp_2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        GRNR_TextA_Reson.setColumns(20);
        GRNR_TextA_Reson.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_TextA_Reson.setLineWrap(true);
        GRNR_TextA_Reson.setRows(5);
        GRNR_TextA_Reson.setToolTipText("Reson for Return this Item");
        GRNR_TextA_Reson.setWrapStyleWord(true);
        AddCustStage_Scp_2.setViewportView(GRNR_TextA_Reson);

        CustStage_Scp_1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        GRNR_Table_Item.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        GRNR_Table_Item.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Table_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Reson", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GRNR_Table_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRNR_Table_Item.setGridColor(new java.awt.Color(102, 102, 102));
        GRNR_Table_Item.setIntercellSpacing(new java.awt.Dimension(1, 0));
        GRNR_Table_Item.setRowHeight(17);
        GRNR_Table_Item.setSelectionBackground(new java.awt.Color(46, 141, 216));
        GRNR_Table_Item.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_1.setViewportView(GRNR_Table_Item);

        GRNR_Label_Total.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        GRNR_Label_Total.setForeground(new java.awt.Color(102, 102, 102));
        GRNR_Label_Total.setText("Total : ");

        GRNR_TextF_Total.setEditable(false);
        GRNR_TextF_Total.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GRNR_TextF_Total.setToolTipText("Last Total");
        GRNR_TextF_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_TextF_TotalActionPerformed(evt);
            }
        });

        GRNR_Btn_Done.setBackground(new java.awt.Color(204, 204, 204));
        GRNR_Btn_Done.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GRNR_Btn_Done.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Btn_Done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/check.png"))); // NOI18N
        GRNR_Btn_Done.setText("Done");
        GRNR_Btn_Done.setToolTipText("Done");
        GRNR_Btn_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        GRNR_Btn_Back.setBackground(new java.awt.Color(204, 204, 204));
        GRNR_Btn_Back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GRNR_Btn_Back.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Btn_Back.setText("Back");
        GRNR_Btn_Back.setToolTipText("Back");
        GRNR_Btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRNR_Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_Btn_BackActionPerformed(evt);
            }
        });

        GRNR_Btn_Ok.setBackground(new java.awt.Color(204, 204, 204));
        GRNR_Btn_Ok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GRNR_Btn_Ok.setForeground(new java.awt.Color(51, 51, 51));
        GRNR_Btn_Ok.setText("Ok");
        GRNR_Btn_Ok.setToolTipText("Ok");
        GRNR_Btn_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRNR_Btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNR_Btn_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(472, 472, 472)
                                .addComponent(GRNR_Label_Heading))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GRNR_Label_GRNRDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GRNR_TextF_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GRNR_Label_GRNNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GRNR_TextF_GRNNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GRNR_Label_Time)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GRNR_TextF_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(GRNR_Label_SupID)
                                    .addComponent(GRNR_Label_OldGRNNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GRNR_TextF_OldGRNNo)
                                    .addComponent(GRNR_CmbBox_SupID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(GRNR_Label_EmpID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GRNR_TextF_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(GRNR_Label_PostMNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GRNR_TextF_PostMNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(GRN_Sep)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GRNR_Label_ItemID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GRNR_Label_Reson, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AddCustStage_Scp_2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GRNR_CmbBox_ItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GRNR_Label_ItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GRNR_CmbBox_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GRNR_Label_Quant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GRNR_TextF_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GRNR_Btn_AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GRNR_Btn_RemoveItem)))
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GRNR_Label_Total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GRNR_Btn_Done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GRNR_TextF_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GRNR_Btn_Back)
                        .addGap(6, 6, 6)
                        .addComponent(GRNR_Btn_Ok)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GRNR_Label_Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GRNR_Label_GRNNo)
                        .addComponent(GRNR_TextF_GRNNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GRNR_Label_EmpID)
                        .addComponent(GRNR_TextF_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GRNR_TextF_OldGRNNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GRNR_Label_OldGRNNo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(GRNR_TextF_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(GRNR_Label_GRNRDate))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(GRNR_Label_SupID)
                                .addComponent(GRNR_CmbBox_SupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GRNR_TextF_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GRNR_Label_Time)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GRNR_Label_PostMNo)
                            .addComponent(GRNR_TextF_PostMNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGap(11, 11, 11)
                .addComponent(GRN_Sep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GRNR_Label_ItemID)
                    .addComponent(GRNR_CmbBox_ItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRNR_Label_ItemName)
                    .addComponent(GRNR_CmbBox_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRNR_Label_Quant)
                    .addComponent(GRNR_TextF_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRNR_Btn_AddItem)
                    .addComponent(GRNR_Btn_RemoveItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddCustStage_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRNR_Label_Reson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GRNR_Label_Total)
                    .addComponent(GRNR_TextF_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRNR_Btn_Done, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GRNR_Btn_Back)
                    .addComponent(GRNR_Btn_Ok))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GRNR_TextF_GRNNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_GRNNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_GRNNoActionPerformed

    private void GRNR_CmbBox_ItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_CmbBox_ItemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_CmbBox_ItemIDActionPerformed

    private void GRNR_TextF_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_DateActionPerformed

    private void GRNR_CmbBox_ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_CmbBox_ItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_CmbBox_ItemNameActionPerformed

    private void GRNR_TextF_QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_QuantActionPerformed

    private void GRNR_Btn_AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_Btn_AddItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_Btn_AddItemActionPerformed

    private void GRNR_TextF_PostMNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_PostMNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_PostMNoActionPerformed

    private void GRNR_Btn_RemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_Btn_RemoveItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_Btn_RemoveItemActionPerformed

    private void GRNR_TextF_TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_TimeActionPerformed

    private void GRNR_TextF_OldGRNNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_OldGRNNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_OldGRNNoActionPerformed

    private void GRNR_TextF_EmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_EmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_EmpIDActionPerformed

    private void GRNR_TextF_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_TextF_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_TextF_TotalActionPerformed

    private void GRNR_Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_Btn_BackActionPerformed
        // TODSup_Label_Headingcode here:
    }//GEN-LAST:event_GRNR_Btn_BackActionPerformed

    private void GRNR_Btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNR_Btn_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNR_Btn_OkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AddCustStage_Scp_2;
    private javax.swing.JScrollPane CustStage_Scp_1;
    private javax.swing.JButton GRNR_Btn_AddItem;
    private javax.swing.JButton GRNR_Btn_Back;
    private javax.swing.JButton GRNR_Btn_Done;
    private javax.swing.JButton GRNR_Btn_Ok;
    private javax.swing.JButton GRNR_Btn_RemoveItem;
    private javax.swing.JComboBox<String> GRNR_CmbBox_ItemID;
    private javax.swing.JComboBox<String> GRNR_CmbBox_ItemName;
    private javax.swing.JComboBox<String> GRNR_CmbBox_SupID;
    private javax.swing.JLabel GRNR_Label_EmpID;
    private javax.swing.JLabel GRNR_Label_GRNNo;
    private javax.swing.JLabel GRNR_Label_GRNRDate;
    private javax.swing.JLabel GRNR_Label_Heading;
    private javax.swing.JLabel GRNR_Label_ItemID;
    private javax.swing.JLabel GRNR_Label_ItemName;
    private javax.swing.JLabel GRNR_Label_OldGRNNo;
    private javax.swing.JLabel GRNR_Label_PostMNo;
    private javax.swing.JLabel GRNR_Label_Quant;
    private javax.swing.JLabel GRNR_Label_Reson;
    private javax.swing.JLabel GRNR_Label_SupID;
    private javax.swing.JLabel GRNR_Label_Time;
    private javax.swing.JLabel GRNR_Label_Total;
    private javax.swing.JTable GRNR_Table_Item;
    private javax.swing.JTextArea GRNR_TextA_Reson;
    private javax.swing.JTextField GRNR_TextF_Date;
    private javax.swing.JTextField GRNR_TextF_EmpID;
    private javax.swing.JTextField GRNR_TextF_GRNNo;
    private javax.swing.JTextField GRNR_TextF_OldGRNNo;
    private javax.swing.JTextField GRNR_TextF_PostMNo;
    private javax.swing.JTextField GRNR_TextF_Quant;
    private javax.swing.JTextField GRNR_TextF_Time;
    private javax.swing.JTextField GRNR_TextF_Total;
    private javax.swing.JSeparator GRN_Sep;
    // End of variables declaration//GEN-END:variables
}
