/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.Login.EmpID;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Invoice extends javax.swing.JPanel {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
        doFirst();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IN_Label_Heading = new javax.swing.JLabel();
        CustStage_Scp_1 = new javax.swing.JScrollPane();
        IN_Table_Item = new javax.swing.JTable();
        IN_Label_INNo = new javax.swing.JLabel();
        IN_TextF_INNo = new javax.swing.JTextField();
        IN_TextF_Date = new javax.swing.JTextField();
        IN_Label_INDate = new javax.swing.JLabel();
        IN_CBox_RegCust = new javax.swing.JCheckBox();
        IN_Label_CustID = new javax.swing.JLabel();
        IN_Label_Discount = new javax.swing.JLabel();
        IN_TextF_Discount = new javax.swing.JTextField();
        IN_Label_EmpID = new javax.swing.JLabel();
        IN_TextF_EmpID = new javax.swing.JTextField();
        IN_Label_PostMNo = new javax.swing.JLabel();
        IN_TextF_PostMNo = new javax.swing.JTextField();
        IN_Label_ItemID = new javax.swing.JLabel();
        IN_Sep = new javax.swing.JSeparator();
        IN_Label_ItemName = new javax.swing.JLabel();
        IN_Label_Quant = new javax.swing.JLabel();
        IN_TextF_Quant = new javax.swing.JTextField();
        IN_Btn_AddItem = new javax.swing.JButton();
        IN_Btn_RemoveItem = new javax.swing.JButton();
        IN_Label_LastDiscount = new javax.swing.JLabel();
        IN_TextF_LastDiscount = new javax.swing.JTextField();
        IN_Label_Total = new javax.swing.JLabel();
        IN_TextF_LastTotal = new javax.swing.JTextField();
        IN_Btn_Back = new javax.swing.JButton();
        IN_Btn_Ok = new javax.swing.JButton();
        IN_Btn_Done = new javax.swing.JButton();
        IN_TextF_ItemID = new javax.swing.JTextField();
        IN_TextF_ItemName = new javax.swing.JTextField();
        IN_TextF_CustID = new javax.swing.JTextField();
        IN_TextF_CustName = new javax.swing.JTextField();
        IN_Label_Disc = new javax.swing.JLabel();
        IN_TextF_Disc = new javax.swing.JTextField();
        IN_Label_LastDiscount1 = new javax.swing.JLabel();
        IN_TextF_Total = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        IN_Label_Heading.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        IN_Label_Heading.setForeground(new java.awt.Color(44, 149, 40));
        IN_Label_Heading.setText("Invoice");

        CustStage_Scp_1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        IN_Table_Item.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_Table_Item.setForeground(new java.awt.Color(51, 51, 51));
        IN_Table_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Sell Price", "Price", "Discount", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        IN_Table_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN_Table_Item.setGridColor(new java.awt.Color(102, 102, 102));
        IN_Table_Item.setIntercellSpacing(new java.awt.Dimension(1, 0));
        IN_Table_Item.setRowHeight(17);
        IN_Table_Item.setSelectionBackground(new java.awt.Color(46, 141, 216));
        IN_Table_Item.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_1.setViewportView(IN_Table_Item);

        IN_Label_INNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_INNo.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_INNo.setText("Invoice No : ");

        IN_TextF_INNo.setEditable(false);
        IN_TextF_INNo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_INNo.setToolTipText("Invoice Number");

        IN_TextF_Date.setEditable(false);
        IN_TextF_Date.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_Date.setToolTipText("Invoice Date");

        IN_Label_INDate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_INDate.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_INDate.setText("Date : ");

        IN_CBox_RegCust.setBackground(new java.awt.Color(204, 204, 204));
        IN_CBox_RegCust.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_CBox_RegCust.setText("Registerd Customer");
        IN_CBox_RegCust.setToolTipText("Check the Customer Registerd or Non-Registerd");
        IN_CBox_RegCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IN_CBox_RegCustMouseClicked(evt);
            }
        });

        IN_Label_CustID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_CustID.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_CustID.setText("Customer ID : ");

        IN_Label_Discount.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_Discount.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_Discount.setText("Discount (%) : ");

        IN_TextF_Discount.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_Discount.setToolTipText("Discount for Customer");

        IN_Label_EmpID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_EmpID.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_EmpID.setText("Employee ID : ");

        IN_TextF_EmpID.setEditable(false);
        IN_TextF_EmpID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_EmpID.setToolTipText("Employee ID");

        IN_Label_PostMNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_PostMNo.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_PostMNo.setText("Post Machine No : ");

        IN_TextF_PostMNo.setEditable(false);
        IN_TextF_PostMNo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_PostMNo.setToolTipText("Post Machine No");

        IN_Label_ItemID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_ItemID.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_ItemID.setText("Item ID : ");

        IN_Sep.setBackground(new java.awt.Color(204, 204, 204));
        IN_Sep.setForeground(new java.awt.Color(153, 153, 153));

        IN_Label_ItemName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_ItemName.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_ItemName.setText("Item Name : ");

        IN_Label_Quant.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_Quant.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_Quant.setText("Quantity : ");

        IN_TextF_Quant.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_Quant.setToolTipText("Quantity");
        IN_TextF_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IN_TextF_QuantKeyTyped(evt);
            }
        });

        IN_Btn_AddItem.setBackground(new java.awt.Color(204, 204, 204));
        IN_Btn_AddItem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Btn_AddItem.setForeground(new java.awt.Color(51, 51, 51));
        IN_Btn_AddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Add_plus.png"))); // NOI18N
        IN_Btn_AddItem.setText("Add");
        IN_Btn_AddItem.setToolTipText("Add Item");
        IN_Btn_AddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN_Btn_AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IN_Btn_AddItemActionPerformed(evt);
            }
        });

        IN_Btn_RemoveItem.setBackground(new java.awt.Color(204, 204, 204));
        IN_Btn_RemoveItem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Btn_RemoveItem.setForeground(new java.awt.Color(51, 51, 51));
        IN_Btn_RemoveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/trash_bin.png"))); // NOI18N
        IN_Btn_RemoveItem.setText("Remove");
        IN_Btn_RemoveItem.setToolTipText("Remove Added Item");
        IN_Btn_RemoveItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN_Btn_RemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IN_Btn_RemoveItemActionPerformed(evt);
            }
        });

        IN_Label_LastDiscount.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        IN_Label_LastDiscount.setForeground(new java.awt.Color(102, 102, 102));
        IN_Label_LastDiscount.setText("Discount : ");

        IN_TextF_LastDiscount.setEditable(false);
        IN_TextF_LastDiscount.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        IN_TextF_LastDiscount.setToolTipText("Last Discount Amount");

        IN_Label_Total.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        IN_Label_Total.setForeground(new java.awt.Color(102, 102, 102));
        IN_Label_Total.setText("Last Total : ");

        IN_TextF_LastTotal.setEditable(false);
        IN_TextF_LastTotal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        IN_TextF_LastTotal.setToolTipText("Last Total");

        IN_Btn_Back.setBackground(new java.awt.Color(204, 204, 204));
        IN_Btn_Back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        IN_Btn_Back.setForeground(new java.awt.Color(51, 51, 51));
        IN_Btn_Back.setText("Back");
        IN_Btn_Back.setToolTipText("Back");
        IN_Btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN_Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IN_Btn_BackActionPerformed(evt);
            }
        });

        IN_Btn_Ok.setBackground(new java.awt.Color(204, 204, 204));
        IN_Btn_Ok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        IN_Btn_Ok.setForeground(new java.awt.Color(51, 51, 51));
        IN_Btn_Ok.setText("Ok");
        IN_Btn_Ok.setToolTipText("Ok");
        IN_Btn_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN_Btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IN_Btn_OkActionPerformed(evt);
            }
        });

        IN_Btn_Done.setBackground(new java.awt.Color(204, 204, 204));
        IN_Btn_Done.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Btn_Done.setForeground(new java.awt.Color(51, 51, 51));
        IN_Btn_Done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/check.png"))); // NOI18N
        IN_Btn_Done.setText("Done");
        IN_Btn_Done.setToolTipText("Done");
        IN_Btn_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        IN_TextF_ItemID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_ItemID.setToolTipText("Invoice Number");
        IN_TextF_ItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IN_TextF_ItemIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IN_TextF_ItemIDKeyTyped(evt);
            }
        });

        IN_TextF_ItemName.setEditable(false);
        IN_TextF_ItemName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_ItemName.setToolTipText("Invoice Number");

        IN_TextF_CustID.setEditable(false);
        IN_TextF_CustID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_CustID.setToolTipText("Customer ID");
        IN_TextF_CustID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IN_TextF_CustIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IN_TextF_CustIDKeyTyped(evt);
            }
        });

        IN_TextF_CustName.setEditable(false);
        IN_TextF_CustName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_CustName.setToolTipText("Customer Name");

        IN_Label_Disc.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        IN_Label_Disc.setForeground(new java.awt.Color(51, 51, 51));
        IN_Label_Disc.setText("Discount (%) : ");

        IN_TextF_Disc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        IN_TextF_Disc.setToolTipText("Quantity");
        IN_TextF_Disc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IN_TextF_DiscKeyTyped(evt);
            }
        });

        IN_Label_LastDiscount1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        IN_Label_LastDiscount1.setForeground(new java.awt.Color(102, 102, 102));
        IN_Label_LastDiscount1.setText("Total : ");

        IN_TextF_Total.setEditable(false);
        IN_TextF_Total.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        IN_TextF_Total.setToolTipText("Last Discount Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(IN_Label_INNo)
                                .addGap(4, 4, 4)
                                .addComponent(IN_TextF_INNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233)
                                .addComponent(IN_CBox_RegCust, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IN_Label_EmpID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IN_TextF_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(IN_Label_INDate)
                                .addGap(4, 4, 4)
                                .addComponent(IN_TextF_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(IN_Label_CustID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IN_Label_Discount)
                                        .addGap(4, 4, 4)
                                        .addComponent(IN_TextF_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(IN_TextF_CustID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(IN_TextF_CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85)
                                                .addComponent(IN_Label_PostMNo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(IN_Label_Heading)))
                                        .addGap(4, 4, 4)
                                        .addComponent(IN_TextF_PostMNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(IN_Btn_Back)
                                    .addGap(6, 6, 6)
                                    .addComponent(IN_Btn_Ok)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(IN_Label_LastDiscount)
                                            .addGap(4, 4, 4)
                                            .addComponent(IN_TextF_LastDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(87, 87, 87)
                                            .addComponent(IN_Btn_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(IN_Label_ItemID)
                                    .addGap(4, 4, 4)
                                    .addComponent(IN_TextF_ItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(IN_Label_ItemName)
                                    .addGap(4, 4, 4)
                                    .addComponent(IN_TextF_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(IN_Label_Quant)
                                    .addGap(4, 4, 4)
                                    .addComponent(IN_TextF_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(IN_Label_Disc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IN_TextF_Disc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(IN_Btn_AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(IN_Btn_RemoveItem))
                                .addComponent(IN_Sep, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(764, 764, 764)
                                    .addComponent(IN_Label_Total)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IN_TextF_LastTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IN_Label_LastDiscount1)
                        .addGap(4, 4, 4)
                        .addComponent(IN_TextF_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(IN_Label_Heading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(IN_Label_INNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(IN_TextF_INNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IN_CBox_RegCust)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IN_TextF_EmpID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IN_Label_EmpID))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(IN_Label_INDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(IN_TextF_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IN_TextF_CustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IN_TextF_CustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IN_Label_CustID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(IN_Label_PostMNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(IN_TextF_PostMNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IN_TextF_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(IN_Label_Discount)))
                .addGap(12, 12, 12)
                .addComponent(IN_Sep, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IN_Btn_AddItem)
                    .addComponent(IN_Btn_RemoveItem)
                    .addComponent(IN_TextF_ItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IN_TextF_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IN_TextF_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IN_Label_Disc)
                        .addComponent(IN_TextF_Disc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IN_Label_ItemID)
                            .addComponent(IN_Label_ItemName)
                            .addComponent(IN_Label_Quant))))
                .addGap(11, 11, 11)
                .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(IN_Label_LastDiscount1))
                    .addComponent(IN_TextF_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IN_Btn_Back)
                        .addComponent(IN_Btn_Ok))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(IN_Label_LastDiscount))
                            .addComponent(IN_TextF_LastDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(IN_Label_Total))
                            .addComponent(IN_TextF_LastTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(IN_Btn_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private float in = 0;
    private void IN_Btn_AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IN_Btn_AddItemActionPerformed
        if (IN_TextF_ItemID.getText().equals("") || IN_TextF_ItemID.getText() == null) {
            JOptionPane.showMessageDialog(this, "Plese enter a item ID", "Error", 0);
        } else if (IN_TextF_Quant.getText().equals("") || IN_TextF_Quant.getText() == null) {
            JOptionPane.showMessageDialog(this, "Plese enter a quantity", "Error", 0);
        } else {
            try {
                ResultSet resIquant = ConnectDB.ConnectDB.DBConnection().createStatement().executeQuery("SELECT I2_Quant, I2_Sell_Price FROM item_2 WHERE I_ID='" + IN_TextF_ItemID.getText() + "'");
                if (resIquant.next()) {
                    if (Integer.parseInt(resIquant.getString("I2_Quant")) < Integer.parseInt(IN_TextF_Quant.getText())) {
                        JOptionPane.showMessageDialog(this, "Sorry you can't buy than " + resIquant.getString("I2_Quant") + " quantity", "Error", 0);
                        IN_TextF_Quant.grabFocus();
                    } else {
                        DefaultTableModel listInvoice = (DefaultTableModel) IN_Table_Item.getModel();
                        Vector v = new Vector();
                        v.addElement(IN_TextF_ItemID.getText());
                        v.addElement(IN_TextF_ItemName.getText());
                        v.addElement(IN_TextF_Quant.getText());
                        v.addElement(resIquant.getString("I2_Sell_Price"));
                        v.addElement(Integer.parseInt(resIquant.getString("I2_Sell_Price")) * Integer.parseInt(IN_TextF_Quant.getText()));
                        if (!(IN_TextF_Disc.getText().equals("") || IN_TextF_Disc.getText() == null)) {
                            v.addElement((Float.parseFloat(resIquant.getString("I2_Sell_Price")) * Float.parseFloat(IN_TextF_Quant.getText())) * (Float.parseFloat(IN_TextF_Disc.getText()) / 100));
                            v.addElement((Float.parseFloat(resIquant.getString("I2_Sell_Price")) * Float.parseFloat(IN_TextF_Quant.getText())) - ((Float.parseFloat(resIquant.getString("I2_Sell_Price")) * Float.parseFloat(IN_TextF_Quant.getText())) * (Float.parseFloat(IN_TextF_Disc.getText()) / 100)));
                        } else {
                            v.addElement("-------------");
                            v.addElement(Integer.parseInt(resIquant.getString("I2_Sell_Price")) * Integer.parseInt(IN_TextF_Quant.getText()));
                        }
                        listInvoice.addRow(v);

                        for (int i = 0; i < listInvoice.getRowCount(); i++) {
                            in += Float.parseFloat("" + listInvoice.getValueAt(i, 6));
                        }
                        IN_TextF_Total.setText("" + in);
                    }
                }
                IN_Btn_RemoveItem.setEnabled(false);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_IN_Btn_AddItemActionPerformed

    private void IN_Btn_RemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IN_Btn_RemoveItemActionPerformed
        DefaultTableModel AdEdReTblModel = (DefaultTableModel) IN_Table_Item.getModel();
        int[] indexes = IN_Table_Item.getSelectedRows();
        int res = 0;
        for (int i = 0; i < indexes.length; i++) {
            res += (i > 0) ? (indexes[i] - indexes[i - 1] - 1) : 0;
            int index = IN_Table_Item.convertColumnIndexToModel(indexes[0] + res);
            AdEdReTblModel.removeRow(index);
        }
        if (AdEdReTblModel.getRowCount() == 0) {
            IN_Btn_RemoveItem.setEnabled(false);
            IN_TextF_Total.setText("");
            in=0;
        }
        DefaultTableModel listInvoice = (DefaultTableModel) IN_Table_Item.getModel();
        for (int i = 0; i < listInvoice.getRowCount(); i++) {
            in += Float.parseFloat("" + listInvoice.getValueAt(i, 6));
        }
        IN_TextF_Total.setText("" + in);
    }//GEN-LAST:event_IN_Btn_RemoveItemActionPerformed

    private void IN_Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IN_Btn_BackActionPerformed
        // TODSup_Label_Headingcode here:
    }//GEN-LAST:event_IN_Btn_BackActionPerformed

    private void IN_Btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IN_Btn_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IN_Btn_OkActionPerformed

    private void IN_CBox_RegCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IN_CBox_RegCustMouseClicked
        if (IN_CBox_RegCust.isSelected()) {
            IN_TextF_CustID.setEditable(true);
        } else {
            IN_TextF_CustID.setText("");
            IN_TextF_CustName.setText("");
            IN_TextF_Discount.setText("");
            IN_TextF_CustID.setEditable(false);
        }
    }//GEN-LAST:event_IN_CBox_RegCustMouseClicked

    private void IN_TextF_CustIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IN_TextF_CustIDKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_IN_TextF_CustIDKeyTyped

    private void IN_TextF_CustIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IN_TextF_CustIDKeyReleased
        try {
            if (!(IN_TextF_CustID.getText().equals("") || IN_TextF_CustID.getText() == null)) {
                ResultSet resCust = ConnectDB.ConnectDB.DBConnection().createStatement().executeQuery("SELECT Cust_FName, Cust_LName, Cust_Stg_No FROM customer WHERE Cust_ID='" + IN_TextF_CustID.getText() + "'");
                if (resCust.next()) {
                    IN_TextF_CustName.setText(resCust.getString("Cust_FName") + " " + resCust.getString("Cust_LName"));
                    ResultSet resCustStage = ConnectDB.ConnectDB.DBConnection().createStatement().executeQuery("SELECT Cust_Stg_Discount FROM cust_stages WHERE Cust_Stg_ID='" + resCust.getString("Cust_Stg_No") + "'");
                    if (resCustStage.next()) {
                        IN_TextF_Discount.setText(resCustStage.getString("Cust_Stg_Discount"));
                    }
                }
            } else {
                IN_TextF_CustName.setText("");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_IN_TextF_CustIDKeyReleased

    private void IN_TextF_ItemIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IN_TextF_ItemIDKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_IN_TextF_ItemIDKeyTyped

    private void IN_TextF_QuantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IN_TextF_QuantKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_IN_TextF_QuantKeyTyped

    private void IN_TextF_ItemIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IN_TextF_ItemIDKeyReleased
        try {
            if (!(IN_TextF_ItemID.getText().equals("") || IN_TextF_ItemID.getText() == null)) {
                ResultSet resIName = ConnectDB.ConnectDB.DBConnection().createStatement().executeQuery("SELECT I_Name FROM item WHERE I_ID='" + IN_TextF_ItemID.getText() + "'");
                if (resIName.next()) {
                    IN_TextF_ItemName.setText(resIName.getString("I_Name"));
                }
            } else {
                IN_TextF_ItemName.setText("");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_IN_TextF_ItemIDKeyReleased

    private void IN_TextF_DiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IN_TextF_DiscKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_IN_TextF_DiscKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CustStage_Scp_1;
    private javax.swing.JButton IN_Btn_AddItem;
    private javax.swing.JButton IN_Btn_Back;
    private javax.swing.JButton IN_Btn_Done;
    private javax.swing.JButton IN_Btn_Ok;
    private javax.swing.JButton IN_Btn_RemoveItem;
    private javax.swing.JCheckBox IN_CBox_RegCust;
    private javax.swing.JLabel IN_Label_CustID;
    private javax.swing.JLabel IN_Label_Disc;
    private javax.swing.JLabel IN_Label_Discount;
    private javax.swing.JLabel IN_Label_EmpID;
    private javax.swing.JLabel IN_Label_Heading;
    private javax.swing.JLabel IN_Label_INDate;
    private javax.swing.JLabel IN_Label_INNo;
    private javax.swing.JLabel IN_Label_ItemID;
    private javax.swing.JLabel IN_Label_ItemName;
    private javax.swing.JLabel IN_Label_LastDiscount;
    private javax.swing.JLabel IN_Label_LastDiscount1;
    private javax.swing.JLabel IN_Label_PostMNo;
    private javax.swing.JLabel IN_Label_Quant;
    private javax.swing.JLabel IN_Label_Total;
    private javax.swing.JSeparator IN_Sep;
    private javax.swing.JTable IN_Table_Item;
    private javax.swing.JTextField IN_TextF_CustID;
    private javax.swing.JTextField IN_TextF_CustName;
    private javax.swing.JTextField IN_TextF_Date;
    private javax.swing.JTextField IN_TextF_Disc;
    private javax.swing.JTextField IN_TextF_Discount;
    private javax.swing.JTextField IN_TextF_EmpID;
    private javax.swing.JTextField IN_TextF_INNo;
    private javax.swing.JTextField IN_TextF_ItemID;
    private javax.swing.JTextField IN_TextF_ItemName;
    private javax.swing.JTextField IN_TextF_LastDiscount;
    private javax.swing.JTextField IN_TextF_LastTotal;
    private javax.swing.JTextField IN_TextF_PostMNo;
    private javax.swing.JTextField IN_TextF_Quant;
    private javax.swing.JTextField IN_TextF_Total;
    // End of variables declaration//GEN-END:variables

    private void doFirst() {
        try {
            ResultSet resInNo = ConnectDB.ConnectDB.DBConnection().createStatement().executeQuery("SELECT IN_No FROM invoice");
            if (!resInNo.next()) {
                IN_TextF_INNo.setText("1");
            } else {
                resInNo.last();
                int INNO = Integer.parseInt(resInNo.getString("IN_No"));
                IN_TextF_INNo.setText(++INNO + "");
            }
            SimpleDateFormat dateFormatter = new SimpleDateFormat("dd MMM yyyy");
            IN_TextF_Date.setText(dateFormatter.format(Calendar.getInstance().getTime()));
            IN_TextF_EmpID.setText(new EmpID().GetEID());
            IN_TextF_PostMNo.setText("not");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void Clear() {
        IN_TextF_ItemID.setText("");
        IN_TextF_ItemName.setText("");
        IN_TextF_Quant.setText("");
    }
}
