/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


public class PetC extends javax.swing.JPanel {

    /**
     * Creates new form PetC
     */
    public PetC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PetC_Label_Heading = new javax.swing.JLabel();
        PetC_LPane_SearchPetC = new javax.swing.JLayeredPane();
        PetC_Search_Label_PetCNO = new javax.swing.JLabel();
        CustStage_Search_CmbBox_CustStageID = new javax.swing.JComboBox<>();
        CustStage_Scp_1 = new javax.swing.JScrollPane();
        PetC_Search_Table_PetC = new javax.swing.JTable();
        PetC_Search_Label_Date = new javax.swing.JLabel();
        CustStage_Search_CmbBox_CustStageName1 = new javax.swing.JComboBox<>();
        PetC_Search_Btn_Search = new javax.swing.JButton();
        PetC_Search_Btn_ShowAllPetC = new javax.swing.JButton();
        CustStage_Scp_2 = new javax.swing.JScrollPane();
        PetC_Search_Table_Item = new javax.swing.JTable();
        PetC_Search_Label_Reson = new javax.swing.JLabel();
        AddCustStage_Scp_2 = new javax.swing.JScrollPane();
        PetC_Search_TextA_Reson = new javax.swing.JTextArea();
        PetC_LPane_AddPetC = new javax.swing.JLayeredPane();
        PetC_Add_Label_PetCNo = new javax.swing.JLabel();
        CustStage_Scp_3 = new javax.swing.JScrollPane();
        PetC_Add_Table_PetC = new javax.swing.JTable();
        PetC_Add_Label_ItemID = new javax.swing.JLabel();
        CustStage_Scp_4 = new javax.swing.JScrollPane();
        PetC_Add_Table_PetCItem = new javax.swing.JTable();
        PetC_Add_Label_Reson = new javax.swing.JLabel();
        AddCustStage_Scp_3 = new javax.swing.JScrollPane();
        PetC_Add_TextA_Reson = new javax.swing.JTextArea();
        PetC_Add_TextF_PetCNo = new javax.swing.JTextField();
        PetC_Add_TextF_ItemID = new javax.swing.JTextField();
        PetC_Add_Label_ItemName = new javax.swing.JLabel();
        PetC_Add_Label_Quant = new javax.swing.JLabel();
        PetC_Add_CBox_ShopItem = new javax.swing.JCheckBox();
        PetC_Add_TextF_ItemName = new javax.swing.JTextField();
        PetC_Add_TextF_Quant = new javax.swing.JTextField();
        PetC_Add_Label_ItemSellPrice = new javax.swing.JLabel();
        PetC_Add_TextF_ItemSellPrice = new javax.swing.JTextField();
        PetC_Add_Btn_AddPetCItem = new javax.swing.JButton();
        PetC_Add_Btn_RemoveAdded = new javax.swing.JButton();
        PetC_Add_Btn_Done = new javax.swing.JButton();
        PetC_Btn_Back = new javax.swing.JButton();
        PetC_Btn_Ok = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        PetC_Label_Heading.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        PetC_Label_Heading.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Label_Heading.setText("Petty Cash");

        PetC_LPane_SearchPetC.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Search Petty Cash", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        PetC_LPane_SearchPetC.setPreferredSize(new java.awt.Dimension(1052, 216));
        PetC_LPane_SearchPetC.setVerifyInputWhenFocusTarget(false);

        PetC_Search_Label_PetCNO.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Search_Label_PetCNO.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Search_Label_PetCNO.setText("Petty Cash No : ");

        CustStage_Search_CmbBox_CustStageID.setEditable(true);
        CustStage_Search_CmbBox_CustStageID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CustStage_Search_CmbBox_CustStageID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustStage_Search_CmbBox_CustStageID.setToolTipText("Petty Cash Number");
        CustStage_Search_CmbBox_CustStageID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustStage_Search_CmbBox_CustStageID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustStage_Search_CmbBox_CustStageIDActionPerformed(evt);
            }
        });

        PetC_Search_Table_PetC.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Search_Table_PetC.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Search_Table_PetC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Petty Cash No", "Date", "Time", "Employee Name", "Total", "Reson"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PetC_Search_Table_PetC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Search_Table_PetC.setGridColor(new java.awt.Color(102, 102, 102));
        PetC_Search_Table_PetC.setIntercellSpacing(new java.awt.Dimension(1, 0));
        PetC_Search_Table_PetC.setRowHeight(17);
        PetC_Search_Table_PetC.setSelectionBackground(new java.awt.Color(46, 141, 216));
        PetC_Search_Table_PetC.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_1.setViewportView(PetC_Search_Table_PetC);

        PetC_Search_Label_Date.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Search_Label_Date.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Search_Label_Date.setText("Date : ");

        CustStage_Search_CmbBox_CustStageName1.setEditable(true);
        CustStage_Search_CmbBox_CustStageName1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CustStage_Search_CmbBox_CustStageName1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustStage_Search_CmbBox_CustStageName1.setToolTipText("Petty Cash Date");
        CustStage_Search_CmbBox_CustStageName1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustStage_Search_CmbBox_CustStageName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustStage_Search_CmbBox_CustStageName1ActionPerformed(evt);
            }
        });

        PetC_Search_Btn_Search.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Search_Btn_Search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PetC_Search_Btn_Search.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Search_Btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/search (2).png"))); // NOI18N
        PetC_Search_Btn_Search.setText("Search");
        PetC_Search_Btn_Search.setToolTipText("Search");
        PetC_Search_Btn_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Search_Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Search_Btn_SearchActionPerformed(evt);
            }
        });

        PetC_Search_Btn_ShowAllPetC.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Search_Btn_ShowAllPetC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PetC_Search_Btn_ShowAllPetC.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Search_Btn_ShowAllPetC.setText("Show All Petty Cash");
        PetC_Search_Btn_ShowAllPetC.setToolTipText("Show All Petty Cash");
        PetC_Search_Btn_ShowAllPetC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Search_Btn_ShowAllPetC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Search_Btn_ShowAllPetCActionPerformed(evt);
            }
        });

        PetC_Search_Table_Item.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Search_Table_Item.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Search_Table_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PetC_Search_Table_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Search_Table_Item.setGridColor(new java.awt.Color(102, 102, 102));
        PetC_Search_Table_Item.setIntercellSpacing(new java.awt.Dimension(1, 0));
        PetC_Search_Table_Item.setRowHeight(17);
        PetC_Search_Table_Item.setSelectionBackground(new java.awt.Color(46, 141, 216));
        PetC_Search_Table_Item.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_2.setViewportView(PetC_Search_Table_Item);

        PetC_Search_Label_Reson.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Search_Label_Reson.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Search_Label_Reson.setText("Reson : ");

        AddCustStage_Scp_2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AddCustStage_Scp_2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PetC_Search_TextA_Reson.setEditable(false);
        PetC_Search_TextA_Reson.setColumns(20);
        PetC_Search_TextA_Reson.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Search_TextA_Reson.setLineWrap(true);
        PetC_Search_TextA_Reson.setRows(5);
        PetC_Search_TextA_Reson.setToolTipText("Reson for Petty Cash");
        PetC_Search_TextA_Reson.setWrapStyleWord(true);
        AddCustStage_Scp_2.setViewportView(PetC_Search_TextA_Reson);

        PetC_LPane_SearchPetC.setLayer(PetC_Search_Label_PetCNO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(CustStage_Search_CmbBox_CustStageID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(CustStage_Scp_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(PetC_Search_Label_Date, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(CustStage_Search_CmbBox_CustStageName1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(PetC_Search_Btn_Search, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(PetC_Search_Btn_ShowAllPetC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(CustStage_Scp_2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(PetC_Search_Label_Reson, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_SearchPetC.setLayer(AddCustStage_Scp_2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PetC_LPane_SearchPetCLayout = new javax.swing.GroupLayout(PetC_LPane_SearchPetC);
        PetC_LPane_SearchPetC.setLayout(PetC_LPane_SearchPetCLayout);
        PetC_LPane_SearchPetCLayout.setHorizontalGroup(
            PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetC_LPane_SearchPetCLayout.createSequentialGroup()
                .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PetC_LPane_SearchPetCLayout.createSequentialGroup()
                        .addComponent(PetC_Search_Btn_Search)
                        .addGap(70, 70, 70))
                    .addGroup(PetC_LPane_SearchPetCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PetC_LPane_SearchPetCLayout.createSequentialGroup()
                                .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PetC_Search_Label_PetCNO)
                                    .addComponent(PetC_Search_Label_Date))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CustStage_Search_CmbBox_CustStageID, 0, 157, Short.MAX_VALUE)
                                    .addComponent(CustStage_Search_CmbBox_CustStageName1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PetC_LPane_SearchPetCLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(PetC_Search_Btn_ShowAllPetC))
                            .addComponent(PetC_Search_Label_Reson, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PetC_LPane_SearchPetCLayout.createSequentialGroup()
                        .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustStage_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddCustStage_Scp_2))
                .addContainerGap())
        );
        PetC_LPane_SearchPetCLayout.setVerticalGroup(
            PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetC_LPane_SearchPetCLayout.createSequentialGroup()
                .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CustStage_Scp_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PetC_LPane_SearchPetCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetC_Search_Label_PetCNO)
                            .addComponent(CustStage_Search_CmbBox_CustStageID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustStage_Search_CmbBox_CustStageName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PetC_Search_Label_Date))
                        .addGap(18, 18, 18)
                        .addComponent(PetC_Search_Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PetC_Search_Btn_ShowAllPetC))
                    .addComponent(CustStage_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PetC_LPane_SearchPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddCustStage_Scp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetC_Search_Label_Reson)))
        );

        PetC_LPane_AddPetC.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add Petty Cash", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11), new java.awt.Color(104, 2, 5))); // NOI18N
        PetC_LPane_AddPetC.setPreferredSize(new java.awt.Dimension(1052, 216));
        PetC_LPane_AddPetC.setVerifyInputWhenFocusTarget(false);

        PetC_Add_Label_PetCNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Label_PetCNo.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Label_PetCNo.setText("Petty Cash No : ");

        PetC_Add_Table_PetC.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_Table_PetC.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Table_PetC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Petty Cash No", "Date", "Time", "Employee Name", "Total", "Reson"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PetC_Add_Table_PetC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Add_Table_PetC.setGridColor(new java.awt.Color(102, 102, 102));
        PetC_Add_Table_PetC.setIntercellSpacing(new java.awt.Dimension(1, 0));
        PetC_Add_Table_PetC.setRowHeight(17);
        PetC_Add_Table_PetC.setSelectionBackground(new java.awt.Color(46, 141, 216));
        PetC_Add_Table_PetC.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_3.setViewportView(PetC_Add_Table_PetC);

        PetC_Add_Label_ItemID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Label_ItemID.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Label_ItemID.setText("Item ID : ");

        PetC_Add_Table_PetCItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_Table_PetCItem.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Table_PetCItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PetC_Add_Table_PetCItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Add_Table_PetCItem.setGridColor(new java.awt.Color(102, 102, 102));
        PetC_Add_Table_PetCItem.setIntercellSpacing(new java.awt.Dimension(1, 0));
        PetC_Add_Table_PetCItem.setRowHeight(17);
        PetC_Add_Table_PetCItem.setSelectionBackground(new java.awt.Color(46, 141, 216));
        PetC_Add_Table_PetCItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustStage_Scp_4.setViewportView(PetC_Add_Table_PetCItem);

        PetC_Add_Label_Reson.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Label_Reson.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Label_Reson.setText("Reson : ");

        AddCustStage_Scp_3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AddCustStage_Scp_3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PetC_Add_TextA_Reson.setEditable(false);
        PetC_Add_TextA_Reson.setColumns(20);
        PetC_Add_TextA_Reson.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_TextA_Reson.setLineWrap(true);
        PetC_Add_TextA_Reson.setRows(5);
        PetC_Add_TextA_Reson.setToolTipText("Reson for Petty Cash ");
        PetC_Add_TextA_Reson.setWrapStyleWord(true);
        AddCustStage_Scp_3.setViewportView(PetC_Add_TextA_Reson);

        PetC_Add_TextF_PetCNo.setEditable(false);
        PetC_Add_TextF_PetCNo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_TextF_PetCNo.setToolTipText("Petty Cash Number");
        PetC_Add_TextF_PetCNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Add_TextF_PetCNoActionPerformed(evt);
            }
        });

        PetC_Add_TextF_ItemID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_TextF_ItemID.setToolTipText("Petty Cash Item");
        PetC_Add_TextF_ItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Add_TextF_ItemIDActionPerformed(evt);
            }
        });

        PetC_Add_Label_ItemName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Label_ItemName.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Label_ItemName.setText("Item Name : ");

        PetC_Add_Label_Quant.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Label_Quant.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Label_Quant.setText("Quantity : ");

        PetC_Add_CBox_ShopItem.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Add_CBox_ShopItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_CBox_ShopItem.setText("Shop Item");
        PetC_Add_CBox_ShopItem.setToolTipText("Check that the Item is Shop Item or Not");

        PetC_Add_TextF_ItemName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_TextF_ItemName.setToolTipText("Petty Cash Item Name");
        PetC_Add_TextF_ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Add_TextF_ItemNameActionPerformed(evt);
            }
        });

        PetC_Add_TextF_Quant.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_TextF_Quant.setToolTipText("Petty Cash Item Quantity");
        PetC_Add_TextF_Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Add_TextF_QuantActionPerformed(evt);
            }
        });

        PetC_Add_Label_ItemSellPrice.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Label_ItemSellPrice.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Label_ItemSellPrice.setText("Item Sell Price : ");

        PetC_Add_TextF_ItemSellPrice.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PetC_Add_TextF_ItemSellPrice.setToolTipText("Petty Cash Item Sell Price");
        PetC_Add_TextF_ItemSellPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Add_TextF_ItemSellPriceActionPerformed(evt);
            }
        });

        PetC_Add_Btn_AddPetCItem.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Add_Btn_AddPetCItem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Btn_AddPetCItem.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Btn_AddPetCItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Add_plus.png"))); // NOI18N
        PetC_Add_Btn_AddPetCItem.setText("Add");
        PetC_Add_Btn_AddPetCItem.setToolTipText("Add Item to Petty Cash");
        PetC_Add_Btn_AddPetCItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PetC_Add_Btn_RemoveAdded.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Add_Btn_RemoveAdded.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Btn_RemoveAdded.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Btn_RemoveAdded.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/trash_bin.png"))); // NOI18N
        PetC_Add_Btn_RemoveAdded.setToolTipText("Remove Added");
        PetC_Add_Btn_RemoveAdded.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Add_Btn_RemoveAdded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Add_Btn_RemoveAddedActionPerformed(evt);
            }
        });

        PetC_Add_Btn_Done.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Add_Btn_Done.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PetC_Add_Btn_Done.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Add_Btn_Done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/check.png"))); // NOI18N
        PetC_Add_Btn_Done.setText("Done");
        PetC_Add_Btn_Done.setToolTipText("Done");
        PetC_Add_Btn_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PetC_LPane_AddPetC.setLayer(PetC_Add_Label_PetCNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(CustStage_Scp_3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Label_ItemID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(CustStage_Scp_4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Label_Reson, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(AddCustStage_Scp_3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_TextF_PetCNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_TextF_ItemID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Label_ItemName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Label_Quant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_CBox_ShopItem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_TextF_ItemName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_TextF_Quant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Label_ItemSellPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_TextF_ItemSellPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Btn_AddPetCItem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Btn_RemoveAdded, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PetC_LPane_AddPetC.setLayer(PetC_Add_Btn_Done, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PetC_LPane_AddPetCLayout = new javax.swing.GroupLayout(PetC_LPane_AddPetC);
        PetC_LPane_AddPetC.setLayout(PetC_LPane_AddPetCLayout);
        PetC_LPane_AddPetCLayout.setHorizontalGroup(
            PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(PetC_Add_CBox_ShopItem)
                .addGap(133, 133, 133))
            .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PetC_Add_Label_PetCNo)
                    .addComponent(PetC_Add_Label_ItemID)
                    .addComponent(PetC_Add_Label_ItemName)
                    .addComponent(PetC_Add_Label_Quant)
                    .addComponent(PetC_Add_Label_ItemSellPrice)
                    .addComponent(PetC_Add_Label_Reson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                        .addComponent(AddCustStage_Scp_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PetC_Add_Btn_Done))
                    .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                        .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PetC_Add_TextF_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PetC_Add_TextF_ItemSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PetC_Add_TextF_PetCNo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PetC_Add_TextF_ItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PetC_Add_TextF_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PetC_Add_Btn_AddPetCItem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustStage_Scp_4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PetC_Add_Btn_RemoveAdded)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustStage_Scp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PetC_LPane_AddPetCLayout.setVerticalGroup(
            PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CustStage_Scp_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PetC_LPane_AddPetCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetC_Add_Label_PetCNo)
                            .addComponent(PetC_Add_TextF_PetCNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(PetC_Add_CBox_ShopItem)
                        .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                                        .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(PetC_Add_Label_ItemID)
                                            .addComponent(PetC_Add_TextF_ItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(PetC_Add_Label_ItemName)
                                            .addComponent(PetC_Add_TextF_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(PetC_Add_Btn_AddPetCItem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PetC_Add_Label_Quant)
                                    .addComponent(PetC_Add_TextF_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PetC_Add_Label_ItemSellPrice)
                                    .addComponent(PetC_Add_TextF_ItemSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(PetC_Add_Btn_RemoveAdded))))
                    .addComponent(CustStage_Scp_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PetC_LPane_AddPetCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PetC_LPane_AddPetCLayout.createSequentialGroup()
                        .addComponent(PetC_Add_Label_Reson)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(AddCustStage_Scp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(PetC_Add_Btn_Done, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PetC_Btn_Back.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Btn_Back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PetC_Btn_Back.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Btn_Back.setText("Back");
        PetC_Btn_Back.setToolTipText("Back");
        PetC_Btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Btn_BackActionPerformed(evt);
            }
        });

        PetC_Btn_Ok.setBackground(new java.awt.Color(204, 204, 204));
        PetC_Btn_Ok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PetC_Btn_Ok.setForeground(new java.awt.Color(51, 51, 51));
        PetC_Btn_Ok.setText("Ok");
        PetC_Btn_Ok.setToolTipText("Ok");
        PetC_Btn_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetC_Btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetC_Btn_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PetC_LPane_SearchPetC, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PetC_Label_Heading)
                        .addGap(479, 479, 479))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PetC_LPane_AddPetC, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PetC_Btn_Back)
                .addGap(6, 6, 6)
                .addComponent(PetC_Btn_Ok)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PetC_Label_Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PetC_LPane_SearchPetC, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PetC_LPane_AddPetC, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PetC_Btn_Back)
                    .addComponent(PetC_Btn_Ok))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CustStage_Search_CmbBox_CustStageIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustStage_Search_CmbBox_CustStageIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustStage_Search_CmbBox_CustStageIDActionPerformed

    private void CustStage_Search_CmbBox_CustStageName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustStage_Search_CmbBox_CustStageName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustStage_Search_CmbBox_CustStageName1ActionPerformed

    private void PetC_Search_Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Search_Btn_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Search_Btn_SearchActionPerformed

    private void PetC_Search_Btn_ShowAllPetCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Search_Btn_ShowAllPetCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Search_Btn_ShowAllPetCActionPerformed

    private void PetC_Add_TextF_PetCNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Add_TextF_PetCNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Add_TextF_PetCNoActionPerformed

    private void PetC_Add_TextF_ItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Add_TextF_ItemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Add_TextF_ItemIDActionPerformed

    private void PetC_Add_TextF_ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Add_TextF_ItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Add_TextF_ItemNameActionPerformed

    private void PetC_Add_TextF_QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Add_TextF_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Add_TextF_QuantActionPerformed

    private void PetC_Add_TextF_ItemSellPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Add_TextF_ItemSellPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Add_TextF_ItemSellPriceActionPerformed

    private void PetC_Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Btn_BackActionPerformed
        // TODSup_Label_Headingcode here:
    }//GEN-LAST:event_PetC_Btn_BackActionPerformed

    private void PetC_Btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Btn_OkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Btn_OkActionPerformed

    private void PetC_Add_Btn_RemoveAddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetC_Add_Btn_RemoveAddedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetC_Add_Btn_RemoveAddedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AddCustStage_Scp_2;
    private javax.swing.JScrollPane AddCustStage_Scp_3;
    private javax.swing.JScrollPane CustStage_Scp_1;
    private javax.swing.JScrollPane CustStage_Scp_2;
    private javax.swing.JScrollPane CustStage_Scp_3;
    private javax.swing.JScrollPane CustStage_Scp_4;
    private javax.swing.JComboBox<String> CustStage_Search_CmbBox_CustStageID;
    private javax.swing.JComboBox<String> CustStage_Search_CmbBox_CustStageName1;
    private javax.swing.JButton PetC_Add_Btn_AddPetCItem;
    private javax.swing.JButton PetC_Add_Btn_Done;
    private javax.swing.JButton PetC_Add_Btn_RemoveAdded;
    private javax.swing.JCheckBox PetC_Add_CBox_ShopItem;
    private javax.swing.JLabel PetC_Add_Label_ItemID;
    private javax.swing.JLabel PetC_Add_Label_ItemName;
    private javax.swing.JLabel PetC_Add_Label_ItemSellPrice;
    private javax.swing.JLabel PetC_Add_Label_PetCNo;
    private javax.swing.JLabel PetC_Add_Label_Quant;
    private javax.swing.JLabel PetC_Add_Label_Reson;
    private javax.swing.JTable PetC_Add_Table_PetC;
    private javax.swing.JTable PetC_Add_Table_PetCItem;
    private javax.swing.JTextArea PetC_Add_TextA_Reson;
    private javax.swing.JTextField PetC_Add_TextF_ItemID;
    private javax.swing.JTextField PetC_Add_TextF_ItemName;
    private javax.swing.JTextField PetC_Add_TextF_ItemSellPrice;
    private javax.swing.JTextField PetC_Add_TextF_PetCNo;
    private javax.swing.JTextField PetC_Add_TextF_Quant;
    private javax.swing.JButton PetC_Btn_Back;
    private javax.swing.JButton PetC_Btn_Ok;
    private javax.swing.JLayeredPane PetC_LPane_AddPetC;
    private javax.swing.JLayeredPane PetC_LPane_SearchPetC;
    private javax.swing.JLabel PetC_Label_Heading;
    private javax.swing.JButton PetC_Search_Btn_Search;
    private javax.swing.JButton PetC_Search_Btn_ShowAllPetC;
    private javax.swing.JLabel PetC_Search_Label_Date;
    private javax.swing.JLabel PetC_Search_Label_PetCNO;
    private javax.swing.JLabel PetC_Search_Label_Reson;
    private javax.swing.JTable PetC_Search_Table_Item;
    private javax.swing.JTable PetC_Search_Table_PetC;
    private javax.swing.JTextArea PetC_Search_TextA_Reson;
    // End of variables declaration//GEN-END:variables
}
