/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FoodCityMain;

import Interfaces.Admin.AAccessLevel;
import Interfaces.Admin.AAdvertiseType;
import Interfaces.Admin.ABType;
import Interfaces.Admin.AEmpAttend;
import Interfaces.Admin.ACustStage;
import Interfaces.Admin.AEmp;
import Interfaces.Admin.AEmpPos;
import Interfaces.Admin.AEmpSalAdv;
import Interfaces.Admin.AEmpSalPay;
import Interfaces.Admin.AEmp_EPF_ETF;
import Interfaces.Admin.AReSetEmpPW;
import Interfaces.Advertise;
import Interfaces.AdvertiseType;
import Interfaces.BType;
import Interfaces.Backup;
import Interfaces.BilMach;
import Interfaces.Cat;
import Interfaces.Complain;
import Interfaces.ContPers;
import Interfaces.Cust;
import Interfaces.CustAct;
import Interfaces.CustStage;
import Interfaces.DispItem;
import Interfaces.Donate;
import Interfaces.Emp;
import Interfaces.EmpAttend;
import Interfaces.EmpPos;
import Interfaces.EmpSal;
import Interfaces.EmpSalAdv;
import Interfaces.Emp_ETF_EPF;
import Interfaces.Item;
import Interfaces.ItemLot;
import Interfaces.ItemSup;
import Interfaces.MainSpend;
import Interfaces.OT;
import Interfaces.PetC;
import Interfaces.SubCat;
import Interfaces.Sup;
import Interfaces.SupItem;
import java.awt.Frame;


public class FoodCityAdmin extends javax.swing.JFrame {
    
    int posX,posY;
    /**
     * Creates new form FoodCityAdmin
     */
    public FoodCityAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_LPane = new javax.swing.JLayeredPane();
        Admin_Btn_Emp = new javax.swing.JButton();
        Admin_Btn_CustStage = new javax.swing.JButton();
        Admin_Btn_EmpPos = new javax.swing.JButton();
        Admin_Btn_AdvType = new javax.swing.JButton();
        Main_Close = new javax.swing.JLabel();
        Main_Minimize = new javax.swing.JLabel();
        Main_Top = new javax.swing.JLabel();
        Main_InternalFrame_MenBar = new javax.swing.JInternalFrame();
        Main_MenBar = new javax.swing.JMenuBar();
        Main_MenBar_File = new javax.swing.JMenu();
        Main_MenBar_File_Backup = new javax.swing.JMenuItem();
        Main_MenBar_File_Setting = new javax.swing.JMenuItem();
        Main_MenBar_File_Sep_After_Backup = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_File_Exit = new javax.swing.JMenuItem();
        Main_MenBar_Item = new javax.swing.JMenu();
        Main_MenBar_Item_Item = new javax.swing.JMenuItem();
        Main_MenBar_Item_Sep_After_ByLot = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Item_MenILot_Lot = new javax.swing.JMenuItem();
        Main_MenBar_Item_MenCat_Cat = new javax.swing.JMenuItem();
        Main_MenBar_Item_MenSubCat_SubCat = new javax.swing.JMenuItem();
        Main_MenBar_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Item_ItemSup = new javax.swing.JMenuItem();
        Main_MenBar_Sup = new javax.swing.JMenu();
        Main_MenBar_Sup_Sup = new javax.swing.JMenuItem();
        Main_MenBar_Sup_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Sup_MenContPers_ContPers = new javax.swing.JMenuItem();
        Main_MenBar_Sup_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Sup_SuplyItems = new javax.swing.JMenuItem();
        Main_MenBar_Customer = new javax.swing.JMenu();
        Main_MenBar_Cust_Cust = new javax.swing.JMenuItem();
        Main_MenBar_Cust_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Cust_MenCustStage_CustStage = new javax.swing.JMenuItem();
        Main_MenBar_Cust_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Cust_CustAct = new javax.swing.JMenuItem();
        Main_MenBar_Emp = new javax.swing.JMenu();
        Main_MenBar_Emp_Employees = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Emp_MenEmpPos_EmpPos = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Emp_Emp_ETF_EPF = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Sep3 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Emp_EmpAttend = new javax.swing.JMenuItem();
        Main_MenBar_Emp_OT = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Salary = new javax.swing.JMenuItem();
        Main_MenBar_Emp_SalaryAdv = new javax.swing.JMenuItem();
        Main_MenBar_Dispose = new javax.swing.JMenu();
        Main_MenBar_Dispose_DispItems = new javax.swing.JMenuItem();
        Main_MenBar_Ad = new javax.swing.JMenu();
        Main_MenBar_Ad_Ad = new javax.swing.JMenuItem();
        Main_MenBar_Ad_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Ad_MenAdType_AdType = new javax.swing.JMenuItem();
        Main_MenBar_Spend = new javax.swing.JMenu();
        Main_MenBar_Spend_MenPetCash_PetCash = new javax.swing.JMenuItem();
        Main_MenBar_Spend_MenMainSpend = new javax.swing.JMenu();
        Main_MenBar_Spend_MenMainSpend_MainSpend = new javax.swing.JMenuItem();
        Main_MenBar_Spend_MenMainSpend_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp = new javax.swing.JMenuItem();
        Main_MenBar_Donate = new javax.swing.JMenu();
        Main_MenBar_Donate_Donate = new javax.swing.JMenuItem();
        Main_MenBar_Complain = new javax.swing.JMenu();
        Main_MenBar_Complain_Complain = new javax.swing.JMenuItem();
        Main_MenBar_Other = new javax.swing.JMenu();
        Main_MenBar_MenBilMac_BilMac = new javax.swing.JMenuItem();
        Admin_Btn_EmpSalPay = new javax.swing.JButton();
        Admin_Btn_ReSetEmpPW = new javax.swing.JButton();
        Admin_Btn_BillType = new javax.swing.JButton();
        Admin_Btn_EmpAttend = new javax.swing.JButton();
        Admin_Btn_EmpSalAdv = new javax.swing.JButton();
        Admin_Btn_SetEtfEpf = new javax.swing.JButton();
        Admin_Btn_EmpAccLevel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_LPane.setBackground(new java.awt.Color(204, 204, 204));
        Admin_LPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Admin_LPane.setPreferredSize(new java.awt.Dimension(1084, 590));

        javax.swing.GroupLayout Admin_LPaneLayout = new javax.swing.GroupLayout(Admin_LPane);
        Admin_LPane.setLayout(Admin_LPaneLayout);
        Admin_LPaneLayout.setHorizontalGroup(
            Admin_LPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Admin_LPaneLayout.setVerticalGroup(
            Admin_LPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Admin_LPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        Admin_Btn_Emp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_Emp.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_Emp.setText("Employee");
        Admin_Btn_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_EmpActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_Emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        Admin_Btn_CustStage.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_CustStage.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_CustStage.setText("Customer Stage");
        Admin_Btn_CustStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_CustStageActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_CustStage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        Admin_Btn_EmpPos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_EmpPos.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_EmpPos.setText("Employee Positions");
        Admin_Btn_EmpPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_EmpPosActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_EmpPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 170, -1));

        Admin_Btn_AdvType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_AdvType.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_AdvType.setText("Advertising Type");
        Admin_Btn_AdvType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_AdvTypeActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_AdvType, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 160, -1));

        Main_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MAIN_CLOSE_2.png"))); // NOI18N
        Main_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Main_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main_CloseMouseExited(evt);
            }
        });
        getContentPane().add(Main_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 0, -1, -1));

        Main_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MINI.png"))); // NOI18N
        Main_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main_MinimizeMouseExited(evt);
            }
        });
        getContentPane().add(Main_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        Main_Top.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Main_Top.setForeground(new java.awt.Color(153, 153, 153));
        Main_Top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Admin.png"))); // NOI18N
        Main_Top.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Main_TopMouseDragged(evt);
            }
        });
        Main_Top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Main_TopMousePressed(evt);
            }
        });
        getContentPane().add(Main_Top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        Main_InternalFrame_MenBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Main_InternalFrame_MenBar.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Main_InternalFrame_MenBar.setEnabled(false);
        Main_InternalFrame_MenBar.setVisible(true);

        Main_MenBar.setBackground(new java.awt.Color(51, 51, 51));
        Main_MenBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Main_MenBar.setForeground(new java.awt.Color(255, 255, 255));
        Main_MenBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_File.setText("File");
        Main_MenBar_File.setToolTipText("File");
        Main_MenBar_File.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_File_Backup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Main_MenBar_File_Backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/database.png"))); // NOI18N
        Main_MenBar_File_Backup.setText("Backup");
        Main_MenBar_File_Backup.setToolTipText("Backup");
        Main_MenBar_File_Backup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File_Backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_File_BackupActionPerformed(evt);
            }
        });
        Main_MenBar_File.add(Main_MenBar_File_Backup);

        Main_MenBar_File_Setting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Main_MenBar_File_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/settings (2).png"))); // NOI18N
        Main_MenBar_File_Setting.setText("Settings");
        Main_MenBar_File_Setting.setToolTipText("Settings");
        Main_MenBar_File_Setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File.add(Main_MenBar_File_Setting);
        Main_MenBar_File.add(Main_MenBar_File_Sep_After_Backup);

        Main_MenBar_File_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Main_MenBar_File_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/exit.png"))); // NOI18N
        Main_MenBar_File_Exit.setText("Exit");
        Main_MenBar_File_Exit.setToolTipText("Exit");
        Main_MenBar_File_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File.add(Main_MenBar_File_Exit);

        Main_MenBar.add(Main_MenBar_File);

        Main_MenBar_Item.setText("Item");
        Main_MenBar_Item.setToolTipText("Item");
        Main_MenBar_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Item_Item.setText("Items");
        Main_MenBar_Item_Item.setToolTipText("Items");
        Main_MenBar_Item_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_ItemActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_Item);
        Main_MenBar_Item.add(Main_MenBar_Item_Sep_After_ByLot);

        Main_MenBar_Item_MenILot_Lot.setText("Item Lots");
        Main_MenBar_Item_MenILot_Lot.setToolTipText("Item Lots");
        Main_MenBar_Item_MenILot_Lot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_MenILot_Lot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_MenILot_LotActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_MenILot_Lot);

        Main_MenBar_Item_MenCat_Cat.setText("Categories");
        Main_MenBar_Item_MenCat_Cat.setToolTipText("Categories");
        Main_MenBar_Item_MenCat_Cat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_MenCat_Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_MenCat_CatActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_MenCat_Cat);

        Main_MenBar_Item_MenSubCat_SubCat.setText("Sub Categories");
        Main_MenBar_Item_MenSubCat_SubCat.setToolTipText("Sub Categories");
        Main_MenBar_Item_MenSubCat_SubCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_MenSubCat_SubCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_MenSubCat_SubCatActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_MenSubCat_SubCat);
        Main_MenBar_Item.add(Main_MenBar_Sep2);

        Main_MenBar_Item_ItemSup.setText("Item Supliers");
        Main_MenBar_Item_ItemSup.setToolTipText("Item Supliers");
        Main_MenBar_Item_ItemSup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_ItemSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_ItemSupActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_ItemSup);

        Main_MenBar.add(Main_MenBar_Item);

        Main_MenBar_Sup.setText("Suplier");
        Main_MenBar_Sup.setToolTipText("Suplier");
        Main_MenBar_Sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Sup_Sup.setText("Supliers");
        Main_MenBar_Sup_Sup.setToolTipText("Supliers");
        Main_MenBar_Sup_Sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup_Sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Sup_SupActionPerformed(evt);
            }
        });
        Main_MenBar_Sup.add(Main_MenBar_Sup_Sup);
        Main_MenBar_Sup.add(Main_MenBar_Sup_Sep1);

        Main_MenBar_Sup_MenContPers_ContPers.setText("Contact Persons");
        Main_MenBar_Sup_MenContPers_ContPers.setToolTipText("Contact Persons");
        Main_MenBar_Sup_MenContPers_ContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup_MenContPers_ContPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Sup_MenContPers_ContPersActionPerformed(evt);
            }
        });
        Main_MenBar_Sup.add(Main_MenBar_Sup_MenContPers_ContPers);
        Main_MenBar_Sup.add(Main_MenBar_Sup_Sep2);

        Main_MenBar_Sup_SuplyItems.setText("Suply Items");
        Main_MenBar_Sup_SuplyItems.setToolTipText("Suply Items");
        Main_MenBar_Sup_SuplyItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup_SuplyItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Sup_SuplyItemsActionPerformed(evt);
            }
        });
        Main_MenBar_Sup.add(Main_MenBar_Sup_SuplyItems);

        Main_MenBar.add(Main_MenBar_Sup);

        Main_MenBar_Customer.setText("Customer");
        Main_MenBar_Customer.setToolTipText("Customer");
        Main_MenBar_Customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Customer.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Cust_Cust.setText("Customers");
        Main_MenBar_Cust_Cust.setToolTipText("Customers");
        Main_MenBar_Cust_Cust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Cust_Cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Cust_CustActionPerformed(evt);
            }
        });
        Main_MenBar_Customer.add(Main_MenBar_Cust_Cust);
        Main_MenBar_Customer.add(Main_MenBar_Cust_Sep1);

        Main_MenBar_Cust_MenCustStage_CustStage.setText("Customer Stages");
        Main_MenBar_Cust_MenCustStage_CustStage.setToolTipText("Customer Stages");
        Main_MenBar_Cust_MenCustStage_CustStage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Cust_MenCustStage_CustStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Cust_MenCustStage_CustStageActionPerformed(evt);
            }
        });
        Main_MenBar_Customer.add(Main_MenBar_Cust_MenCustStage_CustStage);
        Main_MenBar_Customer.add(Main_MenBar_Cust_Sep2);

        Main_MenBar_Cust_CustAct.setText("Customer Activity");
        Main_MenBar_Cust_CustAct.setToolTipText("Customer Activity");
        Main_MenBar_Cust_CustAct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Cust_CustAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Cust_CustActActionPerformed(evt);
            }
        });
        Main_MenBar_Customer.add(Main_MenBar_Cust_CustAct);

        Main_MenBar.add(Main_MenBar_Customer);

        Main_MenBar_Emp.setText("Employee");
        Main_MenBar_Emp.setToolTipText("Employee");
        Main_MenBar_Emp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Emp_Employees.setText("Employees");
        Main_MenBar_Emp_Employees.setToolTipText("Employees");
        Main_MenBar_Emp_Employees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_Employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_EmployeesActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_Employees);
        Main_MenBar_Emp.add(Main_MenBar_Emp_Sep1);

        Main_MenBar_Emp_MenEmpPos_EmpPos.setText("Employee Positions");
        Main_MenBar_Emp_MenEmpPos_EmpPos.setToolTipText("Employee Positions");
        Main_MenBar_Emp_MenEmpPos_EmpPos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_MenEmpPos_EmpPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_MenEmpPos_EmpPos);
        Main_MenBar_Emp.add(Main_MenBar_Emp_Sep2);

        Main_MenBar_Emp_Emp_ETF_EPF.setText("Employee ETF & EPF");
        Main_MenBar_Emp_Emp_ETF_EPF.setToolTipText("Employee ETF");
        Main_MenBar_Emp_Emp_ETF_EPF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_Emp_ETF_EPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_Emp_ETF_EPFActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_Emp_ETF_EPF);
        Main_MenBar_Emp.add(Main_MenBar_Emp_Sep3);

        Main_MenBar_Emp_EmpAttend.setText("Employee Attendent");
        Main_MenBar_Emp_EmpAttend.setToolTipText("Employee Attendent");
        Main_MenBar_Emp_EmpAttend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_EmpAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_EmpAttendActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_EmpAttend);

        Main_MenBar_Emp_OT.setText("OT");
        Main_MenBar_Emp_OT.setToolTipText("OT");
        Main_MenBar_Emp_OT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_OT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_OTActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_OT);

        Main_MenBar_Emp_Salary.setText("Salary");
        Main_MenBar_Emp_Salary.setToolTipText("Salary");
        Main_MenBar_Emp_Salary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_SalaryActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_Salary);

        Main_MenBar_Emp_SalaryAdv.setText("Salary Advance");
        Main_MenBar_Emp_SalaryAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_SalaryAdvActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_SalaryAdv);

        Main_MenBar.add(Main_MenBar_Emp);

        Main_MenBar_Dispose.setText("Dispose");
        Main_MenBar_Dispose.setToolTipText("Dispose");
        Main_MenBar_Dispose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Dispose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Dispose_DispItems.setText("Disposed Items");
        Main_MenBar_Dispose_DispItems.setToolTipText("Disposed Items");
        Main_MenBar_Dispose_DispItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Dispose_DispItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Dispose_DispItemsActionPerformed(evt);
            }
        });
        Main_MenBar_Dispose.add(Main_MenBar_Dispose_DispItems);

        Main_MenBar.add(Main_MenBar_Dispose);

        Main_MenBar_Ad.setText("Advertising");
        Main_MenBar_Ad.setToolTipText("Advertising");
        Main_MenBar_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Ad.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Ad_Ad.setText("Advertisings");
        Main_MenBar_Ad_Ad.setToolTipText("Advertises");
        Main_MenBar_Ad_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Ad_Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Ad_AdActionPerformed(evt);
            }
        });
        Main_MenBar_Ad.add(Main_MenBar_Ad_Ad);
        Main_MenBar_Ad.add(Main_MenBar_Ad_Sep2);

        Main_MenBar_Ad_MenAdType_AdType.setText("Advertise Types");
        Main_MenBar_Ad_MenAdType_AdType.setToolTipText("Advertise Types");
        Main_MenBar_Ad_MenAdType_AdType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Ad_MenAdType_AdType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Ad_MenAdType_AdTypeActionPerformed(evt);
            }
        });
        Main_MenBar_Ad.add(Main_MenBar_Ad_MenAdType_AdType);

        Main_MenBar.add(Main_MenBar_Ad);

        Main_MenBar_Spend.setText("Spendings");
        Main_MenBar_Spend.setToolTipText("Spendings");
        Main_MenBar_Spend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Spend_MenPetCash_PetCash.setText("Petty Cash");
        Main_MenBar_Spend_MenPetCash_PetCash.setToolTipText("Petty Cash");
        Main_MenBar_Spend_MenPetCash_PetCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend_MenPetCash_PetCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Spend_MenPetCash_PetCashActionPerformed(evt);
            }
        });
        Main_MenBar_Spend.add(Main_MenBar_Spend_MenPetCash_PetCash);

        Main_MenBar_Spend_MenMainSpend.setText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend.setToolTipText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Main_MenBar_Spend_MenMainSpend_MainSpend.setText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend_MainSpend.setToolTipText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend_MainSpend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend_MenMainSpend_MainSpend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed(evt);
            }
        });
        Main_MenBar_Spend_MenMainSpend.add(Main_MenBar_Spend_MenMainSpend_MainSpend);
        Main_MenBar_Spend_MenMainSpend.add(Main_MenBar_Spend_MenMainSpend_Sep1);

        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.setText("Bill Types");
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.setToolTipText("Bill Types");
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed(evt);
            }
        });
        Main_MenBar_Spend_MenMainSpend.add(Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp);

        Main_MenBar_Spend.add(Main_MenBar_Spend_MenMainSpend);

        Main_MenBar.add(Main_MenBar_Spend);

        Main_MenBar_Donate.setText("Donations");
        Main_MenBar_Donate.setToolTipText("Donations");
        Main_MenBar_Donate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Donate.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Donate_Donate.setText("Donations");
        Main_MenBar_Donate_Donate.setToolTipText("Donations");
        Main_MenBar_Donate_Donate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Donate_Donate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Donate_DonateActionPerformed(evt);
            }
        });
        Main_MenBar_Donate.add(Main_MenBar_Donate_Donate);

        Main_MenBar.add(Main_MenBar_Donate);

        Main_MenBar_Complain.setText("Complains");
        Main_MenBar_Complain.setToolTipText("Complains");
        Main_MenBar_Complain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Complain.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Complain_Complain.setText("Complains");
        Main_MenBar_Complain_Complain.setToolTipText("Complains");
        Main_MenBar_Complain_Complain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Complain_Complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Complain_ComplainActionPerformed(evt);
            }
        });
        Main_MenBar_Complain.add(Main_MenBar_Complain_Complain);

        Main_MenBar.add(Main_MenBar_Complain);

        Main_MenBar_Other.setText("Other");
        Main_MenBar_Other.setToolTipText("Other");
        Main_MenBar_Other.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Other.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_MenBilMac_BilMac.setText("Billing Machines");
        Main_MenBar_MenBilMac_BilMac.setToolTipText("Billing Machines");
        Main_MenBar_MenBilMac_BilMac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_MenBilMac_BilMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_MenBilMac_BilMacActionPerformed(evt);
            }
        });
        Main_MenBar_Other.add(Main_MenBar_MenBilMac_BilMac);

        Main_MenBar.add(Main_MenBar_Other);

        Main_InternalFrame_MenBar.setJMenuBar(Main_MenBar);

        javax.swing.GroupLayout Main_InternalFrame_MenBarLayout = new javax.swing.GroupLayout(Main_InternalFrame_MenBar.getContentPane());
        Main_InternalFrame_MenBar.getContentPane().setLayout(Main_InternalFrame_MenBarLayout);
        Main_InternalFrame_MenBarLayout.setHorizontalGroup(
            Main_InternalFrame_MenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        Main_InternalFrame_MenBarLayout.setVerticalGroup(
            Main_InternalFrame_MenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Main_InternalFrame_MenBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1104, -1));

        Admin_Btn_EmpSalPay.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_EmpSalPay.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_EmpSalPay.setText("Employee Salary Pay");
        Admin_Btn_EmpSalPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_EmpSalPayActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_EmpSalPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 27));

        Admin_Btn_ReSetEmpPW.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_ReSetEmpPW.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_ReSetEmpPW.setText("Re-Set Employee Password");
        Admin_Btn_ReSetEmpPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_ReSetEmpPWActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_ReSetEmpPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 230, -1));

        Admin_Btn_BillType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_BillType.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_BillType.setText("Bill Type");
        Admin_Btn_BillType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_BillTypeActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_BillType, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, 110, -1));

        Admin_Btn_EmpAttend.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_EmpAttend.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_EmpAttend.setText("Employee Attendent");
        Admin_Btn_EmpAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_EmpAttendActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_EmpAttend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 27));

        Admin_Btn_EmpSalAdv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_EmpSalAdv.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_EmpSalAdv.setText("Employee Salary Advance");
        Admin_Btn_EmpSalAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_EmpSalAdvActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_EmpSalAdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        Admin_Btn_SetEtfEpf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_SetEtfEpf.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_SetEtfEpf.setText("Set ETF / EPF");
        Admin_Btn_SetEtfEpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_SetEtfEpfActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_SetEtfEpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, -1, -1));

        Admin_Btn_EmpAccLevel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_Btn_EmpAccLevel.setForeground(new java.awt.Color(51, 51, 51));
        Admin_Btn_EmpAccLevel.setText("Employee Access Levels");
        Admin_Btn_EmpAccLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Btn_EmpAccLevelActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_Btn_EmpAccLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        setSize(new java.awt.Dimension(1104, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Main_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_CloseMouseClicked
        FoodCityMain FoodCityMainObj = new FoodCityMain();
        FoodCityMainObj.setVisible(true);
        this.dispose();// MouseEvent Close Button
    }//GEN-LAST:event_Main_CloseMouseClicked

    private void Main_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_CloseMouseEntered
        Main_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MAIN_CLOSE.png")));//Mouse Entering
    }//GEN-LAST:event_Main_CloseMouseEntered

    private void Main_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_CloseMouseExited
        Main_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MAIN_CLOSE_2.png")));//Mouse Exiting
    }//GEN-LAST:event_Main_CloseMouseExited

    private void Main_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_MinimizeMouseClicked
        this.setState(Frame.ICONIFIED);// Minimize
    }//GEN-LAST:event_Main_MinimizeMouseClicked

    private void Main_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_MinimizeMouseEntered
        Main_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MINI_2.png")));
    }//GEN-LAST:event_Main_MinimizeMouseEntered

    private void Main_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_MinimizeMouseExited
        Main_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MINI.png")));
    }//GEN-LAST:event_Main_MinimizeMouseExited

    private void Main_TopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_TopMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - posX, this.getLocation().y + evt.getY() - posY);//Set moving JFrame
    }//GEN-LAST:event_Main_TopMouseDragged

    private void Main_TopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_TopMousePressed
        posX = evt.getX();//Mouse Get X
        posY = evt.getY();//Mouse Get Y
    }//GEN-LAST:event_Main_TopMousePressed

    private void Admin_Btn_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_EmpActionPerformed
        AEmp AEmpObj = new AEmp();
        AEmpObj.setSize(1084,590);
        AEmpObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AEmpObj);
        Admin_LPane.moveToFront(AEmpObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_EmpActionPerformed

    private void Admin_Btn_CustStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_CustStageActionPerformed
        ACustStage ACustStageObj = new ACustStage();
        ACustStageObj.setSize(1084,590);
        ACustStageObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(ACustStageObj);
        Admin_LPane.moveToFront(ACustStageObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_CustStageActionPerformed

    private void Admin_Btn_EmpPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_EmpPosActionPerformed
        AEmpPos EmpPosObj = new AEmpPos();
        EmpPosObj.setSize(1084,590);
        EmpPosObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(EmpPosObj);
        Admin_LPane.moveToFront(EmpPosObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_EmpPosActionPerformed

    private void Admin_Btn_AdvTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_AdvTypeActionPerformed
        AAdvertiseType AAdvertiseTypeObj = new AAdvertiseType();
        AAdvertiseTypeObj.setSize(1084,590);
        AAdvertiseTypeObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AAdvertiseTypeObj);
        Admin_LPane.moveToFront(AAdvertiseTypeObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_AdvTypeActionPerformed

    private void Admin_Btn_ReSetEmpPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_ReSetEmpPWActionPerformed
        AReSetEmpPW AReSetEmpPWObj = new AReSetEmpPW();
        AReSetEmpPWObj.setSize(1084, 590);
        AReSetEmpPWObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AReSetEmpPWObj);
        Admin_LPane.moveToFront(AReSetEmpPWObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_ReSetEmpPWActionPerformed

    private void Main_MenBar_File_BackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_File_BackupActionPerformed
        Backup BackupObj = new Backup();
        BackupObj.setSize(1084, 590);
        BackupObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(BackupObj);
        Admin_LPane.moveToFront(BackupObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_File_BackupActionPerformed

    private void Main_MenBar_Item_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_ItemActionPerformed
        Item ItemObj = new Item();
        ItemObj.setSize(1084, 590);
        ItemObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(ItemObj);
        Admin_LPane.moveToFront(ItemObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_ItemActionPerformed

    private void Main_MenBar_Item_MenILot_LotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_MenILot_LotActionPerformed
        ItemLot ItemLotObj = new ItemLot();
        ItemLotObj.setSize(1084, 590);
        ItemLotObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(ItemLotObj);
        Admin_LPane.moveToFront(ItemLotObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_MenILot_LotActionPerformed

    private void Main_MenBar_Item_MenCat_CatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_MenCat_CatActionPerformed
        Cat CatObj = new Cat();
        CatObj.setSize(1084, 590);
        CatObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(CatObj);
        Admin_LPane.moveToFront(CatObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_MenCat_CatActionPerformed

    private void Main_MenBar_Item_MenSubCat_SubCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_MenSubCat_SubCatActionPerformed
        SubCat SubCatObj = new SubCat();
        SubCatObj.setSize(1084, 590);
        SubCatObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(SubCatObj);
        Admin_LPane.moveToFront(SubCatObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_MenSubCat_SubCatActionPerformed

    private void Main_MenBar_Item_ItemSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_ItemSupActionPerformed
        ItemSup ItemSupObj = new ItemSup();
        ItemSupObj.setSize(1084,590);
        ItemSupObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(ItemSupObj);
        Admin_LPane.moveToFront(ItemSupObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_ItemSupActionPerformed

    private void Main_MenBar_Sup_SupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Sup_SupActionPerformed
        Sup SupObj = new Sup();
        SupObj.setSize(1084, 590);
        SupObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(SupObj);
        Admin_LPane.moveToFront(SupObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Sup_SupActionPerformed

    private void Main_MenBar_Sup_MenContPers_ContPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Sup_MenContPers_ContPersActionPerformed
        ContPers ContPersObj = new ContPers();
        ContPersObj.setSize(1084,590);
        ContPersObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(ContPersObj);
        Admin_LPane.moveToFront(ContPersObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Sup_MenContPers_ContPersActionPerformed

    private void Main_MenBar_Sup_SuplyItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Sup_SuplyItemsActionPerformed
        SupItem SupItemObj = new SupItem();
        SupItemObj.setSize(1084, 590);
        SupItemObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(SupItemObj);
        Admin_LPane.moveToFront(SupItemObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Sup_SuplyItemsActionPerformed

    private void Main_MenBar_Cust_CustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Cust_CustActionPerformed
        Cust CustObj = new Cust();
        CustObj.setSize(1084, 590);
        CustObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(CustObj);
        Admin_LPane.moveToFront(CustObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Cust_CustActionPerformed

    private void Main_MenBar_Cust_MenCustStage_CustStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Cust_MenCustStage_CustStageActionPerformed
        CustStage CustStageObj = new CustStage();
        CustStageObj.setSize(1084, 590);
        CustStageObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(CustStageObj);
        Admin_LPane.moveToFront(CustStageObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Cust_MenCustStage_CustStageActionPerformed

    private void Main_MenBar_Cust_CustActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Cust_CustActActionPerformed
        CustAct CustActObj = new CustAct();
        CustActObj.setSize(1084, 590);
        CustActObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(CustActObj);
        Admin_LPane.moveToFront(CustActObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Cust_CustActActionPerformed

    private void Main_MenBar_Emp_EmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_EmployeesActionPerformed
        Emp EmpObj = new Emp();
        EmpObj.setSize(1084, 590);
        EmpObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(EmpObj);
        Admin_LPane.moveToFront(EmpObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_EmployeesActionPerformed

    private void Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed
        EmpPos EmpPosObj = new EmpPos();
        EmpPosObj.setSize(1084, 590);
        EmpPosObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(EmpPosObj);
        Admin_LPane.moveToFront(EmpPosObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed

    private void Main_MenBar_Emp_OTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_OTActionPerformed
        OT OTObj = new OT();
        OTObj.setSize(1084, 590);
        OTObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(OTObj);
        Admin_LPane.moveToFront(OTObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_OTActionPerformed

    private void Main_MenBar_Emp_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_SalaryActionPerformed
        EmpSal EmpSalObj = new EmpSal();
        EmpSalObj.setSize(1084, 590);
        EmpSalObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(EmpSalObj);
        Admin_LPane.moveToFront(EmpSalObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_SalaryActionPerformed

    private void Main_MenBar_Dispose_DispItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Dispose_DispItemsActionPerformed
        DispItem DispItemObj = new DispItem();
        DispItemObj.setSize(1084,590);
        DispItemObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(DispItemObj);
        Admin_LPane.moveToFront(DispItemObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Dispose_DispItemsActionPerformed

    private void Main_MenBar_Ad_AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Ad_AdActionPerformed
        Advertise AdvertiseObj = new Advertise();
        AdvertiseObj.setSize(1084, 590);
        AdvertiseObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AdvertiseObj);
        Admin_LPane.moveToFront(AdvertiseObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Ad_AdActionPerformed

    private void Main_MenBar_Ad_MenAdType_AdTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Ad_MenAdType_AdTypeActionPerformed
        AdvertiseType AdvertiseTypeObj = new AdvertiseType();
        AdvertiseTypeObj.setSize(1084, 590);
        AdvertiseTypeObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AdvertiseTypeObj);
        Admin_LPane.moveToFront(AdvertiseTypeObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Ad_MenAdType_AdTypeActionPerformed

    private void Main_MenBar_Spend_MenPetCash_PetCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Spend_MenPetCash_PetCashActionPerformed
        PetC PetCObj = new PetC();
        PetCObj.setSize(1084, 590);
        PetCObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(PetCObj);
        Admin_LPane.moveToFront(PetCObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Spend_MenPetCash_PetCashActionPerformed

    private void Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed
        MainSpend MainSpendObj = new MainSpend();
        MainSpendObj.setSize(1084, 590);
        MainSpendObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(MainSpendObj);
        Admin_LPane.moveToFront(MainSpendObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed

    private void Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed
        BType BTypeObj = new BType();
        BTypeObj.setSize(1084, 590);
        BTypeObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(BTypeObj);
        Admin_LPane.moveToFront(BTypeObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed

    private void Main_MenBar_Donate_DonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Donate_DonateActionPerformed
        Donate DonateObj = new Donate();
        DonateObj.setSize(1084, 590);
        DonateObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(DonateObj);
        Admin_LPane.moveToFront(DonateObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Donate_DonateActionPerformed

    private void Main_MenBar_Complain_ComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Complain_ComplainActionPerformed
        Complain ComplainObj = new Complain();
        ComplainObj.setSize(1084, 590);
        ComplainObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(ComplainObj);
        Admin_LPane.moveToFront(ComplainObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Complain_ComplainActionPerformed

    private void Main_MenBar_MenBilMac_BilMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_MenBilMac_BilMacActionPerformed
        BilMach BilMachObj = new BilMach();
        BilMachObj.setSize(1084, 590);
        BilMachObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(BilMachObj);
        Admin_LPane.moveToFront(BilMachObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_MenBilMac_BilMacActionPerformed

    private void Admin_Btn_EmpSalPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_EmpSalPayActionPerformed
        AEmpSalPay AEmpSalPayObj = new AEmpSalPay();
        AEmpSalPayObj.setSize(1084, 590);
        AEmpSalPayObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AEmpSalPayObj);
        Admin_LPane.moveToFront(AEmpSalPayObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_EmpSalPayActionPerformed

    private void Admin_Btn_BillTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_BillTypeActionPerformed
        ABType ABTypeObj = new ABType();
        ABTypeObj.setSize(1084, 590);
        ABTypeObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(ABTypeObj);
        Admin_LPane.moveToFront(ABTypeObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_BillTypeActionPerformed

    private void Main_MenBar_Emp_EmpAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_EmpAttendActionPerformed
        EmpAttend EmpAttendObj = new EmpAttend();
        EmpAttendObj.setSize(1084, 590);
        EmpAttendObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(EmpAttendObj);
        Admin_LPane.moveToFront(EmpAttendObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_EmpAttendActionPerformed

    private void Admin_Btn_EmpAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_EmpAttendActionPerformed
        AEmpAttend AEmpAttendObj = new AEmpAttend();
        AEmpAttendObj.setSize(1084, 590);
        AEmpAttendObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AEmpAttendObj);
        Admin_LPane.moveToFront(AEmpAttendObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_EmpAttendActionPerformed

    private void Admin_Btn_EmpSalAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_EmpSalAdvActionPerformed
        AEmpSalAdv AEmpSalAdvObj = new AEmpSalAdv();
        AEmpSalAdvObj.setSize(1084, 590);
        AEmpSalAdvObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AEmpSalAdvObj);
        Admin_LPane.moveToFront(AEmpSalAdvObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_EmpSalAdvActionPerformed

    private void Main_MenBar_Emp_SalaryAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_SalaryAdvActionPerformed
        EmpSalAdv EmpSalAdvObj = new EmpSalAdv();
        EmpSalAdvObj.setSize(1084, 590);
        EmpSalAdvObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(EmpSalAdvObj);
        Admin_LPane.moveToFront(EmpSalAdvObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_SalaryAdvActionPerformed

    private void Admin_Btn_SetEtfEpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_SetEtfEpfActionPerformed
        AEmp_EPF_ETF AEmp_EPF_ETFObj = new AEmp_EPF_ETF();
        AEmp_EPF_ETFObj.setSize(1084, 590);
        AEmp_EPF_ETFObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AEmp_EPF_ETFObj);
        Admin_LPane.moveToFront(AEmp_EPF_ETFObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_SetEtfEpfActionPerformed

    private void Main_MenBar_Emp_Emp_ETF_EPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_Emp_ETF_EPFActionPerformed
        Emp_ETF_EPF Emp_ETF_EPFObj = new Emp_ETF_EPF();
        Emp_ETF_EPFObj.setSize(1084, 590);
        Emp_ETF_EPFObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(Emp_ETF_EPFObj);
        Admin_LPane.moveToFront(Emp_ETF_EPFObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_Emp_ETF_EPFActionPerformed

    private void Admin_Btn_EmpAccLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Btn_EmpAccLevelActionPerformed
        AAccessLevel AAccessLevelObj = new AAccessLevel();
        AAccessLevelObj.setSize(1084, 590);
        AAccessLevelObj.removeAll();
        Admin_LPane.removeAll();
        Admin_LPane.add(AAccessLevelObj);
        Admin_LPane.moveToFront(AAccessLevelObj);
        Admin_LPane.setVisible(true);
    }//GEN-LAST:event_Admin_Btn_EmpAccLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodCityAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodCityAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodCityAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodCityAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodCityAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Btn_AdvType;
    private javax.swing.JButton Admin_Btn_BillType;
    private javax.swing.JButton Admin_Btn_CustStage;
    private javax.swing.JButton Admin_Btn_Emp;
    private javax.swing.JButton Admin_Btn_EmpAccLevel;
    private javax.swing.JButton Admin_Btn_EmpAttend;
    private javax.swing.JButton Admin_Btn_EmpPos;
    private javax.swing.JButton Admin_Btn_EmpSalAdv;
    private javax.swing.JButton Admin_Btn_EmpSalPay;
    private javax.swing.JButton Admin_Btn_ReSetEmpPW;
    private javax.swing.JButton Admin_Btn_SetEtfEpf;
    private javax.swing.JLayeredPane Admin_LPane;
    private javax.swing.JLabel Main_Close;
    private javax.swing.JInternalFrame Main_InternalFrame_MenBar;
    private javax.swing.JMenuBar Main_MenBar;
    private javax.swing.JMenu Main_MenBar_Ad;
    private javax.swing.JMenuItem Main_MenBar_Ad_Ad;
    private javax.swing.JMenuItem Main_MenBar_Ad_MenAdType_AdType;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Ad_Sep2;
    private javax.swing.JMenu Main_MenBar_Complain;
    private javax.swing.JMenuItem Main_MenBar_Complain_Complain;
    private javax.swing.JMenuItem Main_MenBar_Cust_Cust;
    private javax.swing.JMenuItem Main_MenBar_Cust_CustAct;
    private javax.swing.JMenuItem Main_MenBar_Cust_MenCustStage_CustStage;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Cust_Sep1;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Cust_Sep2;
    private javax.swing.JMenu Main_MenBar_Customer;
    private javax.swing.JMenu Main_MenBar_Dispose;
    private javax.swing.JMenuItem Main_MenBar_Dispose_DispItems;
    private javax.swing.JMenu Main_MenBar_Donate;
    private javax.swing.JMenuItem Main_MenBar_Donate_Donate;
    private javax.swing.JMenu Main_MenBar_Emp;
    private javax.swing.JMenuItem Main_MenBar_Emp_EmpAttend;
    private javax.swing.JMenuItem Main_MenBar_Emp_Emp_ETF_EPF;
    private javax.swing.JMenuItem Main_MenBar_Emp_Employees;
    private javax.swing.JMenuItem Main_MenBar_Emp_MenEmpPos_EmpPos;
    private javax.swing.JMenuItem Main_MenBar_Emp_OT;
    private javax.swing.JMenuItem Main_MenBar_Emp_Salary;
    private javax.swing.JMenuItem Main_MenBar_Emp_SalaryAdv;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Emp_Sep1;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Emp_Sep2;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Emp_Sep3;
    private javax.swing.JMenu Main_MenBar_File;
    private javax.swing.JMenuItem Main_MenBar_File_Backup;
    private javax.swing.JMenuItem Main_MenBar_File_Exit;
    private javax.swing.JPopupMenu.Separator Main_MenBar_File_Sep_After_Backup;
    private javax.swing.JMenuItem Main_MenBar_File_Setting;
    private javax.swing.JMenu Main_MenBar_Item;
    private javax.swing.JMenuItem Main_MenBar_Item_Item;
    private javax.swing.JMenuItem Main_MenBar_Item_ItemSup;
    private javax.swing.JMenuItem Main_MenBar_Item_MenCat_Cat;
    private javax.swing.JMenuItem Main_MenBar_Item_MenILot_Lot;
    private javax.swing.JMenuItem Main_MenBar_Item_MenSubCat_SubCat;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Item_Sep_After_ByLot;
    private javax.swing.JMenuItem Main_MenBar_MenBilMac_BilMac;
    private javax.swing.JMenu Main_MenBar_Other;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Sep2;
    private javax.swing.JMenu Main_MenBar_Spend;
    private javax.swing.JMenu Main_MenBar_Spend_MenMainSpend;
    private javax.swing.JMenuItem Main_MenBar_Spend_MenMainSpend_MainSpend;
    private javax.swing.JMenuItem Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Spend_MenMainSpend_Sep1;
    private javax.swing.JMenuItem Main_MenBar_Spend_MenPetCash_PetCash;
    private javax.swing.JMenu Main_MenBar_Sup;
    private javax.swing.JMenuItem Main_MenBar_Sup_MenContPers_ContPers;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Sup_Sep1;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Sup_Sep2;
    private javax.swing.JMenuItem Main_MenBar_Sup_Sup;
    private javax.swing.JMenuItem Main_MenBar_Sup_SuplyItems;
    private javax.swing.JLabel Main_Minimize;
    private javax.swing.JLabel Main_Top;
    // End of variables declaration//GEN-END:variables
}
