/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FoodCityMain;

import Interfaces.Advertise;
import Interfaces.AdvertiseType;
import Interfaces.BType;
import Interfaces.CustStage;
import Interfaces.Backup;
import Interfaces.BilMach;
import Interfaces.Cat;
import Interfaces.Complain;
import Interfaces.ContPers;
import Interfaces.Cust;
import Interfaces.CustAct;
import Interfaces.DispItem;
import Interfaces.Donate;
import Interfaces.Emp;
import Interfaces.EmpAccount.EmpAccount;
import Interfaces.EmpAttend;
import Interfaces.EmpPos;
import Interfaces.EmpSal;
import Interfaces.EmpSalAdv;
import Interfaces.Emp_ETF_EPF;
import Interfaces.GRN;
import Interfaces.GRNR;
import Interfaces.Invoice;
import Interfaces.InvoiceR;
import Interfaces.Item;
import Interfaces.ItemLot;
import Interfaces.ItemSup;
import Interfaces.Login.EmpID;
import Interfaces.MainSpend;
import Interfaces.OT;
import Interfaces.PetC;
import Interfaces.SubCat;
import Interfaces.Sup;
import Interfaces.SupItem;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;


public class FoodCityMain extends javax.swing.JFrame {

    int posX, posY;//set var for move JFrame
    protected TimerThread timerThread;
    //String abcdUN;

    /**
     * Creates new form FoodCityMain
     */
    public FoodCityMain() {
        initComponents();
        runTimer();// Timer run start
        if (new EmpID().getEmpAccl().equals("Admin")) {
           Main_Btn_Admin.setEnabled(true);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Close = new javax.swing.JLabel();
        Main_Minimize = new javax.swing.JLabel();
        Main_Top = new javax.swing.JLabel();
        Main_Bottom_Date = new javax.swing.JLabel();
        Main_Bottom_Time = new javax.swing.JLabel();
        Main_Bottom_Time_Show = new javax.swing.JLabel();
        Main_Bottom_Date_Show = new javax.swing.JLabel();
        Main_InternalFrame_MenBar = new javax.swing.JInternalFrame();
        Main_MenBar = new javax.swing.JMenuBar();
        Main_MenBar_File = new javax.swing.JMenu();
        Main_MenBar_File_Backup = new javax.swing.JMenuItem();
        Main_MenBar_File_Setting = new javax.swing.JMenuItem();
        Main_MenBar_File_Sep_After_Backup = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_File_Exit = new javax.swing.JMenuItem();
        Main_MenBar_Item = new javax.swing.JMenu();
        Main_MenBar_Item_Item = new javax.swing.JMenuItem();
        Main_MenBar_Item_Sep_After_ByLot = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Item_MenILot_Lot = new javax.swing.JMenuItem();
        Main_MenBar_Item_MenCat_Cat = new javax.swing.JMenuItem();
        Main_MenBar_Item_MenSubCat_SubCat = new javax.swing.JMenuItem();
        Main_MenBar_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Item_ItemSup = new javax.swing.JMenuItem();
        Main_MenBar_Sup = new javax.swing.JMenu();
        Main_MenBar_Sup_Sup = new javax.swing.JMenuItem();
        Main_MenBar_Sup_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Sup_MenContPers_ContPers = new javax.swing.JMenuItem();
        Main_MenBar_Sup_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Sup_SuplyItems = new javax.swing.JMenuItem();
        Main_MenBar_Customer = new javax.swing.JMenu();
        Main_MenBar_Cust_Cust = new javax.swing.JMenuItem();
        Main_MenBar_Cust_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Cust_MenCustStage_CustStage = new javax.swing.JMenuItem();
        Main_MenBar_Cust_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Cust_CustAct = new javax.swing.JMenuItem();
        Main_MenBar_Emp = new javax.swing.JMenu();
        Main_MenBar_Emp_Employees = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Emp_MenEmpPos_EmpPos = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Emp__EmpETF_EPF = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Sep3 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Emp_EmpAttend = new javax.swing.JMenuItem();
        Main_MenBar_Emp_OT = new javax.swing.JMenuItem();
        Main_MenBar_Emp_Salary = new javax.swing.JMenuItem();
        Main_MenBar_Emp_SalaryAdv = new javax.swing.JMenuItem();
        Main_MenBar_Dispose = new javax.swing.JMenu();
        Main_MenBar_Dispose_DispItems = new javax.swing.JMenuItem();
        Main_MenBar_Ad = new javax.swing.JMenu();
        Main_MenBar_Ad_Ad = new javax.swing.JMenuItem();
        Main_MenBar_Ad_Sep2 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Ad_MenAdType_AdType = new javax.swing.JMenuItem();
        Main_MenBar_Spend = new javax.swing.JMenu();
        Main_MenBar_Spend_MenPetCash_PetCash = new javax.swing.JMenuItem();
        Main_MenBar_Spend_MenMainSpend = new javax.swing.JMenu();
        Main_MenBar_Spend_MenMainSpend_MainSpend = new javax.swing.JMenuItem();
        Main_MenBar_Spend_MenMainSpend_Sep1 = new javax.swing.JPopupMenu.Separator();
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp = new javax.swing.JMenuItem();
        Main_MenBar_Donate = new javax.swing.JMenu();
        Main_MenBar_Donate_Donate = new javax.swing.JMenuItem();
        Main_MenBar_Complain = new javax.swing.JMenu();
        Main_MenBar_Complain_Complain = new javax.swing.JMenuItem();
        Main_MenBar_Other = new javax.swing.JMenu();
        Main_MenBar_MenBilMac_BilMac = new javax.swing.JMenuItem();
        Main_Btn_IN = new javax.swing.JButton();
        Main_Btn_Item = new javax.swing.JButton();
        Main_Btn_Sup = new javax.swing.JButton();
        Main_Btn_Complain = new javax.swing.JButton();
        Main_Btn_Donate = new javax.swing.JButton();
        Main_Btn_Cust = new javax.swing.JButton();
        Main_Btn_Dispose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Main_Btn_GRN = new javax.swing.JButton();
        Main_Btn_INR = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Main_Btn_GRNR = new javax.swing.JButton();
        Main_Btn_Account = new javax.swing.JButton();
        Main_Btn_Admin = new javax.swing.JButton();
        Main_Bottom_BeforeDate = new javax.swing.JSeparator();
        Main_Bottom_AfterTime = new javax.swing.JSeparator();
        Main_Bottom_AfterDate = new javax.swing.JSeparator();
        Main_LPane = new javax.swing.JLayeredPane();
        jSeparator3 = new javax.swing.JSeparator();
        Main_Btn_Logout = new javax.swing.JButton();
        Main_Btn_PettyCash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1207, 640));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MAIN_CLOSE_2.png"))); // NOI18N
        Main_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Main_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main_CloseMouseExited(evt);
            }
        });
        getContentPane().add(Main_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1175, 0, -1, -1));

        Main_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MINI.png"))); // NOI18N
        Main_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main_MinimizeMouseExited(evt);
            }
        });
        getContentPane().add(Main_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1143, 0, -1, -1));

        Main_Top.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Main_Top.setForeground(new java.awt.Color(153, 153, 153));
        Main_Top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/Main_top3.png"))); // NOI18N
        Main_Top.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Main_TopMouseDragged(evt);
            }
        });
        Main_Top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Main_TopMousePressed(evt);
            }
        });
        getContentPane().add(Main_Top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Main_Bottom_Date.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Main_Bottom_Date.setForeground(new java.awt.Color(51, 51, 51));
        Main_Bottom_Date.setText("Date :");
        getContentPane().add(Main_Bottom_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 661, -1, -1));

        Main_Bottom_Time.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Main_Bottom_Time.setForeground(new java.awt.Color(51, 51, 51));
        Main_Bottom_Time.setText("Time :");
        getContentPane().add(Main_Bottom_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1085, 660, -1, -1));

        Main_Bottom_Time_Show.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Main_Bottom_Time_Show.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(Main_Bottom_Time_Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, 70, 20));

        Main_Bottom_Date_Show.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Main_Bottom_Date_Show.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(Main_Bottom_Date_Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 660, 122, 20));

        Main_InternalFrame_MenBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Main_InternalFrame_MenBar.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Main_InternalFrame_MenBar.setEnabled(false);
        Main_InternalFrame_MenBar.setVisible(true);

        Main_MenBar.setBackground(new java.awt.Color(51, 51, 51));
        Main_MenBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Main_MenBar.setForeground(new java.awt.Color(255, 255, 255));
        Main_MenBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_File.setText("File");
        Main_MenBar_File.setToolTipText("File");
        Main_MenBar_File.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_File_Backup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Main_MenBar_File_Backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/database.png"))); // NOI18N
        Main_MenBar_File_Backup.setText("Backup");
        Main_MenBar_File_Backup.setToolTipText("Backup");
        Main_MenBar_File_Backup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File_Backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_File_BackupActionPerformed(evt);
            }
        });
        Main_MenBar_File.add(Main_MenBar_File_Backup);

        Main_MenBar_File_Setting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Main_MenBar_File_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/settings (2).png"))); // NOI18N
        Main_MenBar_File_Setting.setText("Settings");
        Main_MenBar_File_Setting.setToolTipText("Settings");
        Main_MenBar_File_Setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File.add(Main_MenBar_File_Setting);
        Main_MenBar_File.add(Main_MenBar_File_Sep_After_Backup);

        Main_MenBar_File_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Main_MenBar_File_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/exit.png"))); // NOI18N
        Main_MenBar_File_Exit.setText("Exit");
        Main_MenBar_File_Exit.setToolTipText("Exit");
        Main_MenBar_File_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_File.add(Main_MenBar_File_Exit);

        Main_MenBar.add(Main_MenBar_File);

        Main_MenBar_Item.setText("Item");
        Main_MenBar_Item.setToolTipText("Item");
        Main_MenBar_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Item_Item.setText("Items");
        Main_MenBar_Item_Item.setToolTipText("Items");
        Main_MenBar_Item_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_ItemActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_Item);
        Main_MenBar_Item.add(Main_MenBar_Item_Sep_After_ByLot);

        Main_MenBar_Item_MenILot_Lot.setText("Item Lots");
        Main_MenBar_Item_MenILot_Lot.setToolTipText("Item Lots");
        Main_MenBar_Item_MenILot_Lot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_MenILot_Lot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_MenILot_LotActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_MenILot_Lot);

        Main_MenBar_Item_MenCat_Cat.setText("Categories");
        Main_MenBar_Item_MenCat_Cat.setToolTipText("Categories");
        Main_MenBar_Item_MenCat_Cat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_MenCat_Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_MenCat_CatActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_MenCat_Cat);

        Main_MenBar_Item_MenSubCat_SubCat.setText("Sub Categories");
        Main_MenBar_Item_MenSubCat_SubCat.setToolTipText("Sub Categories");
        Main_MenBar_Item_MenSubCat_SubCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_MenSubCat_SubCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_MenSubCat_SubCatActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_MenSubCat_SubCat);
        Main_MenBar_Item.add(Main_MenBar_Sep2);

        Main_MenBar_Item_ItemSup.setText("Item Supliers");
        Main_MenBar_Item_ItemSup.setToolTipText("Item Supliers");
        Main_MenBar_Item_ItemSup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Item_ItemSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Item_ItemSupActionPerformed(evt);
            }
        });
        Main_MenBar_Item.add(Main_MenBar_Item_ItemSup);

        Main_MenBar.add(Main_MenBar_Item);

        Main_MenBar_Sup.setText("Suplier");
        Main_MenBar_Sup.setToolTipText("Suplier");
        Main_MenBar_Sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Sup_Sup.setText("Supliers");
        Main_MenBar_Sup_Sup.setToolTipText("Supliers");
        Main_MenBar_Sup_Sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup_Sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Sup_SupActionPerformed(evt);
            }
        });
        Main_MenBar_Sup.add(Main_MenBar_Sup_Sup);
        Main_MenBar_Sup.add(Main_MenBar_Sup_Sep1);

        Main_MenBar_Sup_MenContPers_ContPers.setText("Contact Persons");
        Main_MenBar_Sup_MenContPers_ContPers.setToolTipText("Contact Persons");
        Main_MenBar_Sup_MenContPers_ContPers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup_MenContPers_ContPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Sup_MenContPers_ContPersActionPerformed(evt);
            }
        });
        Main_MenBar_Sup.add(Main_MenBar_Sup_MenContPers_ContPers);
        Main_MenBar_Sup.add(Main_MenBar_Sup_Sep2);

        Main_MenBar_Sup_SuplyItems.setText("Suply Items");
        Main_MenBar_Sup_SuplyItems.setToolTipText("Suply Items");
        Main_MenBar_Sup_SuplyItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Sup_SuplyItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Sup_SuplyItemsActionPerformed(evt);
            }
        });
        Main_MenBar_Sup.add(Main_MenBar_Sup_SuplyItems);

        Main_MenBar.add(Main_MenBar_Sup);

        Main_MenBar_Customer.setText("Customer");
        Main_MenBar_Customer.setToolTipText("Customer");
        Main_MenBar_Customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Customer.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Cust_Cust.setText("Customers");
        Main_MenBar_Cust_Cust.setToolTipText("Customers");
        Main_MenBar_Cust_Cust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Cust_Cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Cust_CustActionPerformed(evt);
            }
        });
        Main_MenBar_Customer.add(Main_MenBar_Cust_Cust);
        Main_MenBar_Customer.add(Main_MenBar_Cust_Sep1);

        Main_MenBar_Cust_MenCustStage_CustStage.setText("Customer Stages");
        Main_MenBar_Cust_MenCustStage_CustStage.setToolTipText("Customer Stages");
        Main_MenBar_Cust_MenCustStage_CustStage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Cust_MenCustStage_CustStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Cust_MenCustStage_CustStageActionPerformed(evt);
            }
        });
        Main_MenBar_Customer.add(Main_MenBar_Cust_MenCustStage_CustStage);
        Main_MenBar_Customer.add(Main_MenBar_Cust_Sep2);

        Main_MenBar_Cust_CustAct.setText("Customer Activity");
        Main_MenBar_Cust_CustAct.setToolTipText("Customer Activity");
        Main_MenBar_Cust_CustAct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Cust_CustAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Cust_CustActActionPerformed(evt);
            }
        });
        Main_MenBar_Customer.add(Main_MenBar_Cust_CustAct);

        Main_MenBar.add(Main_MenBar_Customer);

        Main_MenBar_Emp.setText("Employee");
        Main_MenBar_Emp.setToolTipText("Employee");
        Main_MenBar_Emp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Emp_Employees.setText("Employees");
        Main_MenBar_Emp_Employees.setToolTipText("Employees");
        Main_MenBar_Emp_Employees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_Employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_EmployeesActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_Employees);
        Main_MenBar_Emp.add(Main_MenBar_Emp_Sep1);

        Main_MenBar_Emp_MenEmpPos_EmpPos.setText("Employee Positions");
        Main_MenBar_Emp_MenEmpPos_EmpPos.setToolTipText("Employee Positions");
        Main_MenBar_Emp_MenEmpPos_EmpPos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_MenEmpPos_EmpPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_MenEmpPos_EmpPos);
        Main_MenBar_Emp.add(Main_MenBar_Emp_Sep2);

        Main_MenBar_Emp__EmpETF_EPF.setText("Employee ETF & EPF");
        Main_MenBar_Emp__EmpETF_EPF.setToolTipText("Employee ETF");
        Main_MenBar_Emp__EmpETF_EPF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp__EmpETF_EPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp__EmpETF_EPFActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp__EmpETF_EPF);
        Main_MenBar_Emp.add(Main_MenBar_Emp_Sep3);

        Main_MenBar_Emp_EmpAttend.setText("Employee Attendent");
        Main_MenBar_Emp_EmpAttend.setToolTipText("Employee Attendent");
        Main_MenBar_Emp_EmpAttend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_EmpAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_EmpAttendActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_EmpAttend);

        Main_MenBar_Emp_OT.setText("OT");
        Main_MenBar_Emp_OT.setToolTipText("OT");
        Main_MenBar_Emp_OT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_OT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_OTActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_OT);

        Main_MenBar_Emp_Salary.setText("Salary");
        Main_MenBar_Emp_Salary.setToolTipText("Salary");
        Main_MenBar_Emp_Salary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Emp_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_SalaryActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_Salary);

        Main_MenBar_Emp_SalaryAdv.setText("Salary Advance");
        Main_MenBar_Emp_SalaryAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Emp_SalaryAdvActionPerformed(evt);
            }
        });
        Main_MenBar_Emp.add(Main_MenBar_Emp_SalaryAdv);

        Main_MenBar.add(Main_MenBar_Emp);

        Main_MenBar_Dispose.setText("Dispose");
        Main_MenBar_Dispose.setToolTipText("Dispose");
        Main_MenBar_Dispose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Dispose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Dispose_DispItems.setText("Disposed Items");
        Main_MenBar_Dispose_DispItems.setToolTipText("Disposed Items");
        Main_MenBar_Dispose_DispItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Dispose_DispItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Dispose_DispItemsActionPerformed(evt);
            }
        });
        Main_MenBar_Dispose.add(Main_MenBar_Dispose_DispItems);

        Main_MenBar.add(Main_MenBar_Dispose);

        Main_MenBar_Ad.setText("Advertising");
        Main_MenBar_Ad.setToolTipText("Advertising");
        Main_MenBar_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Ad.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Ad_Ad.setText("Advertisings");
        Main_MenBar_Ad_Ad.setToolTipText("Advertises");
        Main_MenBar_Ad_Ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Ad_Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Ad_AdActionPerformed(evt);
            }
        });
        Main_MenBar_Ad.add(Main_MenBar_Ad_Ad);
        Main_MenBar_Ad.add(Main_MenBar_Ad_Sep2);

        Main_MenBar_Ad_MenAdType_AdType.setText("Advertise Types");
        Main_MenBar_Ad_MenAdType_AdType.setToolTipText("Advertise Types");
        Main_MenBar_Ad_MenAdType_AdType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Ad_MenAdType_AdType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Ad_MenAdType_AdTypeActionPerformed(evt);
            }
        });
        Main_MenBar_Ad.add(Main_MenBar_Ad_MenAdType_AdType);

        Main_MenBar.add(Main_MenBar_Ad);

        Main_MenBar_Spend.setText("Spendings");
        Main_MenBar_Spend.setToolTipText("Spendings");
        Main_MenBar_Spend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Spend_MenPetCash_PetCash.setText("Petty Cash");
        Main_MenBar_Spend_MenPetCash_PetCash.setToolTipText("Petty Cash");
        Main_MenBar_Spend_MenPetCash_PetCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend_MenPetCash_PetCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Spend_MenPetCash_PetCashActionPerformed(evt);
            }
        });
        Main_MenBar_Spend.add(Main_MenBar_Spend_MenPetCash_PetCash);

        Main_MenBar_Spend_MenMainSpend.setText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend.setToolTipText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Main_MenBar_Spend_MenMainSpend_MainSpend.setText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend_MainSpend.setToolTipText("Main Spendings");
        Main_MenBar_Spend_MenMainSpend_MainSpend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend_MenMainSpend_MainSpend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed(evt);
            }
        });
        Main_MenBar_Spend_MenMainSpend.add(Main_MenBar_Spend_MenMainSpend_MainSpend);
        Main_MenBar_Spend_MenMainSpend.add(Main_MenBar_Spend_MenMainSpend_Sep1);

        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.setText("Bill Types");
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.setToolTipText("Bill Types");
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed(evt);
            }
        });
        Main_MenBar_Spend_MenMainSpend.add(Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp);

        Main_MenBar_Spend.add(Main_MenBar_Spend_MenMainSpend);

        Main_MenBar.add(Main_MenBar_Spend);

        Main_MenBar_Donate.setText("Donations");
        Main_MenBar_Donate.setToolTipText("Donations");
        Main_MenBar_Donate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Donate.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Donate_Donate.setText("Donations");
        Main_MenBar_Donate_Donate.setToolTipText("Donations");
        Main_MenBar_Donate_Donate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Donate_Donate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Donate_DonateActionPerformed(evt);
            }
        });
        Main_MenBar_Donate.add(Main_MenBar_Donate_Donate);

        Main_MenBar.add(Main_MenBar_Donate);

        Main_MenBar_Complain.setText("Complains");
        Main_MenBar_Complain.setToolTipText("Complains");
        Main_MenBar_Complain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Complain.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_Complain_Complain.setText("Complains");
        Main_MenBar_Complain_Complain.setToolTipText("Complains");
        Main_MenBar_Complain_Complain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Complain_Complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_Complain_ComplainActionPerformed(evt);
            }
        });
        Main_MenBar_Complain.add(Main_MenBar_Complain_Complain);

        Main_MenBar.add(Main_MenBar_Complain);

        Main_MenBar_Other.setText("Other");
        Main_MenBar_Other.setToolTipText("Other");
        Main_MenBar_Other.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_Other.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Main_MenBar_MenBilMac_BilMac.setText("Billing Machines");
        Main_MenBar_MenBilMac_BilMac.setToolTipText("Billing Machines");
        Main_MenBar_MenBilMac_BilMac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_MenBar_MenBilMac_BilMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenBar_MenBilMac_BilMacActionPerformed(evt);
            }
        });
        Main_MenBar_Other.add(Main_MenBar_MenBilMac_BilMac);

        Main_MenBar.add(Main_MenBar_Other);

        Main_InternalFrame_MenBar.setJMenuBar(Main_MenBar);

        javax.swing.GroupLayout Main_InternalFrame_MenBarLayout = new javax.swing.GroupLayout(Main_InternalFrame_MenBar.getContentPane());
        Main_InternalFrame_MenBar.getContentPane().setLayout(Main_InternalFrame_MenBarLayout);
        Main_InternalFrame_MenBarLayout.setHorizontalGroup(
            Main_InternalFrame_MenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1207, Short.MAX_VALUE)
        );
        Main_InternalFrame_MenBarLayout.setVerticalGroup(
            Main_InternalFrame_MenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Main_InternalFrame_MenBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1207, -1));

        Main_Btn_IN.setBackground(new java.awt.Color(51, 51, 51));
        Main_Btn_IN.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Main_Btn_IN.setForeground(new java.awt.Color(69, 168, 78));
        Main_Btn_IN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/in.png"))); // NOI18N
        Main_Btn_IN.setToolTipText("Invoce");
        Main_Btn_IN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_IN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_INActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_IN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 93, 54));

        Main_Btn_Item.setBackground(new java.awt.Color(204, 204, 204));
        Main_Btn_Item.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Item.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Item.setText("Item");
        Main_Btn_Item.setToolTipText("Item");
        Main_Btn_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_ItemActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Item, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 93, 31));

        Main_Btn_Sup.setBackground(new java.awt.Color(204, 204, 204));
        Main_Btn_Sup.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Sup.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Sup.setText("Suplier");
        Main_Btn_Sup.setToolTipText("Suplier");
        Main_Btn_Sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_SupActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 93, 31));

        Main_Btn_Complain.setBackground(new java.awt.Color(204, 204, 204));
        Main_Btn_Complain.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Complain.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Complain.setText("Complains");
        Main_Btn_Complain.setToolTipText("Donation");
        Main_Btn_Complain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Main_Btn_Complain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_ComplainActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Complain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 93, 31));

        Main_Btn_Donate.setBackground(new java.awt.Color(204, 204, 204));
        Main_Btn_Donate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Donate.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Donate.setText("Donations");
        Main_Btn_Donate.setToolTipText("Donation");
        Main_Btn_Donate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Main_Btn_Donate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Donate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_DonateActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Donate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 93, 31));

        Main_Btn_Cust.setBackground(new java.awt.Color(204, 204, 204));
        Main_Btn_Cust.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Cust.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Cust.setText("Customer");
        Main_Btn_Cust.setToolTipText("Customer");
        Main_Btn_Cust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_CustActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 93, 31));

        Main_Btn_Dispose.setBackground(new java.awt.Color(204, 204, 204));
        Main_Btn_Dispose.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Dispose.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Dispose.setText("Dispose");
        Main_Btn_Dispose.setToolTipText("Dispose");
        Main_Btn_Dispose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Dispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_DisposeActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Dispose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 93, 31));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 99, -1));

        Main_Btn_GRN.setBackground(new java.awt.Color(51, 51, 51));
        Main_Btn_GRN.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Main_Btn_GRN.setForeground(new java.awt.Color(69, 168, 78));
        Main_Btn_GRN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/grn.png"))); // NOI18N
        Main_Btn_GRN.setToolTipText("Good Resive Note");
        Main_Btn_GRN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_GRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_GRNActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_GRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 93, 54));

        Main_Btn_INR.setBackground(new java.awt.Color(51, 51, 51));
        Main_Btn_INR.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Main_Btn_INR.setForeground(new java.awt.Color(218, 77, 77));
        Main_Btn_INR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/inr.png"))); // NOI18N
        Main_Btn_INR.setToolTipText("Invoce Return");
        Main_Btn_INR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_INR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_INRActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_INR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 93, 54));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 99, -1));

        Main_Btn_GRNR.setBackground(new java.awt.Color(51, 51, 51));
        Main_Btn_GRNR.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Main_Btn_GRNR.setForeground(new java.awt.Color(218, 77, 77));
        Main_Btn_GRNR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/grnr.png"))); // NOI18N
        Main_Btn_GRNR.setToolTipText("God Resive Note Return");
        Main_Btn_GRNR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_GRNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_GRNRActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_GRNR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 93, 54));

        Main_Btn_Account.setBackground(new java.awt.Color(76, 90, 230));
        Main_Btn_Account.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Account.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/user.png"))); // NOI18N
        Main_Btn_Account.setToolTipText("Go to Account");
        Main_Btn_Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_AccountActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 41, -1));

        Main_Btn_Admin.setBackground(new java.awt.Color(0, 153, 51));
        Main_Btn_Admin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Admin.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/admin (2).png"))); // NOI18N
        Main_Btn_Admin.setToolTipText("Log Out");
        Main_Btn_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Admin.setEnabled(false);
        Main_Btn_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 620, 41, -1));

        Main_Bottom_BeforeDate.setBackground(new java.awt.Color(240, 240, 240));
        Main_Bottom_BeforeDate.setForeground(new java.awt.Color(153, 153, 153));
        Main_Bottom_BeforeDate.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(Main_Bottom_BeforeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1197, 660, -1, 20));

        Main_Bottom_AfterTime.setBackground(new java.awt.Color(240, 240, 240));
        Main_Bottom_AfterTime.setForeground(new java.awt.Color(153, 153, 153));
        Main_Bottom_AfterTime.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(Main_Bottom_AfterTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1078, 660, -1, 20));

        Main_Bottom_AfterDate.setBackground(new java.awt.Color(240, 240, 240));
        Main_Bottom_AfterDate.setForeground(new java.awt.Color(153, 153, 153));
        Main_Bottom_AfterDate.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(Main_Bottom_AfterDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 661, -1, 20));

        Main_LPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Main_LPaneLayout = new javax.swing.GroupLayout(Main_LPane);
        Main_LPane.setLayout(Main_LPaneLayout);
        Main_LPaneLayout.setHorizontalGroup(
            Main_LPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        Main_LPaneLayout.setVerticalGroup(
            Main_LPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        getContentPane().add(Main_LPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 1090, 590));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 99, -1));

        Main_Btn_Logout.setBackground(new java.awt.Color(172, 48, 48));
        Main_Btn_Logout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_Logout.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/logout (2).png"))); // NOI18N
        Main_Btn_Logout.setToolTipText("Log Out");
        Main_Btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 41, -1));

        Main_Btn_PettyCash.setBackground(new java.awt.Color(204, 204, 204));
        Main_Btn_PettyCash.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Main_Btn_PettyCash.setForeground(new java.awt.Color(51, 51, 51));
        Main_Btn_PettyCash.setText("Petty Cash");
        Main_Btn_PettyCash.setToolTipText("Dispose");
        Main_Btn_PettyCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Btn_PettyCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Btn_PettyCashActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Btn_PettyCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 31));

        setSize(new java.awt.Dimension(1216, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Main_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_CloseMouseClicked
        EndTimer();// Timer Ending
        this.dispose();// MouseEvent Close Button
    }//GEN-LAST:event_Main_CloseMouseClicked

    private void Main_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_CloseMouseEntered
        Main_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MAIN_CLOSE.png")));//Mouse Entering
    }//GEN-LAST:event_Main_CloseMouseEntered

    private void Main_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_CloseMouseExited
        Main_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MAIN_CLOSE_2.png")));//Mouse Exiting
    }//GEN-LAST:event_Main_CloseMouseExited

    private void Main_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_MinimizeMouseClicked
        this.setState(Frame.ICONIFIED);// Minimize
    }//GEN-LAST:event_Main_MinimizeMouseClicked

    private void Main_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_MinimizeMouseEntered
        Main_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MINI_2.png")));
    }//GEN-LAST:event_Main_MinimizeMouseEntered

    private void Main_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_MinimizeMouseExited
        Main_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Btn_icon/MINI.png")));
    }//GEN-LAST:event_Main_MinimizeMouseExited

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void Main_TopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_TopMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - posX, this.getLocation().y + evt.getY() - posY);//Set moving JFrame
    }//GEN-LAST:event_Main_TopMouseDragged

    private void Main_TopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_TopMousePressed
        posX = evt.getX();//Mouse Get X
        posY = evt.getY();//Mouse Get Y
    }//GEN-LAST:event_Main_TopMousePressed

    private void Main_MenBar_File_BackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_File_BackupActionPerformed
        Backup BackupObj = new Backup();
        BackupObj.setSize(1084, 590);
        BackupObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(BackupObj);
        Main_LPane.moveToFront(BackupObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_File_BackupActionPerformed

    private void Main_MenBar_Emp_EmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_EmployeesActionPerformed
        Emp EmpObj = new Emp();
        EmpObj.setSize(1084, 590);
        EmpObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(EmpObj);
        Main_LPane.moveToFront(EmpObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_EmployeesActionPerformed

    private void Main_MenBar_Emp_OTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_OTActionPerformed
        OT OTObj = new OT();
        OTObj.setSize(1084, 590);
        OTObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(OTObj);
        Main_LPane.moveToFront(OTObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_OTActionPerformed

    private void Main_MenBar_Emp_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_SalaryActionPerformed
        EmpSal EmpSalObj = new EmpSal();
        EmpSalObj.setSize(1084, 590);
        EmpSalObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(EmpSalObj);
        Main_LPane.moveToFront(EmpSalObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_SalaryActionPerformed

    private void Main_MenBar_Ad_AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Ad_AdActionPerformed
        Advertise AdvertiseObj = new Advertise();
        AdvertiseObj.setSize(1084, 590);
        AdvertiseObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(AdvertiseObj);
        Main_LPane.moveToFront(AdvertiseObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Ad_AdActionPerformed

    private void Main_MenBar_Spend_MenPetCash_PetCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Spend_MenPetCash_PetCashActionPerformed
        PetC PetCObj = new PetC();
        PetCObj.setSize(1084, 590);
        PetCObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(PetCObj);
        Main_LPane.moveToFront(PetCObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Spend_MenPetCash_PetCashActionPerformed

    private void Main_Btn_INActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_INActionPerformed
        Invoice InvoiceObj = new Invoice();
        InvoiceObj.setSize(1084, 590);
        InvoiceObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(InvoiceObj);
        Main_LPane.moveToFront(InvoiceObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_INActionPerformed

    private void Main_Btn_INRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_INRActionPerformed
        InvoiceR InvoiceRObj = new InvoiceR();
        InvoiceRObj.setSize(1084, 590);
        InvoiceRObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(InvoiceRObj);
        Main_LPane.moveToFront(InvoiceRObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_INRActionPerformed

    private void Main_Btn_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_AccountActionPerformed
        EmpAccount EmpAccountObj = new EmpAccount();
        EmpAccountObj.setVisible(true);
    }//GEN-LAST:event_Main_Btn_AccountActionPerformed

    private void Main_Btn_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_AdminActionPerformed
        FoodCityAdmin FoodCityAdminObj = new FoodCityAdmin();
        FoodCityAdminObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Main_Btn_AdminActionPerformed

    private void Main_MenBar_Item_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_ItemActionPerformed
        Item ItemObj = new Item();
        ItemObj.setSize(1084, 590);
        ItemObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(ItemObj);
        Main_LPane.moveToFront(ItemObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_ItemActionPerformed

    private void Main_Btn_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_ItemActionPerformed
        Item ItemObj = new Item();
        ItemObj.setSize(1084, 590);
        ItemObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(ItemObj);
        Main_LPane.moveToFront(ItemObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_ItemActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void Main_MenBar_Item_MenILot_LotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_MenILot_LotActionPerformed
        ItemLot ItemLotObj = new ItemLot();
        ItemLotObj.setSize(1084, 590);
        ItemLotObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(ItemLotObj);
        Main_LPane.moveToFront(ItemLotObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_MenILot_LotActionPerformed

    private void Main_MenBar_Item_MenCat_CatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_MenCat_CatActionPerformed
        Cat CatObj = new Cat();
        CatObj.setSize(1084, 590);
        CatObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(CatObj);
        Main_LPane.moveToFront(CatObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_MenCat_CatActionPerformed

    private void Main_MenBar_Item_MenSubCat_SubCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_MenSubCat_SubCatActionPerformed
        SubCat SubCatObj = new SubCat();
        SubCatObj.setSize(1084, 590);
        SubCatObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(SubCatObj);
        Main_LPane.moveToFront(SubCatObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_MenSubCat_SubCatActionPerformed

    private void Main_MenBar_Item_ItemSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Item_ItemSupActionPerformed
        ItemSup ItemSupObj = new ItemSup();
        ItemSupObj.setSize(1084, 590);
        ItemSupObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(ItemSupObj);
        Main_LPane.moveToFront(ItemSupObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Item_ItemSupActionPerformed

    private void Main_MenBar_Sup_SupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Sup_SupActionPerformed
        Sup SupObj = new Sup();
        SupObj.setSize(1084, 590);
        SupObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(SupObj);
        Main_LPane.moveToFront(SupObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Sup_SupActionPerformed

    private void Main_Btn_SupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_SupActionPerformed
        Sup SupObj = new Sup();
        SupObj.setSize(1084, 590);
        SupObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(SupObj);
        Main_LPane.moveToFront(SupObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_SupActionPerformed

    private void Main_MenBar_Sup_MenContPers_ContPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Sup_MenContPers_ContPersActionPerformed
        ContPers ContPersObj = new ContPers();
        ContPersObj.setSize(1084, 590);
        ContPersObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(ContPersObj);
        Main_LPane.moveToFront(ContPersObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Sup_MenContPers_ContPersActionPerformed

    private void Main_MenBar_Sup_SuplyItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Sup_SuplyItemsActionPerformed
        SupItem SupItemObj = new SupItem();
        SupItemObj.setSize(1084, 590);
        SupItemObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(SupItemObj);
        Main_LPane.moveToFront(SupItemObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Sup_SuplyItemsActionPerformed

    private void Main_MenBar_Cust_CustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Cust_CustActionPerformed
        Cust CustObj = new Cust();
        CustObj.setSize(1084, 590);
        CustObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(CustObj);
        Main_LPane.moveToFront(CustObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Cust_CustActionPerformed

    private void Main_Btn_CustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_CustActionPerformed
        Cust CustObj = new Cust();
        CustObj.setSize(1084, 590);
        CustObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(CustObj);
        Main_LPane.moveToFront(CustObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_CustActionPerformed

    private void Main_MenBar_Cust_MenCustStage_CustStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Cust_MenCustStage_CustStageActionPerformed
        CustStage CustStageObj = new CustStage();
        CustStageObj.setSize(1084, 590);
        CustStageObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(CustStageObj);
        Main_LPane.moveToFront(CustStageObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Cust_MenCustStage_CustStageActionPerformed

    private void Main_MenBar_Cust_CustActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Cust_CustActActionPerformed
        CustAct CustActObj = new CustAct();
        CustActObj.setSize(1084, 590);
        CustActObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(CustActObj);
        Main_LPane.moveToFront(CustActObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Cust_CustActActionPerformed

    private void Main_Btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_LogoutActionPerformed
        /*if (abcdUN.equals("admin")) {
            CustAct CustActObj = new CustAct();
        CustActObj.setSize(1084, 590);
        CustActObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(CustActObj);
        Main_LPane.moveToFront(CustActObj);
        Main_LPane.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this , "you do not have proper access");
        }*/
    }//GEN-LAST:event_Main_Btn_LogoutActionPerformed

    private void Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed
        EmpPos EmpPosObj = new EmpPos();
        EmpPosObj.setSize(1084, 590);
        EmpPosObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(EmpPosObj);
        Main_LPane.moveToFront(EmpPosObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_MenEmpPos_EmpPosActionPerformed

    private void Main_MenBar_Dispose_DispItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Dispose_DispItemsActionPerformed
        DispItem DispItemObj = new DispItem();
        DispItemObj.setSize(1084, 590);
        DispItemObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(DispItemObj);
        Main_LPane.moveToFront(DispItemObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Dispose_DispItemsActionPerformed

    private void Main_Btn_DisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_DisposeActionPerformed
        DispItem DispItemObj = new DispItem();
        DispItemObj.setSize(1084, 590);
        DispItemObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(DispItemObj);
        Main_LPane.moveToFront(DispItemObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_DisposeActionPerformed

    private void Main_MenBar_Ad_MenAdType_AdTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Ad_MenAdType_AdTypeActionPerformed
        AdvertiseType AdvertiseTypeObj = new AdvertiseType();
        AdvertiseTypeObj.setSize(1084, 590);
        AdvertiseTypeObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(AdvertiseTypeObj);
        Main_LPane.moveToFront(AdvertiseTypeObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Ad_MenAdType_AdTypeActionPerformed

    private void Main_MenBar_Donate_DonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Donate_DonateActionPerformed
        Donate DonateObj = new Donate();
        DonateObj.setSize(1084, 590);
        DonateObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(DonateObj);
        Main_LPane.moveToFront(DonateObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Donate_DonateActionPerformed

    private void Main_Btn_DonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_DonateActionPerformed
        Donate DonateObj = new Donate();
        DonateObj.setSize(1084, 590);
        DonateObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(DonateObj);
        Main_LPane.moveToFront(DonateObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_DonateActionPerformed

    private void Main_MenBar_Complain_ComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Complain_ComplainActionPerformed
        Complain ComplainObj = new Complain();
        ComplainObj.setSize(1084, 590);
        ComplainObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(ComplainObj);
        Main_LPane.moveToFront(ComplainObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Complain_ComplainActionPerformed

    private void Main_Btn_ComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_ComplainActionPerformed
        Complain ComplainObj = new Complain();
        ComplainObj.setSize(1084, 590);
        ComplainObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(ComplainObj);
        Main_LPane.moveToFront(ComplainObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_ComplainActionPerformed

    private void Main_MenBar_MenBilMac_BilMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_MenBilMac_BilMacActionPerformed
        BilMach BilMachObj = new BilMach();
        BilMachObj.setSize(1084, 590);
        BilMachObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(BilMachObj);
        Main_LPane.moveToFront(BilMachObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_MenBilMac_BilMacActionPerformed

    private void Main_Btn_PettyCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_PettyCashActionPerformed
        PetC PetCObj = new PetC();
        PetCObj.setSize(1084, 590);
        PetCObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(PetCObj);
        Main_LPane.moveToFront(PetCObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_PettyCashActionPerformed

    private void Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed
        MainSpend MainSpendObj = new MainSpend();
        MainSpendObj.setSize(1084, 590);
        MainSpendObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(MainSpendObj);
        Main_LPane.moveToFront(MainSpendObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Spend_MenMainSpend_MainSpendActionPerformed

    private void Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed
        BType BTypeObj = new BType();
        BTypeObj.setSize(1084, 590);
        BTypeObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(BTypeObj);
        Main_LPane.moveToFront(BTypeObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Spend_MenMainSpend_MenBil_BilTypActionPerformed

    private void Main_Btn_GRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_GRNActionPerformed
        GRN GRNObj = new GRN();
        GRNObj.setSize(1084, 590);
        GRNObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(GRNObj);
        Main_LPane.moveToFront(GRNObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_GRNActionPerformed

    private void Main_Btn_GRNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Btn_GRNRActionPerformed
        GRNR GRNRObj = new GRNR();
        GRNRObj.setSize(1084, 590);
        GRNRObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(GRNRObj);
        Main_LPane.moveToFront(GRNRObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_Btn_GRNRActionPerformed

    private void Main_MenBar_Emp_EmpAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_EmpAttendActionPerformed
        EmpAttend EmpAttendObj = new EmpAttend();
        EmpAttendObj.setSize(1084, 590);
        EmpAttendObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(EmpAttendObj);
        Main_LPane.moveToFront(EmpAttendObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_EmpAttendActionPerformed

    private void Main_MenBar_Emp_SalaryAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp_SalaryAdvActionPerformed
        EmpSalAdv EmpSalAdvObj = new EmpSalAdv();
        EmpSalAdvObj.setSize(1084, 590);
        EmpSalAdvObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(EmpSalAdvObj);
        Main_LPane.moveToFront(EmpSalAdvObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp_SalaryAdvActionPerformed

    private void Main_MenBar_Emp__EmpETF_EPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenBar_Emp__EmpETF_EPFActionPerformed
        Emp_ETF_EPF Emp_ETF_EPFObj = new Emp_ETF_EPF();
        Emp_ETF_EPFObj.setSize(1084, 590);
        Emp_ETF_EPFObj.removeAll();
        Main_LPane.removeAll();
        Main_LPane.add(Emp_ETF_EPFObj);
        Main_LPane.moveToFront(Emp_ETF_EPFObj);
        Main_LPane.setVisible(true);
    }//GEN-LAST:event_Main_MenBar_Emp__EmpETF_EPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodCityMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodCityMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodCityMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodCityMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodCityMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Main_Bottom_AfterDate;
    private javax.swing.JSeparator Main_Bottom_AfterTime;
    private javax.swing.JSeparator Main_Bottom_BeforeDate;
    private javax.swing.JLabel Main_Bottom_Date;
    private static javax.swing.JLabel Main_Bottom_Date_Show;
    private javax.swing.JLabel Main_Bottom_Time;
    private static javax.swing.JLabel Main_Bottom_Time_Show;
    private javax.swing.JButton Main_Btn_Account;
    private javax.swing.JButton Main_Btn_Admin;
    private javax.swing.JButton Main_Btn_Complain;
    private javax.swing.JButton Main_Btn_Cust;
    private javax.swing.JButton Main_Btn_Dispose;
    private javax.swing.JButton Main_Btn_Donate;
    private javax.swing.JButton Main_Btn_GRN;
    private javax.swing.JButton Main_Btn_GRNR;
    private javax.swing.JButton Main_Btn_IN;
    private javax.swing.JButton Main_Btn_INR;
    private javax.swing.JButton Main_Btn_Item;
    private javax.swing.JButton Main_Btn_Logout;
    private javax.swing.JButton Main_Btn_PettyCash;
    private javax.swing.JButton Main_Btn_Sup;
    private javax.swing.JLabel Main_Close;
    private javax.swing.JInternalFrame Main_InternalFrame_MenBar;
    private javax.swing.JLayeredPane Main_LPane;
    private javax.swing.JMenuBar Main_MenBar;
    private javax.swing.JMenu Main_MenBar_Ad;
    private javax.swing.JMenuItem Main_MenBar_Ad_Ad;
    private javax.swing.JMenuItem Main_MenBar_Ad_MenAdType_AdType;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Ad_Sep2;
    private javax.swing.JMenu Main_MenBar_Complain;
    private javax.swing.JMenuItem Main_MenBar_Complain_Complain;
    private javax.swing.JMenuItem Main_MenBar_Cust_Cust;
    private javax.swing.JMenuItem Main_MenBar_Cust_CustAct;
    private javax.swing.JMenuItem Main_MenBar_Cust_MenCustStage_CustStage;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Cust_Sep1;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Cust_Sep2;
    private javax.swing.JMenu Main_MenBar_Customer;
    private javax.swing.JMenu Main_MenBar_Dispose;
    private javax.swing.JMenuItem Main_MenBar_Dispose_DispItems;
    private javax.swing.JMenu Main_MenBar_Donate;
    private javax.swing.JMenuItem Main_MenBar_Donate_Donate;
    private javax.swing.JMenu Main_MenBar_Emp;
    private javax.swing.JMenuItem Main_MenBar_Emp_EmpAttend;
    private javax.swing.JMenuItem Main_MenBar_Emp_Employees;
    private javax.swing.JMenuItem Main_MenBar_Emp_MenEmpPos_EmpPos;
    private javax.swing.JMenuItem Main_MenBar_Emp_OT;
    private javax.swing.JMenuItem Main_MenBar_Emp_Salary;
    private javax.swing.JMenuItem Main_MenBar_Emp_SalaryAdv;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Emp_Sep1;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Emp_Sep2;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Emp_Sep3;
    private javax.swing.JMenuItem Main_MenBar_Emp__EmpETF_EPF;
    private javax.swing.JMenu Main_MenBar_File;
    private javax.swing.JMenuItem Main_MenBar_File_Backup;
    private javax.swing.JMenuItem Main_MenBar_File_Exit;
    private javax.swing.JPopupMenu.Separator Main_MenBar_File_Sep_After_Backup;
    private javax.swing.JMenuItem Main_MenBar_File_Setting;
    private javax.swing.JMenu Main_MenBar_Item;
    private javax.swing.JMenuItem Main_MenBar_Item_Item;
    private javax.swing.JMenuItem Main_MenBar_Item_ItemSup;
    private javax.swing.JMenuItem Main_MenBar_Item_MenCat_Cat;
    private javax.swing.JMenuItem Main_MenBar_Item_MenILot_Lot;
    private javax.swing.JMenuItem Main_MenBar_Item_MenSubCat_SubCat;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Item_Sep_After_ByLot;
    private javax.swing.JMenuItem Main_MenBar_MenBilMac_BilMac;
    private javax.swing.JMenu Main_MenBar_Other;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Sep2;
    private javax.swing.JMenu Main_MenBar_Spend;
    private javax.swing.JMenu Main_MenBar_Spend_MenMainSpend;
    private javax.swing.JMenuItem Main_MenBar_Spend_MenMainSpend_MainSpend;
    private javax.swing.JMenuItem Main_MenBar_Spend_MenMainSpend_MenBil_BilTyp;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Spend_MenMainSpend_Sep1;
    private javax.swing.JMenuItem Main_MenBar_Spend_MenPetCash_PetCash;
    private javax.swing.JMenu Main_MenBar_Sup;
    private javax.swing.JMenuItem Main_MenBar_Sup_MenContPers_ContPers;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Sup_Sep1;
    private javax.swing.JPopupMenu.Separator Main_MenBar_Sup_Sep2;
    private javax.swing.JMenuItem Main_MenBar_Sup_Sup;
    private javax.swing.JMenuItem Main_MenBar_Sup_SuplyItems;
    private javax.swing.JLabel Main_Minimize;
    private javax.swing.JLabel Main_Top;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    // Timer Start Method
    private void runTimer() {
        timerThread = new TimerThread(Main_Bottom_Date_Show, Main_Bottom_Time_Show);
        timerThread.start();
    }

    // Timer End Method
    public void EndTimer() {
        timerThread.setRunning(false);
        System.exit(0);
    }

    ////// Timer Ttread
    public class TimerThread extends Thread {

        protected boolean isRunning;

        protected JLabel dateLabel;
        protected JLabel timeLabel;

        protected SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, d MMM yyyy");
        protected SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");

        public TimerThread(JLabel dateLabel, JLabel timeLabel) {
            this.dateLabel = dateLabel;
            this.timeLabel = timeLabel;
            this.isRunning = true;
        }

        @Override
        public void run() {
            while (isRunning) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        Calendar currentCalendar = Calendar.getInstance();
                        Date currentTime = currentCalendar.getTime();
                        dateLabel.setText(dateFormat.format(currentTime));
                        timeLabel.setText(timeFormat.format(currentTime));
                    }

                });

                try {
                    Thread.sleep(5000L);
                } catch (InterruptedException e) {
                }
            }
        }

        public void setRunning(boolean isRunning) {
            this.isRunning = isRunning;
        }

    }

}
